### ISSUE TITLE
Download Map Errors

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#967] opened 2016-07-15 18:47 UTC
From: https://github.com/triplea-game/triplea/issues/948

I am having trouble with testing it out :(
I installed 1.9.0.0.2533
Could not load any of my downloaded maps without getting errors.
So I deleted all downloaded maps and opened TripleA program.
Looked at “select game” and only tutorial was there (as expected).
Then tried to download maps but cant. I am getting this error:

triplea.engine.version.bin:1.9
Loading map: tutorial, from: C:\Games\triplea\maps\tutorial.zip
> Exception: java.net.ConnectException: Connection timed out: connect
java.lang.IllegalStateException: java.net.ConnectException: Connection timed out: connect
at games.strategy.engine.framework.map.download.DownloadUtils.getDownloadLength(DownloadUtils.java:24)
at games.strategy.engine.framework.map.download.DownloadMapsWindow.createLabelText(DownloadMapsWindow.java:285)
at games.strategy.engine.framework.map.download.DownloadMapsWindow.lambda$updateMapUrlAndSizeLabel$55(DownloadMapsWindow.java:272)
at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
at java.net.DualStackPlainSocketImpl.connect0(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.PlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at sun.net.NetworkClient.doConnect(Unknown Source)
at sun.net.www.http.HttpClient.openServer(Unknown Source)
at sun.net.www.http.HttpClient.openServer(Unknown Source)
at sun.net.www.http.HttpClient.(Unknown Source)
at sun.net.www.http.HttpClient.New(Unknown Source)
at sun.net.www.http.HttpClient.New(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
at java.net.HttpURLConnection.getResponseCode(Unknown Source)
at games.strategy.engine.framework.map.download.DownloadUtils.getDownloadLength(DownloadUtils.java:16)
... 3 more

**Comment by FrostionAAA** [comment] 2016-07-16 15:41
I still can’t open and run TripleA maps. I will just post this and then try to reinstall tripleA without installing any maps and then try again. This is what I experience:
1.	Run TripleA program.
2.	I press “Select Game”.
3.	I choose “Tutorial”.
4.	“Start Local Game”, I change nothing, and hit “Play”.
The game does not start, but instead this long Java error pops up, and it seems to grow longer and longer by the split second. Like if the game is getting new errors by the split second.
The Java window is the only TripleA window still open, so when I closed it I have closed the TripleA down.

**His is what the error looks like after a few seconds:**
triplea.engine.version.bin:1.9
Loading map: tutorial, from: C:\Games\triplea\maps\tutorial.zip
Loading map: tutorial, from: C:\Games\triplea\maps\tutorial.zip
Loading map: tutorial, from: C:\Games\triplea\maps\tutorial.zip
Exception: null
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at games.strategy.ui.SwingAction.invokeAndWait(SwingAction.java:61)
	at games.strategy.triplea.TripleA.startGame(TripleA.java:132)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:49)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$32(AbstractLauncher.java:42)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source)
	at java.util.Optional.<init>(Unknown Source)
	at java.util.Optional.of(Unknown Source)
	at games.strategy.triplea.ui.TripleAFrame.getInGameLobbyWatcher(TripleAFrame.java:2176)
	at games.strategy.triplea.ui.menubar.TripleAMenuBar.<init>(TripleAMenuBar.java:77)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:281)
	at games.strategy.triplea.TripleA.lambda$startGame$154(TripleA.java:134)
	at games.strategy.ui.SwingAction.lambda$invokeAndWait$344(SwingAction.java:61)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans
Game frame is null, but entered player step: italiansCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansNonCombatMove for player: Human:Italians
Game frame is null, but entered player step: italiansEndTurn for player: Human:Italians
Game frame is null, but entered player step: germansEndTurn for player: Human:Germans

**Comment by FrostionAAA** [comment] 2016-07-16 15:56
New info:
When I went to uninstall TripleA in windows program manager, it seemed that TripleA was running in the background without me being able to see the game:
![uninstall1](https://cloud.githubusercontent.com/assets/15268177/16895665/6ac8bcd6-4b7e-11e6-953f-71d368a5502c.png)

I went to look in the windows task manager, and here I could shot it down so I could uninstall:
![uninstall2](https://cloud.githubusercontent.com/assets/15268177/16895668/6fd69662-4b7e-11e6-9b94-406979e79418.png)

**Comment by FrostionAAA** [comment] 2016-07-16 16:07
Uninstalled TripleA 1.9.0.0.2533, removed all downloaded maps, reinstalled same TripleA version and try to run tutorial but got the same problem: When trying to run tutorial a Java error pops up and TripleA goes to run in the background, using 25-30% of the CPU and I have to go to the task manager to shot it down.

I will now try to install the recommended release version 1.9.0.0.2461. and see if it acts any different.

**Comment by FrostionAAA** [comment] 2016-07-16 16:51
I tried out the installer “triplea_windows-x64_1.9.0.0.2533.exe” before I went to install the release candidate. The x64 version did install but I could not start the program at all, but only saw the TripleA logo with the black background pop up and then shot down again.

I installed “triplea_windows_1.9.0.0.2461.exe” and it acted just like all of the above.

I have tied to update Java to see if this was the problem, and installed what seems to be the latest version (jre-8u91-windows-x64.exe) but that did not help either.

FINALLY I installed triplea_windows_1.9.0.0.2441.exe, as this is an 8 day old version right now, and this version of TripleA works. YAY! :)

But sadly this also means that the latest versions are making trouble for my PC? :(

**Comment by DanVanAtta** [comment] 2016-07-17 05:42
@FrostionAAA , big thank you for the bug report with error. I was able to reproduce the problem. The root issue was a bug on this line: `TripleAFrame.java:2176`. From there the main game window error'ed out and was then null. It appears in that state the game then would cycle through turns ad infinitum... This problem should now be fixed in the latest prerelease, 2553

**Comment by FrostionAAA** [comment] 2016-07-17 12:20
I installed very latest ”triplea_windows_1.9.0.0.2562.exe”, downloaded maps and played with no errors, as far as I am concerned this issue has been fixed :)

**Closed** 2016-07-17 18:01 UTC
Labels: Close Pending Confirmation, Include with 1.9 release, Regression
