### ISSUE TITLE
Units freezing prerelease 2689

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#1034] opened 2016-08-06 15:41 UTC
Have been playing a few games with prereleases. 
Working smooth and flawless until this happens:

Version: 1.9.0.0.2689
Map: NWO
Problem: In round 9 it's the French turn to play. All landunits piled up on 1 territory are immobile. Destroyer and 2 fighters (in other territory) can move normally.
When trying to move individual units the game says:
-Infantry: Units cannot participate in multiple battles
-Armour+Truck: not all units have enough movement
-Artillery: Not all units can blitz
When trying to move them all at once:
-Units cannot participate in multiple battles

Is a normal game against Hard-AI. Only edited the 2 AA-guns few times but in previous turns(not last 2 turns at least).

Game is still open if you'd like me to perform any other action.
Savegame: 
[ReleaseTestNWO.zip](https://github.com/triplea-game/triplea/files/405066/ReleaseTestNWO.zip)

**Comment by ron-murhammer** [comment] 2016-08-08 03:01
@ZjelcoP Yeah there is definitely an issue with that save game. It appears the unit are marked as already been in combat that turn so can't move again. Hard to say why that occurred. Did you happen to edit units in that territory during the past round or anything?

If you see this occur again or if you can reproduce getting to that situation please add details here. As of now, I don't really have any idea why that happened.

**Comment by DanVanAtta** [comment] 2016-08-08 04:01
@ron-murhammer , I haven't spotted anything that would even update the 'wasInCombat' flag. Looks like only the game XML can enable that field. In the save game, I clicked through to the next round, the problem is persistent with the French through to the next round.

**Comment by ron-murhammer** [comment] 2016-08-08 05:07
@DanVanAtta It is done through the Change objects indirectly. In this particular case its called either at the start or end of turns I believe through `MoveDelegate.getResetUnitStateChange()`. All of the Change objects eventually funnel down to `PropertyUtil` for lots of reflection fun!

**Comment by ron-murhammer** [comment] 2016-08-15 02:06
@ZjelcoP Unless we can reproduce getting to this problem or it happens again I think we should just close this for now. Somehow the save game got messed up and the units are marked as already been in combat so can't move again. That should never happen though. If you see this happen again please reopen this issue.

**Comment by ZjelcoP** [comment] 2016-08-15 21:13
Don't know if it makes a difference:
> Somehow the save game got messed up and the units are marked as already been in combat so can't move again.

The bug happened mid game, not after loading a game. I only made the save for the bugreport and this save accurately shows what happened in-game.

**Comment by DanVanAtta** [comment] 2016-08-15 22:07
Let's keep tracking this, it's quite a problem. ON every turn if we are unflipping the bits for the units to show as 'not in combat', there is a bug in there since that is not happening. The french units remain unable to move turn after turn.

**Comment by DanVanAtta** [comment] 2016-08-16 06:37
removing from 1.9 milestone - If we can fix before 1.9, great, otherwise, it is not a show-stopper and we'll should release  1.9 anyways even if this is not fixed yet.

**Comment by DanVanAtta** [comment] 2016-12-18 10:16
:white_flag:

**Closed by DanVanAtta** 2016-12-18 10:16 UTC
Labels: Bug Backlog
