### ISSUE TITLE
Mod Toolbox Lockup

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2110] opened 2017-07-18 18:41 UTC
I mentioned this to @RoiEXLab  and he felt i should post this issue.  
(I have not attempted to duplicate it yet)

  While performing a 10 minute mute to a player in the lobby, (foul language player abuse etc) the lobby locked up for me. (using newest unstable pre release from yesterday) I then task manager closed the lobby. It did not lock up for me when doing it with old stable. 0 error message.  My internet connection never changed.  I was able to google while lobby locked. I am just mentioning in case it matters.

**Comment by ssoloff** [comment] 2017-07-18 18:51
@prastle Just to be clear, can you confirm the environment is the following:

* Lobby server: 1.9.0.0.3635
* Your client: 1.9.0.0.5778

And when you say, "the lobby locked up," you specifically mean your lobby _client_, correct?  Did the actual lobby server lock up for all connected users, requiring it to be restarted?

The obvious candidate here is #1942.  We may have missed this particular use case (although I do remember testing one-minute mutes, but I think it was from a 3635 client to a new lobby rather than vice versa).

**Comment by RoiEXLab** [comment] 2017-07-18 18:57
@ssoloff I also assumed #1942 is the reason, that's why I told him to report it, because this seems like a rather weird issue.

When I'm thinking about it: Most of the issues are weird. Otherwhise we would probably have fixed it already ^^

**Comment by prastle** [comment] 2017-07-18 20:12
my client 5782

server was lobby

it didnt lock up 5 -10 sec later as .3627

no restart required only affected me as a mod using toolbox to mute a player

**Comment by ssoloff** [comment] 2017-07-18 23:43
Confirmed I can reproduce this using a `master` (666e396; tag 1.9.0.0.5785) client and 3635 lobby.  I'm debugging now.

**Comment by prastle** [comment] 2017-07-18 23:49
ty ss

**Comment by ssoloff** [comment] 2017-07-18 23:57
The client's UI thread is hung waiting for an RMI call to return.  Specifically, it is stuck in the handler for the Quick Mute action in `LobbyServer#createAdminActions()`:

```java
rVal.add(SwingAction.of("Quick Mute", e -> {
  final JLabel label = new JLabel("How many minutes should this player be muted?");
  final JSpinner spinner = new JSpinner(new SpinnerNumberModel(10, 0, 60 * 24 * 2, 1));
  final JPanel panel = new JPanel();
  panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS));
  panel.add(label);
  panel.add(spinner);
  if (JOptionPane.showConfirmDialog(LobbyFrame.this, panel, "Mute Player",
     JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
    final Object value = spinner.getValue();
    if (value == null) {
      return;
    }
    final long resultMuteLengthInMinutes = Long.parseLong(value.toString());
    if (resultMuteLengthInMinutes < 0) {
      return;
    }
    final Instant expire = Instant.now().plus(Duration.ofMinutes(resultMuteLengthInMinutes));
    controller.zzMuteUsername(clickedOn, expire); // <-- HUNG ON THIS LINE
    controller.zzMuteMac(clickedOn, expire);
  }
}));
```

The following exception is reported in the lobby:

```
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> Exception in thread "pool-1-thread-11" java.lang.ArrayIndexOutOfBoundsException: 24
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at games.strategy.engine.message.RemoteInterfaceHelper.getMethodInfo(RemoteInterfaceHelper.java:49)
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at games.strategy.engine.message.RemoteMethodCall.resolve(RemoteMethodCall.java:178)
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:161)
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$298(UnifiedMessenger.java:303)
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Tue Jul 18 19:41:57 EDT 2017 SEVERE [pool-1-thread-11] ERROR -> 	at java.lang.Thread.run(Thread.java:748)
```

That looks like the client requested a call to the method with ordinal 24, which doesn't exist in the old code.  My guess is the new client's RMI subsystem is hung waiting for a response from the lobby server, which will never arrive because the server's handler thread crashed.

Therefore, it looks like we're calling the new `zz` methods even though we're connected to an old lobby.  Whoops.

Other than reverting this change, is it possible to detect what lobby we're connected to and call the older method when we're connected to an old lobby?  I expect this would have to be done at every call site for the new `zz` methods.  @RoiEXLab?

**Comment by ssoloff** [comment] 2017-07-18 23:59
PS: I saw that @DanVanAtta just marked 1.9.0.0.5792 as the new latest release.  Is that release going to be deployed as the lobby server soon?  If so, then this compatibility issue may be short lived.

**Comment by RoiEXLab** [comment] 2017-07-19 00:11
@ssoloff Good question. The primary reason for this version to be marked as stable was to fix some of the links etc. in the client.
But updating shouldn't be a big problem so this could also work to fix the issue.

**Comment by RoiEXLab** [comment] 2017-07-19 00:12
Twge most important question is if updating the lobby is going to break anything on outdated clients. (If it's only breaking moderator controls we should be fine because we can tell them to update to fix their problems)

**Comment by RoiEXLab** [comment] 2017-07-19 00:18
@ssoloff unfortunately I believe that there's currently no way to determine the lobby version.
A workaround would be to push a change to the latest master which send a version string along with the challenge and if this string is not being sent the version must be old.

**Comment by ssoloff** [comment] 2017-07-19 03:35
@prastle #2114 should fix this issue.  When you have a chance, please test pre-release 1.9.0.0.5802 or later to verify that you are able to successfully use moderator commands against the production lobby.

**Comment by prastle** [comment] 2017-07-19 13:01
Yes new one works fine Thanks!

**Comment by prastle** [comment] 2017-07-19 22:15
Apparently that only fixed mute.  1 week ban earlier did not work from newest release but works from old stable.

**Comment by RoiEXLab** [comment] 2017-07-19 22:26
Closing in favor of #2117

**Closed by RoiEXLab** 2017-07-19 22:26 UTC
Labels: close pending confirmation
