### ISSUE TITLE
Cant load maps that are not downloaded and zipped

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#7904] opened 2020-10-14 20:55 UTC
The latest versions of TripleA (v2.3.22024 at least) do not seem to allow maps being loaded if they are not in zip files, but just in a dir. The maps just do not show in the list when loading map.

This is not very practical when working on and developing maps. Actually it is pretty hindering.

Could this be fixed?

**Comment by trevan** [comment] 2020-10-15 17:27
This is a duplicate of #7840.  That issue also has a regression range.

**Closed** 2020-10-15 20:49 UTC
Labels: Problem

**Comment by trevan** [comment] 2020-10-15 21:31
I've created #7910 to fix this.
