### ISSUE TITLE
Researching Long Range Aircraft *reduces* Bomber Range to 2 or 1!

### ISSUE THREAD

**Issue by GuiltyCol** [triplea-game/triplea#1719] opened 2017-05-16 22:17 UTC
Playing the Tutorial, I had 4 bombers in Holland Belgium which had successfully bombed the United Kingdom.  

I then successfully researched Long Range Aircraft, rolling a double 6 from 2 tries. See screenshots.

But when I came to try to bomb the United Kingdom again, my bombers couldn't reach.  In fact 2 of the bombers have a range of just 2 now, and the other 2 have a range of just 1! See screenshots.  

My 2 fighters do have the correct new range of 6. 

![16-05-2017 23-14-09](https://cloud.githubusercontent.com/assets/28742566/26130687/d2a454d8-3a8d-11e7-8392-6ed873bfd593.png)
![16-05-2017 23-12-18](https://cloud.githubusercontent.com/assets/28742566/26130691/d2a76b28-3a8d-11e7-8b50-d2323f80490a.png)
![16-05-2017 23-13-26](https://cloud.githubusercontent.com/assets/28742566/26130689/d2a658b4-3a8d-11e7-93fa-6fb541e0482a.png)
![16-05-2017 23-11-19](https://cloud.githubusercontent.com/assets/28742566/26130690/d2a6b598-3a8d-11e7-9a4a-9a5a04dfb723.png)
![16-05-2017 23-10-16](https://cloud.githubusercontent.com/assets/28742566/26130688/d2a55c5c-3a8d-11e7-96d2-9bfa728207fc.png)

**Comment by DanVanAtta** [comment] 2017-05-17 06:44
Thank you for reporting @GuiltyCol  

Triaging this: I suspect this is a new problem, so labeling as a regression. This also looks like a pretty bad bug, greatest concern is that this is a problem on other maps, not just Tutorial.

**Comment by GuiltyCol** [comment] 2017-05-17 11:32
Thanks Dan. Would it be useful if I posted up the saved game (there's no personal information saved in there is there?).

**Comment by ron-murhammer** [comment] 2017-05-24 00:38
@GuiltyCol I wasn't able to reproduce this. Can you upload a save game?

**Comment by GuiltyCol** [comment] 2017-05-24 05:15
Sure Ron. 
[Tutorial 3 - bug.zip](https://github.com/triplea-game/triplea/files/1024475/Tutorial.3.-.bug.zip)

**Comment by ron-murhammer** [comment] 2017-05-24 23:21
@GuiltyCol So this is a pretty strange bug and actually has nothing to do with researching Long Range Aircraft. Either a bug occurs or just your game gets corrupt during the German turn when you strategic bomb London. After that occurs, those bombers never get their movement reset at the end of non-combat move like they should (any new bombers you build work fine).

Here is a save right before the issue occurs (before combat move) where I can't seem to reproduce the problem even taking the exact same steps you did: 
[Before Bomber Movement Bug.zip](https://github.com/triplea-game/triplea/files/1027483/Before.Bomber.Movement.Bug.zip)

Here is a save right after the strategic bombing during non-combat move when the bombers are already bugged and doesn't matter if you research anything next turn they won't have their max movement:
[After Bomber Movement Bug.zip](https://github.com/triplea-game/triplea/files/1027485/After.Bomber.Movement.Bug.zip)

Unless we are able to reproduce the error again with the first save or a new game. I'm going to have to assume this was just a glitch and your game getting corrupted for some reason as I haven't seen this happen anywhere else.

**Comment by GuiltyCol** [comment] 2017-05-25 09:30
Ok Ron, thanks for investigating.  I'd strategically bombed London a couple of times and the movement didn't reset the after I researched Long Range Aircraft.  I assumed correlation implied causation, very naughty of me!

**Comment by ron-murhammer** [comment] 2017-05-25 13:04
@GuiltyCol I probably would have assumed the same thing given the timing.

**Comment by ron-murhammer** [comment] 2017-05-27 17:01
Closing this for now since we can't reproduce.

**Closed by ron-murhammer** 2017-05-27 17:01 UTC
Labels: category: game engine > game rules, close pending confirmation, type: bug
