### ISSUE TITLE
G.O.T. map territory issues

### ISSUE THREAD

**Issue by hispublic** [triplea-game/triplea#3160] opened 2018-02-25 22:21 UTC
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

At game start, turn 1 there are several errors in the map itself in these three connected territories.  The attached saved game highlights the three territories and errors 3 & 4.

Look at the Neutral border between Dothraki and FreeCities...northwest on map.

These territories are (name under the Territories tab / name printed on map):

Midlands Road/Qohor,
Lhazar/Midlands Road and Lhazar (both names printed on same territory),
Midlands Road (yes, two territories w/same name)/blank

 Error #1
At the start of the game, Qohor is Neutral and uncontested but occupied by FreeCities troops.  I'm thinking the author intended to place these troops in different territories west of Qohor. 

Error #2
The opening combat move for Dothraki AI is to attack Qohor (perhaps because it is occupied?).  When they occupy Qohor, the territory remains Neutral.

Error #3
When the FreeCities attack Qohor, all three territories (both Midlands Roads and Lhazar) light up as under attack...see attached saved game.
[GOT bug save.zip](https://github.com/triplea-game/triplea/files/1756770/GOT.bug.save.zip)

Error #4
When the attack in Error #3 is successful, the FreeCities troops occupy Midlands Road/blank rather than Midlands Road/Qohor as intended.

### Do you have the exact error text? Please copy/paste if so
there is no error message

**Comment by ron-murhammer** [comment] 2018-02-26 01:49
@hispublic Thanks for the bug report and a few other have reported similar issues with territory connections. The original map maker is no longer active and since this is in experimental category, the engine developers probably won't improve it. Are you interested in taking it over and trying to fix the issues?

**Comment by Cernelius** [comment] 2018-02-26 02:26
Just to give a few info, as I don't think anyone else here knows the history (and as long as I know it right, which is not assured), this map never had an owner, but was left incomplete there in the old forum and RolfLarsson, at the time almost the only person taking care of the repository at the previous place, did some minimal stuff to get this map to the repository.
It would be great if somebody fixes this map, especially considering that the AI improvements would make this a much interesting game (take 1 player each and give rest to Fast AI). I recall there were also some units that were absolutely obsolete, meaning absolutely worthless to buy, in place of others, and the two-hitpoint units are the same as the un-injured ones, which is confusing.
Maybe somebody can post here a link about where now is all the stuff that you need to read to learn about how to mapmake? I cannot find it now.

**Comment by Cernelius** [comment] 2018-02-26 19:50
Also, this is an example of what I was saying, in that this map is so bugged one would think it should not stay in the repository, yet if you take it out the possibilities of someone fixing or even noticing it get virtually zeroed; yet probably users should not be offered broken maps without warning.
If not a broken section, maybe a "bugged" tag beside the maps, and a switch show/hide bugged maps? Just an idea.

**Comment by DanVanAtta** [comment] 2018-02-26 21:40
"in-progress", "abandoned" could be reasonable categories as well.

To be clear, my latest position is that we should include maps early and often. Maps that cause system problems, like war of relics, are probably best not included (bots will download all maps, so we get problems). We need to fix war of relics anyways, I'm hoping something like: https://github.com/triplea-game/triplea/issues/3104 coudl help get us there.

**Comment by DanVanAtta** [comment] 2018-02-26 21:41
(so until we can fix the maps that cause system problems, those probably should be excluded, it is just the one to my knowledge)

**Comment by Cernelius** [comment] 2018-02-26 22:36
Bots have limits, mainly related to the RAM, and should not run maps with a very big xml, but it would be very wrong not to have such maps just because of bots. Bots should not dictate anything at all, as I see it.
Personally, I would for sure rather get totally rid of bots than big XML maps like war of the relics, if I had to choose.
The proble here are the bots, not the big XML maps; my suggestions:

- Having bots not loading and not having anything from the "Experimental" category; this would be a good thing anyways, as it makes sense that bots have only the staples, and will cut confusion (if something is requested in bots, then it should probably be upped of a category); then, you can assure maps that are not up to the requirements of bots to be in that category (tho this may be unfair to high quality maps that would be downgraded because of bots only).

or

- Having a line in the bots themselves to exclude a particular map from them; then you would just need to be sure to add the name you don't want the bots to have

or

something else.

**Comment by Cernelius** [comment] 2018-02-26 22:43
Of course, the best way would be that the bots are able to see themselves if a game is just to big for their settings, and not try to load it; but I'm sure you have already thought about this. If a way can be made, that would be surely great, as bots should not bite off more than they can chew, but surely neither dictate an upper limit for xml (that is why we had and have the RAM settings), also considering that you can set the bots RAM etc. limits as low as you wish.

**Comment by Cernelius** [comment] 2018-02-26 22:52
@DanVanAtta I'm not aware of any problems about war of the relics, and all was fine the last time I played it. If there are any issues I might take a look (not promising), but I need to know at least what? Did someone make a bug report?

**Comment by DanVanAtta** [comment] 2018-02-27 00:48
>  I would for sure rather get totally rid of bots than big XML maps like war of the relics

😁  while I really appreciate maps, bots are a lifeblood for us; most people cannot host.

My solution for war of relics is update XML spec so it would not need to be 70k lines long (or 40k, however long, it's just large because the specification is not efficient).

> Having bots not loading and not having anything from the "Experimental" category;

Pretty good suggestion. We have not put enough time into it right now though, so right now it only excludes War of Relics.

> also considering that you can set the bots RAM etc. limits as low as you wish.

Funny enough it's actually not RAM that is the limit here. In general bots are limited by RAM for how many games they can host, but for map parsing that is CPU. The issue is that we go into so many iterative loops for the XML that it takes about 30s to parse the one map. The file has something like 40~70k lines, I looked at it once and each line causes a loop with many iterations. I recorded some loops being executed 1.2M (million) times while parsing the map.

It's basically a technology limit, we did not code the XML to handle this efficiently.

> @DanVanAtta I'm not aware of any problems about war of the relics, and all was fine the last time I played it.

I don't have the ticket number handy, @prastle noted bots loading very slowly and a lot of it was the slow map parsing for war of relics.

War of relics is only a problem for parsing. If you select the map, unless you have a really beastly machine (even with a beastly machine ) you can probably expect 10-30 seconds to parse. So for example, select the map, start a game, then close out the game and relaunch TripleA. On launch we do a full parse, you'll perhaps notice the UI is frozen for the 10-30 seconds. We also get further slow downs when opening the map selection window.

**Comment by prastle** [comment] 2018-02-27 01:01
Ya the bots are down to about 2-3 min now on an update/reload.

**Comment by Cernelius** [comment] 2018-02-27 01:34
>>Having bots not loading and not having anything from the "Experimental" category;

>Pretty good suggestion. We have not put enough time into it right now though, so right now it only excludes War of Relics.

Ah, so you have already excluded WotR? Good then, that definitely should not stay in bots.
And, yes, if the problem is "only" the loading time, I confirm it. Also in the past the main bot hoster was taking care not to have WotR in a bot.
It makes no sense to get massive delays for a rarely played map; so only maps that bots can handle in less than 1 sec should stay in them (think about if all maps would be like WotR).
What I was pointing out is that would be bad to say that if bots cannot handle it, then this map is unacceptable for the repo.
And, yes, I think excluding the experimental from bots would be a very good move, as I believe it does little more but confusing new people using bots, and it would also be a way to assure more consistency (if people complains that a popular map is not available in bots, that probably means that such a map is at least "good").
If a mapmaker badly needs to test and can use only bots, I remember there was a development section for the maps being actively worked on, that could not be excluded.
But we are really being off topic.

**Comment by hispublic** [comment] 2018-02-27 03:58
@ron-murhammer I have no clue how to work on the games.  That doesn't mean I can't learn though.  Is it something that a non-coder can do?

**Comment by Cernelius** [comment] 2018-02-27 04:16
Yes, all is covered by stuff that explain how to mapmake both the skin and the game. I don't know where the stuff is now, so maybe they can tell.

**Comment by beelee1** [comment] 2018-02-27 14:39
@hispublic  if you want to just do xml changes dl pact of steel and open the games folder which has the pos 2 xml. It explains a lot. Idk how to change the map ( graphics ) . @FrostionAAA might be able to point you in the right direction.

@all Idk how bots work but if you could have 1 or 2 that could randomly offer experimental maps it would help them get some exposure and possibly become popular/improved. Otherwise most people will probably never know they exist.

Obviously overall bot performance should take precedence if not feasible.

**Comment by Cernelius** [comment] 2018-03-03 20:49
Ok, so it seems nobody is telling.

I guess I'll tell you to do this:

Download the old 1.8.0.9 from here:
http://triplea-game.org/old_downloads/

Then, once you have it installed (do it taking care not to override your current istallation), open:

triplea_1_8_0_9/doc

First read:
How to create custom games

then read:
map_and_map_skin_making_overview

then read the pos2 xml you can find here:
https://github.com/triplea-maps/the_pact_of_steel/blob/master/map/games/pact_of_steel_2.xml

And if you get stuck at any point, just ask here or in Forum.

They have removed all the mapmaking help stuff that used to be in the main download, and I assume that they have made it available somewhere else (right?), but I'm not finding it.
If nobody gives us the link, that is a way you can get it, as long as the old 1.8.0.9 is available.

**Comment by Cernelius** [comment] 2018-03-03 20:52
If anyone is going to fix this map and know stuff about the lore of the setting, my suggestion is to do whatever you feel right, not just limiting yourselves correcting the bugs. I'm fairly shure no admins will object any changes, or a full ownership takeover, and anyways you can always make your stuff into a mod, to have full freedom.
I believe tergarien is a bit overpowered, for having dragons, cheap units and good position.

**Comment by Cernelius** [comment] 2018-03-22 23:19
I found them. Forget what I said about downloading the 1.8.0.9. All the documentation you need is here:

https://github.com/triplea-game/triplea/tree/master/docs/map_making

Reading that and anything that is referred in it will make you fully able to mapmake (more than enough to just debug this game, and possibly, also, rework it a bit (rebalance the units and players, and making it closer to the lore)).
The main reference would be this:

https://github.com/triplea-maps/the_pact_of_steel/blob/master/map/games/pact_of_steel_2.xml

It would be nice if someone would fix this map/game.

My main suggestions:

1) Keep it as a FFA in which you take 1 player each and rest to AI, documenting it has to be played this way in Notes.

2) Do what you can to have the game as close as possible to the setting and the lore (I have been told a lot of territories are assigned to the wrong players).

3) Much reduce the total income in the map, or increase the units costs, or both (as being a FFA, the game tends to get way too stacky).

4) Tergarien is a bit overpowered and Tully is a bit underpowered, but I believe all the rest is quite well balance; so my suggestion is not to sway too much from the current balance (or you risk to worsen it), while doing something to tone down or up the two players I mentioned.

**Closed** 2018-09-11 02:06 UTC
Labels: category: map bug, ice box - close and revisit later
