### ISSUE TITLE
Engine Shouldn't Allow Blitzing Through Enemy Territory With Units to Friendly Territory

### ISSUE THREAD

**Issue by drockken** [triplea-game/triplea#4486] opened 2019-01-03 04:50 UTC
### Engine version
1.10.13419

### Map name
World War II Global 1940 2nd Edition

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Load the saved game.  UK shall attempt to Blitz from Karelia to Baltic States through Novgorod.  The game does not allow it.

### Do you have the exact error text? Please copy/paste if so
There is no error message.

### Instead of this error, what should have happened?
Should be allowed to blitz through Novgorod into Baltic States
[no_blitz.zip](https://github.com/triplea-game/triplea/files/2722768/no_blitz.zip)

## Actual Bug After Discussion
Moving a tank into an unoccupied enemy territory then into a friendly territory is considered a blitz move so its not legal to move into a friendly territory if the enemy territory has infrastructure. So that would be a bug as the engine should prevent that second move.

v1 - infra units (factories, etc) don't stop blitz
v2+ - infra units do stop blitz

**Comment by panther2** [comment] 2019-01-03 15:07
@beelee1 is correct.

Page 15, Europe 1940 rulebook:

> A tank (or mechanized infantry) that encounters enemy units, including AAA (antiaircraft artillery) units,
or an industrial complex, air base, or naval base, in the first territory it enters must stop there and may not blitz.

**Comment by ron-murhammer** [comment] 2019-01-03 15:16
Closing this. Please re-open if you have further questions.

**Comment by drockken** [comment] 2019-01-03 15:21
The game permits you to move on into friendly territory.  Is that not considered blitzing?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ron-murhammer** [comment] 2019-01-03 15:47
@drockken Ah I see what you mean now. Moving a tank into an unoccupied enemy territory then into a friendly territory is considered a blitz move so its not legal to move into a friendly territory if the enemy territory has infrastructure. So that would be a bug as the engine should prevent that second move.

**Comment by drockken** [comment] 2019-01-03 16:07
Ok.  That wasn't my original posted issue (I was ignorant on those rules), but something I noticed anyway.  I can post this as a new issue if necessary.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Cernelius** [comment] 2019-01-03 16:13
>Closing this. Please re-open if you have further questions.

I believe not-members can reopen only their issues they themselves closed (or I'm missing something?).

And, yes, blitzing is anything comprising moving into an enemy owned territory not occupied by units that don't allow blitzing. So, extrapolating the rules, if you have a 3 movement unit, blitzing would be also moving first into a friendly territory, then into an empty enemy owned one, then into another friendly territory.

As default (classic), infrastructures don't block blitzing, while from v2 onwards any hostile units block blitzing.

In my opinion, it is nonsense that something like an undefended factory blocks blitzing, so I think here the ruleset got worse since Classic.

**Comment by Cernelius** [comment] 2019-01-03 17:32
Just to be clear "Engine Shouldn't Allow Blitzing Through Enemy Territory With Units to Friendly Territory" is true for any ruleset from v2 onwards, but not for v1, that I believe currently works correctly.

**Comment by panther2** [comment] 2019-01-03 19:58
@drockken , @redrum

> Moving a tank into an unoccupied enemy territory then into a friendly territory is considered a blitz move so its not legal to move into a friendly territory if the enemy territory has infrastructure. So that would be a bug as the engine should prevent that second move.

I can't reproduce a bug here.
Take the savegame and try to move the British Tanks from Karelia via Novgorod to Belarus or Archangel.
The engine correctly prevents the tanks from continuing their move when in Novgorod.

**Comment by ron-murhammer** [comment] 2019-01-03 20:05
@panther2 I just did a quick test as well and everything seems to work fine. Closing this (again) unless someone can provide a reproducer.

**Closed by ron-murhammer** 2019-01-03 20:05 UTC
Labels: category: bug
