### ISSUE TITLE
Lock not held exception with latest master vs bots when production window is rendered

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3135] opened 2018-02-24 22:56 UTC
With latest master:
```
commit 34cbf16900958afe9fdd5deb674a42b42572c699
Date:   Sat Feb 24 17:11:07 2018 -0500
```

### Problem

Can get the following stack trace:
```
java.lang.Exception: Lock not held
	at games.strategy.engine.data.GameData.ensureLockHeld(GameData.java:160)
	at games.strategy.engine.data.GameData.getResourceList(GameData.java:183)
	at games.strategy.triplea.ui.ProductionPanel.setLeft(ProductionPanel.java:179)
	at games.strategy.triplea.ui.ProductionPanel.calculateLimits(ProductionPanel.java:205)
	at games.strategy.triplea.ui.ProductionPanel.show(ProductionPanel.java:99)
	at games.strategy.triplea.ui.TabbedProductionPanel.getProduction(TabbedProductionPanel.java:41)
	at games.strategy.triplea.ui.PurchasePanel$1.actionPerformed(PurchasePanel.java:119)
	at games.strategy.triplea.ui.PurchasePanel.lambda$waitForPurchase$2(PurchasePanel.java:106)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
```

### Impact to user:
- game seems to continue fine without problem. Hard to say if there is any long term damage from this

### Repro
- Launch the game
- join lobby
- join a bot
- pick big world 1943 v3
- pick all nations so the game launches
- proceed to russia purchase screen
- when purchase screen is rendered, notice in the console the above stack trace

**Comment by DanVanAtta** [comment] 2018-02-27 03:36
@ron-murhammer FYI on this one, I think it might be due to the new resource icons. Let's please assign when there is active work being done.

**Comment by General-Dru-Zod** [comment] 2018-03-03 04:26
I'm getting "lock not held" errors too, very reproducible too. Using 9464 in a bot game. I'm attaching the save game. But it happens every time that I try to move one of the British acc that are carrying American fighters. I need to go into edit mode to get the moves done, because the errors keep popping up. I even tried to replace the acc with fresh one via edit mode.

Map is "ww2 1941 v3"

[ww2.v3.toc.match.1_me.allies_v_rav.axis__r2.uk_1.end.3_lock.not held.error_01.2018.zip](https://github.com/triplea-game/triplea/files/1777096/ww2.v3.toc.match.1_me.allies_v_rav.axis__r2.uk_1.end.3_lock.not.held.error_01.2018.zip)

**Comment by ron-murhammer** [comment] 2018-03-03 04:30
@General-Dru-Zod Can you post the entire error message? I'm not able to reproduce with that save game.

**Comment by prastle** [comment] 2018-03-03 04:59
What gz has left out that might matter is his opponent is 3635? also the observers were using 9480

**Comment by ron-murhammer** [comment] 2018-03-03 05:08
```
java.lang.Exception: Lock not held
	at games.strategy.engine.data.GameData.ensureLockHeld(GameData.java:160)
	at games.strategy.engine.data.GameData.getRelationshipTracker(GameData.java:463)
	at games.strategy.triplea.delegate.Matches.lambda$alliedUnit$151(Matches.java:1334)
```

**Comment by ssoloff** [comment] 2018-03-03 05:16
Unrelated to the root cause, but it seems strange that we would require the read-lock to be held while getting a reference to a `final` field.  I can see requiring the lock to be held while _using_ the `RelationshipTracker` but not to simply get the reference.

**Comment by ron-murhammer** [comment] 2018-03-03 05:18
@ssoloff I think a lot of the code the has ensureLockHeld() calls are probably questionable. But just submitted a PR to at least fix this.

**Comment by ron-murhammer** [comment] 2018-03-03 05:24
@General-Dru-Zod @prastle This should be fixed in the latest pre-release now. There was a potential error introduced with the changes around the route message enhancements. Thanks for the bug report!

**Comment by General-Dru-Zod** [comment] 2018-03-03 05:50
@prastle, He started with 3635 and then we reloaded with his newer version.

**Comment by ron-murhammer** [comment] 2018-03-03 05:53
@General-Dru-Zod @prastle It ended up not having anything to do with older versions. Just a bug that was added with the route message changes and great to catch before we make this a stable. You should be able to load that save now without any errors in the latest pre-release.

**Comment by General-Dru-Zod** [comment] 2018-03-03 08:32
I left a zip with the errors, But here ya go. I was getting it over and over as I tried to move British acc's that carry usa fighters.

java.lang.Exception: Lock not held
	at games.strategy.engine.data.GameData.ensureLockHeld(GameData.java:160)
	at games.strategy.engine.data.GameData.getRelationshipTracker(GameData.java:463)
	at games.strategy.triplea.delegate.Matches.lambda$alliedUnit$151(Matches.java:1334)
	at java.util.function.Predicate.lambda$and$10(Unknown Source)
	at java.util.function.Predicate.lambda$and$10(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at games.strategy.util.CollectionUtils.getMatches(CollectionUtils.java:46)
	at games.strategy.triplea.delegate.MoveValidator.carrierMustMoveWith(MoveValidator.java:1364)
	at games.strategy.triplea.delegate.Matches.lambda$unitIsBeingTransportedByOrIsDependentOfSomeUnitInThisList$172(Matches.java:1472)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at games.strategy.util.CollectionUtils.getMatches(CollectionUtils.java:46)
	at games.strategy.engine.data.Route.getMovementFuelCostCharge(Route.java:414)
	at games.strategy.triplea.ui.MapPanel.setMouseShadowUnits(MapPanel.java:757)
	at games.strategy.triplea.ui.MovePanel.updateRouteAndMouseShadowUnits(MovePanel.java:545)
	at games.strategy.triplea.ui.MovePanel$3.mouseMoved(MovePanel.java:1272)
	at games.strategy.triplea.ui.MapPanel.notifyMouseMoved(MapPanel.java:325)
	at games.strategy.triplea.ui.MapPanel.access$1900(MapPanel.java:72)
	at games.strategy.triplea.ui.MapPanel$2.mouseMoved(MapPanel.java:202)
	at java.awt.AWTEventMulticaster.mouseMoved(Unknown Source)
	at java.awt.Component.processMouseMotionEvent(Unknown Source)
	at javax.swing.JComponent.processMouseMotionEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by General-Dru-Zod** [comment] 2018-03-03 08:33
I will try the newest release.

**Comment by General-Dru-Zod** [comment] 2018-03-13 03:10
I got another lock not held error with 9713. Playing ww2 v3.
 
[lock_not_held_error_03.12.2018.zip](https://github.com/triplea-game/triplea/files/1805323/lock_not_held_error_03.12.2018.zip)

**Comment by ron-murhammer** [comment] 2018-03-13 03:43
@General-Dru-Zod Thanks for the report. Its a very similar error with a different cause.

This is a pretty interesting one. It appears this was attempted to be fixed a few years back in this commit: https://github.com/triplea-game/triplea/commit/20d5505fec23686c916d443224f72886a03dfc83

But I don't think its enough to just set the predicate inside of the data read lock block, the actual predicate test must be in the data read lock block as well.

Seems that the most straightforward fix is to wrap the entire block in the data read lock block. It definitely does start to make you wonder if we should really be handling data read locks more consistently throughout the code.

Here is the stacktrace:
```
java.lang.Exception: Lock not held
	at games.strategy.engine.data.GameData.ensureLockHeld(GameData.java:160)
	at games.strategy.engine.data.GameData.getSequence(GameData.java:251)
	at games.strategy.triplea.delegate.Matches.lambda$unitHasEnoughMovementForRoute$126(Matches.java:1104)
	at games.strategy.triplea.delegate.MoveValidator.validateBasic(MoveValidator.java:595)
	at games.strategy.triplea.delegate.MoveValidator.validateMove(MoveValidator.java:86)
	at games.strategy.triplea.delegate.AbstractMoveDelegate.validateMove(AbstractMoveDelegate.java:137)
	at games.strategy.triplea.ui.MovePanel.updateUnitsThatCanMoveOnRoute(MovePanel.java:463)
	at games.strategy.triplea.ui.MovePanel.access$1200(MovePanel.java:52)
	at games.strategy.triplea.ui.MovePanel$3.mouseMoved(MovePanel.java:1250)
	at games.strategy.triplea.ui.MapPanel.notifyMouseMoved(MapPanel.java:325)
	at games.strategy.triplea.ui.MapPanel.access$1900(MapPanel.java:72)
	at games.strategy.triplea.ui.MapPanel$2.mouseMoved(MapPanel.java:202)
	at java.awt.AWTEventMulticaster.mouseMoved(Unknown Source)
```

**Comment by General-Dru-Zod** [comment] 2018-03-13 15:03
I have an older lock not held error saved from a 12/2017 game. Was during experimentation of some new concepts so I never posted it. But maybe it will be helpful. Was running 7753 on tis one.

[Lock not held_12.15.2017.zip](https://github.com/triplea-game/triplea/files/1807442/Lock.not.held_12.15.2017.zip)

**Comment by ron-murhammer** [comment] 2018-03-13 23:25
@General-Dru-Zod That appears to have the same root cause as the second one. So both should be fixed now in the latest pre-release. If you see any more instances, please report them. Thanks!

**Closed by ron-murhammer** 2018-03-13 23:25 UTC
Labels: category: bug, close pending confirmation
