### ISSUE TITLE
2.6 Release Bug - Download Maps Button failure

### ISSUE THREAD

**Issue by jsarles-code** [triplea-game/triplea#9788] opened 2021-11-16 13:52 UTC
### Reproduction Steps

1.click the download maps button it doesn't appear to be working, this is after i selected the pre-release settings as explained in the post about helping out with 2.6 testing. 
2.
3.

### Attach a Save Game

No save game this is before a game is live

### Engine Version

2.6 
Engine Version:2.6

### Is there anything else we should know?
Error report below , I clicked the report to Triple A button but it looked like the button did not fire? 

Status 500 reading ErrorReportFeignClient#canUploadErrorReport(Map,CanUploadRequest) Reason: Internal Server Error {"code":500,"message":"There was an error processing your request. It has been logged (ID 670302f9b41c23f2)."}  org.triplea.http.client.HttpInteractionException: Status 500 reading ErrorReportFeignClient#canUploadErrorReport(Map,CanUploadRequest) Reason: Internal Server Error {"code":500,"message":"There was an error processing your request. It has been logged (ID 670302f9b41c23f2)."}

**Comment by frigoref** [comment] 2022-03-31 19:46
@jsarles-code 
Can you please check my steps and retest them yourself?

**Steps-to-reproduce**
1. Start application
2. Click button _Engine Preferences_ (open popup _Settings_)
3. Switch setting in tab _Testing_ entry _Lobby URI Override_ to _Pre-Release_
4. Close popup _Settings_
5. Click button _Download Maps_
Expected result: Popup _Download Maps_ opens
**My result: Popup opens as expected**
![ Popup_DownloadMaps](https://user-images.githubusercontent.com/10353640/161136128-3679cfa7-d10b-4300-b94f-0fdc57b0988b.png)

**Comment by asvitkine** [comment] 2023-09-13 14:25
I'm closing this out since it works fine now if you don't have a Lobby URI Override set (i.e. set to "Latest Stable").

**Closed by asvitkine** 2023-09-13 14:25 UTC
Labels: Problem, 2.6
