### ISSUE TITLE
Side Scroll Freeze with Hot Key Use

### ISSUE THREAD

**Issue by beelee1** [triplea-game/triplea#4458] opened 2018-12-27 20:09 UTC
### My Operating System
windows7
### Map name
Global 40 House Rules with Canada
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
use the hot key Ctrl h and then Ctrl g you can't horizontally scroll until you click on something.
### Any additional information that may help
It doesn't do it when clicking on the Game drop down menu. If it freezes and you then use the drop down menu it works.

Noticed this a while ago and thought some other "hot keys" did it as well, but I can't replicate any others.

[``]([url](url))

Lol I can't figure out how to post a save on windows. I compressed and copied but... well w/e I'll figure that out later : )  You don't need a save, just fire up a game, do one thing, then check history.

I'm gonna do the @ron-murhammer since you did the hot key expansion a while back : )

Thanks

**Comment by ssoloff** [comment] 2018-12-28 05:33
Confirmed in 1.10.13344.

It looks like the problem is that when opening the History view, it receives the focus, so that all hot keys go to that window.  However, when closing the History view, the focus is not returned to the map window.  Hot keys end up being ignored until focus is restored to the map window (this can be as simple as left-clicking the map).

The following change seems to fix the problem, but I haven't researched too deeply to determine if this is indeed the idiomatic fix:

```diff
diff --git a/game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java b/game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
index 6b399db15..818466122 100644
--- a/game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
+++ b/game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
@@ -1997,6 +1997,7 @@ public final class TripleAFrame extends JFrame {
       getContentPane().removeAll();
       getContentPane().add(gameMainPanel, BorderLayout.CENTER);
       validate();
+      requestWindowFocus();
     });
     mapPanel.setRoute(null);
   }
```

**Closed** 2018-12-29 22:05 UTC
Labels: category: UI problem
