### ISSUE TITLE
New Battle calc: Retreat after round: 1

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#4708] opened 2019-02-24 08:46 UTC
Battle calc fixes and improvements #4576

1.10.14134

Windows 7

WAW

Make a calculation, select retreat after round: 1

No Error, Average attackers units left is calculated for multiple battle rounds (go for the win)
Had this occur at least twice during game. Can reproduce, but not for every battle....

![battle calc](https://user-images.githubusercontent.com/13902879/53297064-610b1e80-3818-11e9-8e74-c8c6c265d529.png)

Also easily calculated battles do not produce exact numbers.....?

![battle calc2](https://user-images.githubusercontent.com/13902879/53297086-a16a9c80-3818-11e9-8b8a-2a9241bfb7c6.png)

**Comment by ron-murhammer** [comment] 2019-02-24 20:21
@ZjelcoP Looks like there might be an issue around thinking air units are dead when retreating after round.  Is the second screenshot with dice or LL? For dice it is always going to be an approximation so that looks about right.

**Comment by ZjelcoP** [comment] 2019-02-24 21:30
It's LL.

**Comment by ron-murhammer** [comment] 2019-02-24 21:39
@ZjelcoP I tried reproducing the second battle with the latest pre-release and get the correct result:
![image](https://user-images.githubusercontent.com/1427689/53305705-5bc6c780-384a-11e9-8edb-cdecb216e1ce.png)

I think you must have had dice instead of LL on.

The first one does seem to be an issue and I was able to reproduce it.

**Comment by ZjelcoP** [comment] 2019-02-24 21:50
Ah yes, probably had dice on by mistake when testing the issue in revised map :-)

**Comment by ron-murhammer** [comment] 2019-02-25 02:19
@ZjelcoP Should be fixed in the pre-release once this PR is merged: https://github.com/triplea-game/triplea/pull/4711

**Closed** 2019-02-28 03:44 UTC
Labels: Impact: Regression
