### ISSUE TITLE
Lobby login fails

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#2347] opened 2017-09-09 07:31 UTC
### My Operating System:
Win 7.64
### TripleA version:
1.9.0.0.6538

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Login with my **new account** fails:

![lobby](https://user-images.githubusercontent.com/20812775/30238135-5c0d720a-9541-11e7-92e4-716d26770f67.PNG)

Though my user name exists:

![lobby2](https://user-images.githubusercontent.com/20812775/30238222-2e5450de-9543-11e7-9053-952e61510749.PNG)

Please indicate how I can provide more information, as there is no error log and no console message.

**Comment by RoiEXLab** [comment] 2017-09-09 09:41
We are aware of this problem... 
We ran into some issues with the DerbyDB, while Migrating the lobby software.
We decided to drop Derby completely, and @DanVanAtta removed the supporting code in  #2343
It seems the removal did not work out as expected, and therefore the versions after the merge of #2101 are unable to log in

**Comment by panther2** [comment] 2017-09-09 09:49
Thanks for the insight. 

(Just in case it helps: I created the new account and successfully logged in using version 1.9.0.0.6507)

**Comment by RoiEXLab** [comment] 2017-09-09 09:50
@panther2 Yeah, but now you probably won't be able to login using the stable version of TripleA

**Comment by panther2** [comment] 2017-09-09 12:52
Ah ok, but I am always going with the latest pre-releases.
The stable had a very short existence on my hard-drive :wink:

**Comment by prastle** [comment] 2017-09-09 13:32
@RoiEXLab I just dl .6538 and yes i can confirm above still occurs.  Same error with newest but the stable login is fine.

**Comment by ssoloff** [comment] 2017-09-09 15:44
I can reproduce a similar problem (can't login but get a different error message) locally running a 6538 lobby and client.

What version of the lobby is currently installed in production?

**Comment by RoiEXLab** [comment] 2017-09-09 15:46
I believe the first pre-release that has @DanVanAtta's Derby changes. 
Should be the same in terms of lobby code as the latest pre-release

**Comment by ssoloff** [comment] 2017-09-09 15:48
Negative on that last statement.  I forgot I just reset my lobby database last night, so the account I was using didn't exist. 😞 

So, using 6538 for both lobby and client works fine for me locally.  I will try using a 6520 lobby.

**Comment by ssoloff** [comment] 2017-09-09 15:58
Using a 6520 lobby and a 6538 client, everything works fine for me when run locally.

**Comment by RoiEXLab** [comment] 2017-09-09 16:02
@ssoloff I believe the issue is only noticeable if you created your account using the latest stable and then try to login with the latest pre-release and vice versa. While the former is not desired, the latter could definitely be "normal behaviour" as when users used the latest pre-release their accounts have been updated.

**Comment by prastle** [comment] 2017-09-09 16:05
Above is correct @RoiEXLab

**Comment by ssoloff** [comment] 2017-09-09 16:12
@RoiEXLab

Latest local test...

1. Start 6520 lobby.
1. Create a new account using 3635 client.  Login was successful.  Logout.
1. Login using 6538 client with account created in (2).  Login was successful.  Logout.

Another test against the production lobby:

1. Create a new account using 6538 client.  Error dialog displayed with title "Account creation failed" and message "java.io.IOException: Socket closed".

**Comment by RoiEXLab** [comment] 2017-09-09 16:21
@ssoloff Weird, the socket exception however means that a server side exception is occurring, I'll see if there some logs

**Comment by panther2** [comment] 2017-09-09 16:34
My experience was.

1. Create new account with 1.9.0.0.6507 last night (German time) (after hint that new account creation was fine at that time)
2. Login/logout without problems
3. Sleep
4. This morning (German time): Uninstall of 6507, install of 6538
5. The above mentioned problems occurred

**Comment by RoiEXLab** [comment] 2017-09-09 16:48
Server log wasn't as useful as I hoped.
It seems errors are coming from the lobbyloginvalidator

**Comment by ssoloff** [comment] 2017-09-09 17:08
Well, this might help a little...  If I comment out the code at `LobbyLogin.java:105` that sets the RSA password in the challenge response:

```java
final String hashedPassword = MD5Crypt.crypt(panel.getPassword(), salt);
props.put(LobbyLoginValidator.HASHED_PASSWORD_KEY, hashedPassword);
if (isUpdatedLobby) {
  //props.putAll(RsaAuthenticator.getEncryptedPassword(challengProperties, panel.getPassword()));
}
```

I can successfully login to the production lobby from a 6538 client.

Obviously, the lobby is choking when trying to validate the RSA password.

**Comment by panther2** [comment] 2017-09-09 17:24
FYI:
I have just downloaded and installed the stable (3635) version.
I managed to login successfully using the new account data.

6538 now returns this:
![lobby3](https://user-images.githubusercontent.com/20812775/30242323-7d868554-9594-11e7-8770-d29789fef259.PNG)

**Comment by ssoloff** [comment] 2017-09-09 17:27
Another issue to investigate is, if I created an account using a 6538 client, why is an MD5Crypt password being stored in the database instead of a bcrypt password?  That seems to be the case since my modified client is only sending an MD5Crypt password in the response.  (Someone with DB access can verify that claim by looking at the password for user `test1000` and seeing if it starts with `$2a$` or `$1$`.)

It almost seems as if in the following code used to create a new user account (`LobbyLoginValidator.java:243-255`):

```java
    if (RsaAuthenticator.canProcessResponse(propertiesReadFromClient)) {
      return RsaAuthenticator.decryptPasswordForAction(privateKey.get(), propertiesReadFromClient, pass -> {
        final UserDao userDao = new UserController();
        final HashedPassword newPass = new HashedPassword(BCrypt.hashpw(pass, BCrypt.gensalt()));
        if (password.isValidSyntax()) {
          userDao.createUser(user, password);
          userDao.updateUser(user, newPass);
        } else {
          userDao.createUser(user, newPass);
        }
        return null;
      });
    }
```

that the `userDao.updateUser(user, newPass)` call is throwing an exception before it gets a chance to update the database with the bcrypt password.  That would explain the socket closed exception I see when creating an account and why I can't login via RSA authentication.

**Comment by ssoloff** [comment] 2017-09-09 17:54
I confirmed that I can reproduce the exact behavior I observe in production (both creating a new account and trying to login to an existing account) on my local machine if I force an exception to be thrown from `UserController#updateUser()` before the transaction can be committed.

The reason the client is getting a socket closed error rather than seeing the cause of the authentication failure appears to be because we don't catch any exceptions in the lambda passed to `RsaAuthenticator#decryptPasswordForAction()`.  So the exception simply percolates up to the exception handler in `ServerQuarrantineConversation#message()`, which terminates the connection.

@RoiEXLab, when you looked at the lobby logs, did you see an "Error with connection" message anywhere?  When you said, "It seems errors are coming from the lobbyloginvalidator," did you come to that conclusion because there was there a stack trace?  If so, can you please post it?

**Comment by ssoloff** [comment] 2017-09-09 18:17
Ok, I think I have a real good candidate for what the problem may be.  I suspect the Postgres database in production was not re-created after [this change](https://github.com/triplea-game/triplea/commit/44f358f7fcf3d31321cfddc4289509395ea14074#diff-bfa3a4fe6065631b4ed6576b1ed67bd0) to the `ta_users` table schema.

I rebuilt my lobby database Docker container with the old schema and can confirm that that produces the same behavior I'm seeing in production.  In this case, the `UserController#updateUser()` method throws an exception because the SQL `UPDATE` command fails to write a bcrypted password to the `ta_users` table because the column size is too small to hold a bcrypt password.

Someone with access to the production database can confirm this by running `\d ta_users` from psql and looking at the type of the `password` column.  If it's `character varying(40)` instead of `character varying(60)`, then the schema will have to be updated manually to avoid having to recreate the database.

**Comment by prastle** [comment] 2017-09-09 18:43
Some new info.  If it matters.  I can login with pre release using my old name of himmler.  Testing now but I am assuming i cant use stable with that name

**Comment by RoiEXLab** [comment] 2017-09-09 20:22
@ssoloff Thanks for the analysis of this issue, @DanVanAtta should be able to alter the DB schema, when doing so I'd suggest to add another column for bcrypted passwords in order to be backwards compatible.
This would of course require another patch

**Comment by RoiEXLab** [comment] 2017-09-10 09:21
@DanVanAtta I probably have sufficient rights to access the postgresdb, but I don't know how to exactly access it, assuming it's using a password.
Assigning you to alter the DB schema to have an additional column/allow for bcrypted passwords.
I'd suggest using char(60) instead of varchar as the hash should not change in length at all.
If I have the time tomorrow, I'll submit a PR which effectively uses the new column.
I explicitly ask you to not just apply @ssoloff's changes, because this would require someone to move all bcrypted passwords to the new column just before updating the server software.

**Comment by RoiEXLab** [comment] 2017-09-10 21:48
Thanks to @prastle I was able to alter the DB schema myself... I'll try to submit a fix tomorrow

**Comment by prastle** [comment] 2017-09-10 23:47
no ty for helping me as well
@RoiEXLab

**Comment by prastle** [comment] 2017-09-10 23:48
WE WILL GET THERE @ ALL

**Comment by DanVanAtta** [comment] 2017-09-11 03:35
@RoiEXLab please do not modify production by hand. All changes to production should be done through scripts that are checked in. Note that the new column is not going to get created during integration tests: https://github.com/triplea-game/triplea/blob/master/config/lobby/db/001_create_tables

We've had examples of blatantly broken install scripts, which is at least far better than the examples of completely missing scripts (and maybe some documentation, but in some cases that is missing). The way we avoid this is by making sure anything in production has gotten that way by running a script that has been checked in. If you couple this with making sure test and prod environments are the same, then your production deployments can actually be simulated and error rates go down.

**Comment by DanVanAtta** [comment] 2017-09-11 03:36
> @DanVanAtta I probably have sufficient rights to access the postgresdb, but I don't know how to exactly access it, assuming it's using a password.

Please install one locally! Do not run anything in production unless it has been reviewed.

**Comment by DanVanAtta** [comment] 2017-09-11 03:38
> Assigning you to alter the DB schema to have an additional column/allow for bcrypted passwords.

This is actually totally not necessary, create a file '002'  similar to: https://github.com/triplea-game/triplea/blob/master/config/lobby/db/001_create_tables, it will get picked up automatically during travis build and we can run the same in production to update the schema.

Schema updates are not run by me from a postgres command line. THe fact I"ve been doing that for moderator updates is really bad, but I'm balancing that with the pressing need to have moderators turn on and live in the lobby.

**Comment by DanVanAtta** [comment] 2017-09-11 03:38
> I explicitly ask you to not just apply @ssoloff's changes, because this would require someone to move all bcrypted passwords to the new column just before updating the server software.

Let's just check both columns? Then it does not matter if client is old or new.

**Comment by DanVanAtta** [comment] 2017-09-11 03:44
@ssoloff 

```
ta_users-# \d ta_users;


                  Table "public.ta_users"
     Column      |            Type             | Modifiers 
-----------------+-----------------------------+-----------
 username        | character varying(40)       | not null
 password        | character(34)               | 
 email           | character varying(40)       | not null
 joined          | timestamp without time zone | not null
 lastlogin       | timestamp without time zone | not null
 admin           | integer                     | not null
 bcrypt_password | character(60)        
```

I did not blow away the postgres DB.. We do need to tighten up the brand new process of deploying a schema. The schema does not match what is checked in: https://github.com/triplea-game/triplea/tree/master/config/lobby/db

I ran:
```
alter table ta_users alter column password type varchar(60);
```

We now have:
```
     Column      |            Type             | Modifiers 
-----------------+-----------------------------+-----------
 username        | character varying(40)       | not null
 password        | character varying(60)       | 
 email           | character varying(40)       | not null
 joined          | timestamp without time zone | not null
 lastlogin       | timestamp without time zone | not null
 admin           | integer                     | not null
 bcrypt_password | character(60)               | 
```

`bcrypt_password` needs to have some constraints, it's not used. I dropped that as well:

```
ta_users=# alter table ta_users drop column bcrypt_password;
```

We should now be more or less matching the checked in schema. I'm noting on my backlog something to help enforce this better.

**Comment by ssoloff** [comment] 2017-09-11 03:59
@DanVanAtta Confirmed that I can now create new accounts and login with existing accounts using the latest client from `master`. :+1:

Also, login times appear to be the same as what they were prior to the upgrade.  I am seeing about 10-15 seconds.

**Comment by RoiEXLab** [comment] 2017-09-11 06:14
Okay @DanVanAtta I will remember sticking to the scheme scripts, would anyone mind if I copy the bcrypted rows over to the "new" column just before upgrading the server software using `UPDATE ta_users SET bcrypt_password=password, password=NULL WHERE password LIKE '$2a$%'`?

**Comment by RoiEXLab** [comment] 2017-09-11 06:37
@DanVanAtta I actually added some constraints to bcrypt_password... 
I added a check constraint which ensured either password is bcrypt_password is not null (you need to set the password column back to not null to get the initial behaviour.

**Comment by panther2** [comment] 2017-09-11 08:58
I have been able to log in with my new account and 6555 this morning.

So can this issue be closed - or is it still needed for any purpose?

**Comment by RoiEXLab** [comment] 2017-09-11 09:42
In theory this issue can be closed, I'd like to implement a feature, which allows for some sort of backwards compatibility.
I will probably submit a PR today, which should then finally close this issue.

**Closed** 2017-09-11 18:10 UTC
Labels: regression, type: bug

**Comment by DanVanAtta** [comment] 2017-09-11 18:11
@RoiEXLab if you are confident something is fixed, in this case you checked, you can close a report like this and ask it be re-opened if you missed something. I suggest that to reduce the overhead, so we can deal with things once by one person where possible.
