### ISSUE TITLE
Remove Codacy?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2498] opened 2017-10-14 06:03 UTC
At question: remove codacy branch builds? Codacy is reading zero issues, did we zero that out thanks to the checkstyle? If so, then codacy is seeming a bit redundant.

![wow](https://user-images.githubusercontent.com/12397753/31573101-aa409e0a-b069-11e7-8cdb-2f64bf0b9771.png)

**Comment by ssoloff** [comment] 2017-10-15 03:50
Checkstyle is still reporting ~2,500 issues.  The last time I remember looking at Codacy, it reported all the existing Checkstyle issues.  Maybe something in the configuration changed recently?  Because the results make it appear as if Checkstyle analysis has been shut off.

I need to create a Codacy project for my fork so I can play around with what's available.  There seems to be other metrics we could add to the dashboard that would be useful to monitor over time.  I'll try to do that over the next few days.

**Comment by DanVanAtta** [comment] 2017-10-15 21:00
@ssoloff we would want to be able to run those same metrics locally as well. It would be a bad situation if we had to wait for codacy to re-run to check any branch build. For me that seems like even if we can get value out of it, we need to also spend effort to be able to run the analysis locally. Now, if we can do both of those things, and be sure that if a local build would match all checks run against branches for PR builds, then I think we would be doing well.

**Comment by ssoloff** [comment] 2017-10-15 21:56
@DanVanAtta Agreed that we should be able to reproduce all metrics locally, and we would definitely do that (e.g. we would enable PMD in the Gradle build before turning it on in Codacy).  But the value I see for Codacy is having a _history_ of those metrics so we can see where we are improving and where we are not.

**Comment by DanVanAtta** [comment] 2017-10-18 02:25
Interesting point, I can see value in having a history. I think that answers the question of whether we should keep it. The cost of having it is low at the moment. Enabling PMD local and in codacy seems like a decent idea.

Stepping back, I think we do need to focus on rewriting code and adding unit tests before much of anything else though. I would not want us to fix a bunch of PMD violations for the sake of fixing PMD violations when instead large chunks (with many duplications) should just be removed instead.

I think that answers the question on whether to keep, anyone feel free to re-open if there is more to discuss. I very much appreciate the engagement on this @ssoloff and the drive to improve the code base.

**Comment by DanVanAtta** [comment] 2017-10-18 02:25
Summary: keep codacy, it gives us a history view

**Comment by ssoloff** [comment] 2017-11-16 04:43
I was curious as to why we're showing zero Checkstyle issues in Codacy, so I set up a test repo to play around with my own Codacy setup.  I ran into several issues and opened a support case with Codacy.  Ultimately, there were two separate defects the Codacy team fixed in order for Codacy to correctly use an existing Checkstyle configuration file (as opposed to manually configuring the applicable Codacy code patterns).

Unfortunately, the one thing Codacy can't overcome is our usage of an external suppression filter file.  There's simply no way to inject the value of the `samedir` variable as we do with Gradle.  The latest update I received from Codacy support is that this is out of scope for their tool.

Therefore, as of today, Codacy is unable to read our Checkstyle configuration, and will continue to report zero code style issues.  This effectively makes Codacy useless for tracking Checkstyle issues.  Not a huge deal because the Travis build still enforces no net increase in issues, but it would have been nice to have a history.

Codacy still offers some value in tracking duplication and code complexity.  However, if we ever introduce a tool like PMD which does the same thing, we should revisit dropping Codacy from our PR workflow.

**Comment by DanVanAtta** [comment] 2017-12-09 04:38
I would like to take a second look at dropping Codacy for these reasons:
- there is a lot of value in *never* ignoring "X" marks on PR. I propose we drop anything that is not allowing PRs to show as a green build when they have actually built successfully.
- second, any style/coverage enforcement that we want needs to find its way into the build. Having external tools that we are not required to look is not helpful for the review and code quality assessment. The historical trend is maybe interesting, but is it really useful? We want to drive all analysis warnings to zero, how fast we get there I'm not sure is that important beyond the fact that we get there and stay there.

Please let me know if there is only weak support for Codacy, I am of strong opinion currently to remove it, mostly because I want valid PR builds to always be 'green' so we know 100% that 'red' needs work.

**Comment by ssoloff** [comment] 2017-12-09 06:15
I'm ok with removing it at this point because, to me personally, the value of the history was in the Checkstyle issues, not so much in duplication and code complexity.

**Comment by DanVanAtta** [comment] 2017-12-11 02:07
I think I just removed config for Codacy and CodeCov. @ron-murhammer  FYI.
My goal is that anything which can cause a 'red X' on PR and we just ignore would be removed. I hope we can re-introduce CodeCov at some point.

**Comment by ron-murhammer** [comment] 2017-12-11 02:13
@DanVanAtta I'm fine with removing it for now. I think we just have too many exceptions at this point.

**Comment by ssoloff** [comment] 2017-12-11 02:14
BTW, the corresponding badges on the top-level README will have to be removed, as well.

**Closed by ron-murhammer** 2017-12-11 02:13 UTC
Labels: category: dev & admin process, close pending confirmation, discussion
