### ISSUE TITLE
Map Rendering Error -  Comparison method violates its general contract!

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#320] opened 2016-01-05 06:36 UTC
Hit this stack trace while playing the latest version of master+undo_key branch.   Impacts map drawing when moving units, forces a reload of the game when in this state.. 

```
Exception: Comparison method violates its general contract!
java.util.TimSort.mergeLo(TimSort.java:777)
java.util.TimSort.mergeAt(TimSort.java:514)
java.util.TimSort.mergeCollapse(TimSort.java:441)
java.util.TimSort.sort(TimSort.java:245)
java.util.Arrays.sort(Arrays.java:1512)
java.util.ArrayList.sort(ArrayList.java:1454)
java.util.Collections.sort(Collections.java:175)
games.strategy.triplea.ui.MovePanel.sortUnitsToMove(MovePanel.java:137)
games.strategy.triplea.ui.MovePanel.updateUnitsThatCanMoveOnRoute(MovePanel.java:467)
games.strategy.triplea.ui.MovePanel.access$13(MovePanel.java:445)
games.strategy.triplea.ui.MovePanel$3.mouseMoved(MovePanel.java:1295)
games.strategy.triplea.ui.MapPanel.notifyMouseMoved(MapPanel.java:266)
games.strategy.triplea.ui.MapPanel.access$16(MapPanel.java:264)
games.strategy.triplea.ui.MapPanel$2.mouseMoved(MapPanel.java:400)
java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:330)
java.awt.Component.processMouseMotionEvent(Component.java:6580)
javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)
```
Full stack trace: https://gist.github.com/DanVanAtta/abe2d655026b119910aa

The functionality in MovePanel.java wasn't altered in this location, MovePanel.java: line 137 == line 136 on master:

```
    // sort units based on which transports are allowed to unload
    if (route.isUnload() && Match.someMatch(units, Matches.UnitIsLand)) {
      Collections.sort(units, UnitComparator.getUnloadableUnitsComparator(units, route, getUnitOwner(units), true));
    } else {
      Collections.sort(units, UnitComparator.getMovableUnitsComparator(units, route, getUnitOwner(units), true));   // << this is line 137
    }
```

**Comment by DanVanAtta** [comment] 2016-01-05 20:12
Here is the comparator function in question ("Comparison method violates its general contract!"):
```
  /**
   * Return a Comparator that will order the specified units in preferred move order.
   */
  public static Comparator<Unit> getMovableUnitsComparator(final List<Unit> units, final Route route,
      final PlayerID player, final boolean noTies) {
    final Comparator<Unit> decreasingCapacityComparator = getDecreasingCapacityComparator(units);
    return new Comparator<Unit>() {
      @Override
      public int compare(final Unit u1, final Unit u2) {
        // ensure units have enough movement
        final int left1 = TripleAUnit.get(u1).getMovementLeft();
        final int left2 = TripleAUnit.get(u2).getMovementLeft();
        if (route != null) {
          if (left1 >= route.getMovementCost(u1) && left2 < route.getMovementCost(u2)) {
            return -1;
          }
          if (left1 < route.getMovementCost(u1) && left2 >= route.getMovementCost(u2)) {
            return 1;
          }
        }
        Collection<Unit> transporting1 = TripleAUnit.get(u1).getTransporting();
        Collection<Unit> transporting2 = TripleAUnit.get(u2).getTransporting();
        if (transporting1 == null) {
          transporting1 = Collections.emptyList();
        }
        if (transporting2 == null) {
          transporting2 = Collections.emptyList();
        }
        // prefer transports for which dependents are also selected
        final int hasDepends1 = units.containsAll(transporting1) ? 1 : 0;
        final int hasDepends2 = units.containsAll(transporting2) ? 1 : 0;
        if (hasDepends1 != hasDepends2) {
          return hasDepends1 - hasDepends2;
        }
        // sort by decreasing transport capacity (only valid for transports)
        final int compareCapacity = decreasingCapacityComparator.compare(u1, u2);
        if (compareCapacity != 0) {
          return compareCapacity;
        }
        // sort by increasing movement normally,
        // but by decreasing movement during loading
        // (to filter out armour that has already moved)
        if (left1 != left2) {
          if (route != null && route.isLoad()) {
            return left2 - left1;
          } else {
            return left1 - left2;
          }
        }
        // if noTies is set, sort by hashcode so that result is deterministic
        if (noTies) {
          return u1.hashCode() - u2.hashCode();
        } else {
          return 0;
        }
      }
    };
  }
```

**Comment by DanVanAtta** [comment] 2016-01-16 07:26
This is a problem upgrading to Java8, Java7 JRE's did not enforce the contract, silently ignored.

**Comment by ron-murhammer** [comment] 2016-01-20 03:20
@DanVanAtta Yeah, I ran into this same issue in some areas in the casualty sorting and AI sorting when moving to Java 7/8 as Java 6 didn't enforce the contract strictly.

**Comment by gaborbernat** [comment] 2016-02-02 08:11
that being said, I do consider this a heavy bug, and we should fix it. anyone has already gone for fixing this?

**Comment by DanVanAtta** [comment] 2016-02-02 08:40
I haven't. You're welcome to it @gaborbernat  if you'd like

**Comment by gaborbernat** [comment] 2016-02-02 08:58
will do so :+1:

**Comment by gaborbernat** [comment] 2016-02-07 17:46
do someone has a savegame that replicates this?

**Comment by DanVanAtta** [comment] 2016-02-09 22:26
No, IIRC correctly it wasn't repeatable after loading a save. I suspect we could replicate this with unit tests alone.

**Comment by ron-murhammer** [comment] 2016-02-09 22:39
Usually for these types of errors you have to have certain data that gets compared the breaks the sort contract. I had one in the AI code, that I eventually was able to get a save game to reproduce and test against.

You might be able to just take a fine tooth comb to the method in question to figure out where the issue could exist then write a unit test to try to replicate it.

**Comment by DanVanAtta** [comment] 2016-02-10 05:44
Repro case for you @gaborbernat :

[error_comparison_fails.tsvg](https://files.zenhub.io/56bacdf4aeb01e7a1688e9b9)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

(World at War) Shift select the large US navy group in Sz83 (off of New Guinea/Australia)  and try to move it West towards Davao

**Comment by gaborbernat** [comment] 2016-02-10 06:52
Thanks @DanVanAtta, tried reproducing this during the weekend but creating some player units for unit testings turned out a lot harder than should be (with at first all the magic properties where you specify unit capacity and so on) :-1:  What approach do you guys take for quickly creating units/territories for unit testing?

**Comment by DanVanAtta** [comment] 2016-02-10 09:29
For test units / territories, see: `GameDataTestUtil.java`
For getting gameData objects, here is an example: `LoadGameUtil.loadTestGame("big_world_1942_test.xml");`

**Comment by ron-murhammer** [comment] 2016-02-11 02:46
Here is another save to reproduce it: https://sourceforge.net/p/triplea/bugs/1139/

**Comment by gaborbernat** [comment] 2016-02-13 09:28
uploading the other save here [test.tsvg](https://files.zenhub.io/56bef73595307a0978e7d847)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by DanVanAtta** [comment] 2016-02-18 10:25
Switching this to highly requested rather than a release blocker. The error existed in the last release, so it is not anything new that we added. It is a pretty annoying/bad bug, so still gets the 'highly requested' label.

**Comment by gaborbernat** [comment] 2016-02-18 10:39
Will allocate time to look into this on Sunday, next week. Sadly, until
then I'm quite booked.

Bernát GÁBOR

**Comment by gaborbernat** [comment] 2016-02-28 18:32
This is a hard bastard to be working on it. :D Spent four hours trying to reproduce it in a unit test, and still did not manage, even with having the reproducible test case.

**Comment by gaborbernat** [comment] 2016-03-21 07:00
@ron-murhammer I think this shouldn't be release blocker.

**Comment by ron-murhammer** [comment] 2016-03-21 23:23
@gaborbernat I would really like to fix this if at all possible before the next release. This is probably one of the only major stability bugs that affects all maps we have. It will be even worse with the new release since we'll require Java 8 so everyone will potentially experience it. 

IMO stability is our number one priority and this is more important than just about every other issue and PR we have. The one saving grace is that it at least doesn't crash the game but only has the error window popup. I've personally hit this bug several times and then have to select only a subset of units at a time to get around it.

If you don't think you'll have time to tackle this over the next few weeks then I would like either myself or @DanVanAtta to take a stab at it. Yeah, these sorting issues can be difficult to solve as I had a similar one in the AI code a few months back.

**Comment by DanVanAtta** [comment] 2016-03-21 23:28
I've only seen the problem on WaW. My guess is 90% of people are on at least Java7, so I would suspect the problem is likely as pervasive as it will be. With that said, @gaborbernat , please publish what you have so far. I could perhaps take a look at it next weekend.

**Comment by ron-murhammer** [comment] 2016-03-21 23:41
@DanVanAtta I've seen it on Great War and NWO as well. I have a feeling less people are on Java 7/8 than you think. We still have users post about being on Windows XP...

**Comment by DanVanAtta** [comment] 2016-03-21 23:45
XP surprises me less than Java6 - point taken though.

**Comment by DanVanAtta** [comment] 2016-04-08 06:07
@ron-murhammer : release blocker is bad label / process here IMO:
 - java7/8 is almost certainly a majority of people playing the game, java6 is not *that* common.
 - this has been existing bug, so no reason to insist we fix it now (moving the goal posts)
 - frankly I don't think we have the resources/time to dedicate so much time to this
 - we've yet to do release testing, we can let the really annoying bugs surface then. The next release can bake a week or two before we have everyone upgrade.  We do not have to pull the switch so quickly like we did last time.
 - it's not that hard to work around the bug when you hit it, it is not a show stopper
 - the bug is a bit hard to hit, requires a mix of units and certain situations on maps that are played mostly by experienced players only, who are able to work around it.

**Comment by ron-murhammer** [comment] 2016-04-11 02:47
@DanVanAtta While this is definitely an existing bug it will only continue to show up more and more as we now require Java 8. This is probably the most annoying and widespread bug we have in the current release which is why I'd like to fix it for the next release. IMO, stability issues and bugs that affect all maps/playmodes are the most important to address. If we get to a point that this is the only remaining release blocker open then we can discuss pushing this to the following release.

I'll assign this to myself and try to find some time this week or next week to fix it.

**Comment by ron-murhammer** [comment] 2016-04-28 02:31
@DanVanAtta @gaborbernat This should now be fixed with #630. Unfortunately, I can't test any of the uploaded save games since they were created with old maps.

**Comment by DanVanAtta** [comment] 2016-05-02 00:30
You should be able to load a save from an old map using a new one. We have the map name conversion logic in place that will do the translation. But.. trying to load the old maps I get this error:
![error](https://cloud.githubusercontent.com/assets/12397753/14945264/5915c634-0fc2-11e6-9a20-9fd5bdab3b0f.png)

Our auto-versioning is not doing what it should. Note that it thinks our saved maps are version 0.0.

**Closed** 2016-05-03 03:47 UTC
Labels: Close Pending Confirmation, High Priority, Release Blocker

**Comment by DanVanAtta** [comment] 2016-05-03 04:20
good work getting this out of the door @ron-murhammer
