### ISSUE TITLE
com.apple.eawt not working for Java 9+

### ISSUE THREAD

**Issue by chronodm** [triplea-game/triplea#3297] opened 2018-03-18 21:59 UTC
### Engine version

1.9.0.0.9687

### My Operating System

macOS 10.13.3 (High Sierra)

### Map name

WW2 classic 3E

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Start a local game, configure AI players, click "Play"

### Do you have the exact error text? Please copy/paste if so

```
TripleA engine version 1.9.0.0.9687
Loading map: world_war_ii_classic, from: /Users/dmoles/triplea/downloadedMaps/world_war_ii_classic-master.zip
Loading resources from the following paths: [/Users/dmoles/triplea/downloadedMaps/world_war_ii_classic-master.zip, /Applications/TripleA.app/Contents/java/app/assets]
Loading map: world_war_ii_classic, from: /Users/dmoles/triplea/downloadedMaps/world_war_ii_classic-master.zip
Loading resources from the following paths: [/Users/dmoles/triplea/downloadedMaps/world_war_ii_classic-master.zip, /Applications/TripleA.app/Contents/java/app/assets]
Error: com/apple/eawt/QuitHandler
java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler
	at games.strategy.triplea.ui.menubar.FileMenu.addExitMenu(FileMenu.java:104)
	at games.strategy.triplea.ui.menubar.FileMenu.<init>(FileMenu.java:45)
	at games.strategy.triplea.ui.menubar.TripleAMenuBar.<init>(TripleAMenuBar.java:35)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:247)
	at games.strategy.triplea.TripleA.lambda$startGame$0(TripleA.java:121)
	at games.strategy.ui.SwingAction.lambda$invokeAndWait$0(SwingAction.java:86)
	at games.strategy.ui.SwingAction.lambda$invokeAndWaitResult$1(SwingAction.java:114)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
```

### Instead of this error, what should have happened?

Game should start

### Any additional information that may help

```
$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

**Comment by RoiEXLab** [comment] 2018-03-18 22:20
Just to be sure: Does this error happen using java 8 as well?

**Comment by ron-murhammer** [comment] 2018-03-18 22:29
@RoiEXLab Guessing its the same problem reported here: https://github.com/kaikramer/keystore-explorer/issues/102

**Comment by ZjelcoP** [comment] 2018-03-18 23:32
Release 9824
macOS 10.12.6
Java 8 
No problems

**Comment by RoiEXLab** [comment] 2018-03-19 17:28
Found the reason: http://openjdk.java.net/jeps/272
The good news: We no longer need to depend on this stupid legacy library
The bad news: It doesn't look like this feature will be backported to java 8, so we'll have to rely on reflection if we don't want to upgrade to java 9.

**Comment by RoiEXLab** [comment] 2018-03-19 17:34
As a side note: The official release date of java 10 is tomorrow.
See http://openjdk.java.net/projects/jdk/10/
[Oracle announced that "Java SE 9 will be a short term release, and users should immediately transition to the next release (18.3) when available."](http://www.oracle.com/technetwork/java/eol-135779.html)
So if Java 10 will be available at java.com we could consider moving to a newer version of Java

**Comment by RoiEXLab** [comment] 2018-03-19 21:27
Assigning you all @DanVanAtta @ron-murhammer @ssoloff to get your opinion on how to handle this issue.
Please read my comments above to get a good picture of what's going on.


We basically have 3 options:
1. Just ignore this for now, and wait until we can upgrade the java version and use the Desktop API from there.
2. Try some dark reflection magic and check if TripleA is running with Java 9 or higher (too bad the version comparison classes are a java 9 feature ^^) i.e. the required methods exists and invoke them if they do.
3. Just drop the dependency on orange-extensions, and use reflection for everything instead of partial reflection and partial "polyfilling" (not sure if this is the right term, but it reminds me of JavaScript)

**Comment by chronodm** [comment] 2018-03-19 22:30
Just my 2¢ as a developer—the [reflection hack used in keystore-explorer](https://github.com/kaikramer/keystore-explorer/pull/103/files) doesn't seem completely horrible, bearing in mind there's likely to be a transition period when you need to support <= 1.8 as well as 9+, even after Oracle drops support for Java 8 next year.

**Comment by RoiEXLab** [comment] 2018-03-19 22:38
@chronodm Agreed, however we currently require users to use java 8 or higher, so incrementing the version required might not be a huge deal at all.

**Comment by ron-murhammer** [comment] 2018-03-19 23:06
@RoiEXLab I'd probably prefer to be able to support Java 8 and 9 for a while. And wait to force users to upgrade to Java 9 after a good portion have already done so through Oracle updates/etc. Otherwise we are either going to keep getting bug reports like this or we need to force Java 9 very soon which is a bit early IMO.

**Comment by chronodm** [comment] 2018-03-19 23:46
Java 9 isn’t considered a long-term support release, I don’t think, so it might be a bit harsh to force casual users to upgrade to it now.

**Comment by ssoloff** [comment] 2018-03-20 02:48
@RoiEXLab I think a pure reflection-based solution similar to what @chronodm linked would be acceptable until we dropped Java 8 support (i.e. your option (3)).

**Comment by DanVanAtta** [comment] 2018-03-20 03:48
We currently bundle a JDK8 for Mac+Windows with the installer.  @chronodm was this reproduced by running one of the installers, or launching from a jar file or source? If from an installed TripleA, it would mean our bundled JDK is not being used.

**Comment by chronodm** [comment] 2018-03-20 15:23
Interesting. That was running the game after installing with the Mac installer. I'm away from that machine at the moment but when I get back to it I'll see if I can find any other configuration information that might help.

**Comment by RoiEXLab** [comment] 2018-03-20 15:40
Technically we don't bundle a JRE.
The installer is just configured to download one if the system it runs on doesn't have a JRE preinstalled.
Because we currently don't have a maximum java version, the java 9 JRE is treated as perfectly fine and therefore no additional JRE will be downloaded and the existing JRE will be used.

**Comment by ssoloff** [comment] 2018-03-20 15:51
@RoiEXLab Should we temporarily revert the portion of 8913692bb that removed Java 8 as the max version supported by the installer?  We have several issues at the moment that prevent the application from running correctly on Java 9+ (most notably JDK-8199664).  We can always direct users to the portable install for Java 9+ testing.

**Comment by RoiEXLab** [comment] 2018-03-20 15:53
@ssoloff probably the best option for now.

**Comment by RoiEXLab** [comment] 2018-03-20 15:59
@ssoloff We should probably also consider changing the second travis build to java 10 to ensure the code still compiles.

**Comment by RoiEXLab** [comment] 2018-03-20 17:31
@ssoloff #3304

**Comment by DanVanAtta** [comment] 2018-09-11 02:09
@RoiEXLab @ssoloff ; is this mitigated? Anything left to do?  A new issue to track any open items I think would be useful to keep our task list clean. Otherwise perhaps we would want a summary of the things we would need to be java 9 / java 10 ready.

**Comment by ssoloff** [comment] 2018-09-11 03:12
Sorry, don't have access to a Mac, so I don't know if this is still an issue.  Regardless, labeling as a Java 9+ blocker.

**Closed** 2019-01-05 16:33 UTC
Labels: category: problem
