### ISSUE TITLE
Unsaveable Stuck Game (1.9.0.0.12421)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#4399] opened 2018-11-29 21:30 UTC
I'm using TripleA 1.9.0.0.12421 and joined Bot502_LONDON_UK this day.

The bot was up and the game could be joined an seen normally, but not saved. Attempting to, I got no savegame, but I received this error:

>nov 29, 2018 10:13:40 PM games.strategy.engine.framework.GameRunner lambda$start$0
GRAVE: Exception on remote
java.lang.RuntimeException: Exception on remote
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:54)
	at games.strategy.engine.framework.$Proxy6.getSavedGame(Unknown Source)
	at games.strategy.engine.framework.ClientGame.saveGame(ClientGame.java:204)
	at games.strategy.triplea.ui.menubar.FileMenu.lambda$createSaveMenu$0(FileMenu.java:52)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:65)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.framework.ServerGame.SERVER_REMOTE
	at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:89)
	at games.strategy.net.AbstractServerMessenger.notifyListeners(AbstractServerMessenger.java:468)
	at games.strategy.net.AbstractServerMessenger.messageReceived(AbstractServerMessenger.java:289)
	at games.strategy.net.nio.NioSocket.messageReceived(NioSocket.java:119)
	at games.strategy.net.nio.Decoder.loop(Decoder.java:89)
	at java.lang.Thread.run(Thread.java:748)

After a few minutes, the game crashed and I got a second screen, with the game waiting for player and autoloaded (the other screen still had the game open but not saveable, just like previously).

The game was started and I kept having double screen, and in both screens I was able to see the moves being made and, now, save the game successfully. Just like when you join a same game twice, but, in this case, having only 1 of me inside; listed, at least.

Then the game got back waiting for players, and my situation was normalized to 1 screen only (I didn't close anything; the game went back waiting for player because the one that was playing it quit).

This is the lobby report that made me join that automated host:

>(22.12.41) AdamF (1):  You were slapped by AdamF (1)
(22.12.52) AdamF (1):  I am having trouble saving a game
(22.13.01) Cernel:  ok where?
(22.13.05) AdamF (1):  502

Apparently, he experienced the same things I did.

**Comment by ssoloff** [comment] 2018-11-29 22:16
I'm having trouble reproducing this.

Looking at the stack trace, my initial theory was that the bot or client may be running incompatible versions.  Specifically where the `SERVER_REMOTE` channel got renamed accidentally, although  I don't recall that happening any time in the past two years.

I logged into Linode and  confirmed that bot 502 is running 1.9.0.0.12226, as expected.  I set up a local bot running that version, and connected to it with a client running 1.9.0.0.12421.  Saving a game was successful.

I tried doing some other things, such as first connecting with a 1.9.0.0.3635 client, starting the game, and then joining the in-progress game with a 12421 client.  But, again, saving the game was successful.

I then tried connecting to bot 502 directly with a 12421 client, starting a game, and saving it.  Again, it was successful.

@Cernelius Is there any other information you can provide that will help us to reproduce the problem?  For example, the map that was loaded (don't think that would matter, but...), the engine versions of any other players that were connected to the bot at the time, etc.

**Comment by Cernelius** [comment] 2018-11-30 01:47
AdamF was the one that got stuck in that game. I didn't ask him what version he was using. I think this is something that keeps happening at some intervals, when the bots get (quite commonly) stuck, for reasons I don't know. It is quite frequent to see people in the lobby that tell each other to change bot, as the one they were using got stuck. Sometimes this result in being even unable to save the game, sometimes you can.

The game was a round 4 of WWII Revised. So, I don't think that matters in any way (it should be very light on the RAM etc.).

**Comment by Cernelius** [comment] 2018-11-30 01:52
Related Bot502_LONDON_UK chatlog:

>(9:01:49 PM) darquan:  you there?
(9:05:33 PM) darquan:  i guess you're frozen or you had to leave, i saved, cya
--- hammond has joined ---
--- hammond has left ---
--- darquan has left ---
--- AdamF (1) has joined ---
--- AdamF (1) has left ---
--- AdamF (1) has joined ---
--- Cernel has joined ---
(9:13:28 PM) AdamF (1):  hey, had a power outage
(9:13:38 PM) AdamF (1):  came back and was logged in 2x
(9:13:59 PM) AdamF (1):  tried to save "excpetion on remote"
(9:16:00 PM) AdamF (1):  u here?
--- AdamF has left ---
(9:16:57 PM) Bot502_LONDON_UK:  Unrecognized error occurred: Exception on remote, if this is a repeatable error please make a copy of this savegame and report to:
https://github.com/triplea-game/triplea/issues/new
--- AdamF (1) has left ---
--- AdamF (1) has joined ---
(9:17:41 PM) Cernel:  did nothing btw
(9:17:54 PM) AdamF (1):  thjats funny
(9:18:12 PM) AdamF (1):  it worked!
(9:18:20 PM) AdamF (1):  thanks for nothing
(9:18:22 PM) AdamF (1):  :)
(9:19:52 PM) Cernel:  can you move 1 piece?
(9:20:02 PM) AdamF (1):  i saved, thats fine
(9:20:05 PM) AdamF (1):  thanks
(9:20:09 PM) Cernel:  plz move 1 piece
(9:20:24 PM) AdamF (1):  canb move
(9:20:28 PM) AdamF (1):  can, NP
(9:20:41 PM) Cernel:  cool
--- AdamF (1) has left ---
(9:20:55 PM) Bot502_LONDON_UK:  Unrecognized error occurred: Exception on remote, if this is a repeatable error please make a copy of this savegame and report to:
https://github.com/triplea-game/triplea/issues/new
--- KingKelly has joined ---
(9:22:34 PM) KingKelly:  hi
(9:24:08 PM) Cernel:  ah sorry not actuall searching for players
--- Cernel has left ---

It looks like it happened after a power outage on the side of the hosted player.

I asked about moving 1 piece to verify both screens I had open were showing the same (they were).

**Comment by ssoloff** [comment] 2018-11-30 03:39
> It is quite frequent to see people in the lobby that tell each other to change bot, as the one they were using got stuck.

Do the mods typically restart bots when this happens or do the bots eventually "fix themselves"?  (BTW, I looked at bot 502 again, and it appears to have been running since Nov. 20, so it hasn't been restarted since this problem was reported earlier today.)

> It looks like it happened after a power outage on the side of the hosted player.

I just want to verify I'm not misunderstanding something...  What do you mean by "hosted player"?  If the error occurred on a bot, the bot would be considered the "host", and that's what the log above seems to suggest.  I'm interested in understanding why you made that distinction between the players, just in case it has something to do with reproducing the problem.

The power outage aspect is interesting.  It may be that an unexpected disconnect on the part of one of the players is crashing some bot subsystem such that it no longer responds to future requests, as your original stack trace shows.  I'll play around with disconnecting in the middle of a game to see if that helps me reproduce the problem.

**Comment by Cernelius** [comment] 2018-11-30 21:31
Been a while since I did anything to fix any bots, but I recall the Remote Stop Game rarely or never worked. Now since there are usually too many bots they rarely tell about problems, but just move to another working bot. I don't know if bots irreversibly break down or not; I'm not using anything remote since a long time, either. You need to ask this the people that are into bots.

The hosted player is the human player that is being hosted. In a bot, since there is none playing from the terminal where the bot is, nor the bot itself plays, nor any AI is available for bots, I could have just said the "player", were it non that TripleA also calls the player or players that the player is playing as players (so, if I say player, I may mean either the player that is playing the player or players, or the player or players that are to be played by a player).
I suppose it makes sense that if the bot is a host, then the users that join a bot are hosted (and may or may not be players, depending if they selected any players or not).
Practically "hosted player" = "TripleA user that is playing in a host he is not hosting".

I know that if you switch off the computer that causes the host to ghost or something. Tho being able to join it (after the crash or whatever) but not to save it is what it is really strange and unusual for me.

Asked AdamF about the version:
>(22.28.40) AdamF:  ?
(22.28.51) AdamF:  Hi quim...in game
(22.28.55) Cernel:  I meant
(22.29.00) Cernel:  when you start triplea
(22.29.03) Quimby:  he left adam?
(22.29.11) Cernel:  you should see something like 1.9.0.0.
(22.29.16) AdamF:  i do
(22.29.17) Cernel:  what is the number after that
(22.29.28) AdamF:  11996
(22.29.31) Cernel:  ok tx

**Comment by ssoloff** [comment] 2018-12-04 05:12
Unfortunately, I'm still unable to reproduce this issue.  I played around with several theories, but I could never get the bot into a state where the `IServerRemote` service was not running (which would produce the reported exception when a client attempted to save a game while connected to the bot).

I don't really know what to try next.  The only thing I can suggest--when this happens the next time--is we should look at the bot logs around the time of the incident.  Any errors there may yield clues as to how the `IServerRemote` service is either a) failing to be registered when the `ServerGame` is created or b) is being unregistered unexpectedly during the game (unregistration should only happen when the `ServerGame` is shut down).

**Comment by ron-murhammer** [comment] 2018-12-30 06:41
Closing this as I don't think there is anything we can do without being able to reproduce it.

**Closed by ron-murhammer** 2018-12-30 06:41 UTC
