### ISSUE TITLE
AI Strategic Bombs Already Max Damage Factories

### ISSUE THREAD

**Issue by drockken** [triplea-game/triplea#6718] opened 2020-06-18 17:32 UTC
### How can the problem be recreated?

Set up a factory with maximum damage, and an opportunity for the AI to strategic bomb the factory. 

### What is an expected fix?

AI enhancement to not strategic bomb factories that cannot be damaged any further.  An algorithm could be added to deny bombing when expected damage is less than the expected cost of losing the plane.

I think I have seen this issue with tactical bombers and harbors/airfields as well, but I don't have an example.

### Which Engine Version are you using?
2.0.19993  - I have seen this issue in a number of different versions of TripleA.  I attached a save-game, look at Italy's most recent move to see.  The max factory damage in London is 20, but Italy strat-bombs the factory anyway.

Let me know if the Zip doesn't upload.

[sb_max_dmg.zip](https://github.com/triplea-game/triplea/files/4800189/sb_max_dmg.zip)

**Comment by beelee1** [comment] 2020-06-22 06:19
Maybe AI wants to make sure those factories are obliterated. Might want to ask @ron-murhammer he's the AI guy :)

**Comment by panther2** [comment] 2020-06-22 08:59
FWIW I just want to add that "overbombing" is not violating the rules, however useless it appears to be.

**Comment by DanVanAtta** [comment] 2020-06-22 14:10
This is the right place to report. Please do not PM or ask specific people
to look at items.

If only one person handles an issue they are unlikely to create
documentation, build code that is easily understood by others, and they
themselves are stuck as they cannot go on vacation. If they do go manage to
go on vacation, then it leaves the rest of us in a bad place

**Comment by frigoref** [comment] 2022-03-31 19:20
@panther2 @DanVanAtta @beelee1 
I have no clue what the issue here is. Can anyone summarize this nicely and provide an example that can be used?

> AI enhancement to not strategic bomb factories that cannot be damaged any further. An algorithm could be added to deny bombing when expected damage is less than the expected cost of losing the plane.
> 
> I think I have seen this issue with tactical bombers and harbors/airfields as well, but I don't have an example.
My questions would be:
- Is the rule with the "execpted cost of losing the plane" making any sense to you guys? The damage can be repaired, no? Shouldn't the rule reflect the likelihood of killing the factory unit?
- How about examples for tactical bombers and harbors/airfields? Can anyone provide them as well?

**Comment by beelee1** [comment] 2022-03-31 23:29
@frigoref The Factories can only be damaged not destroyed. So the AI is risking losing a Bomber for no gain once maximum damage has been attained. Harbors and Airfields work the same as factories in that they can't be destroyed. Tac Bmbrs may only attack Harbors and Airfields, not Factories.

I assume this refers to the Global 40 game, I didn't look at the save, but it is possible and other games may have it, where the "infrastructure" (factories, airfields, harbours, etc...) can be destroyed.

Someone else was working on the AI for a while after Ron, but I can't remember who it was and if they ended up finishing anything with it.

**Comment by DanVanAtta** [comment] 2022-04-01 05:55
Is this fixed now? I recall reading in forums that someone mentioned this was no longer a problem.

**Comment by beelee1** [comment] 2022-04-01 06:44
> Is this fixed now? I recall reading in forums that someone mentioned this was no longer a problem.

I hadn't heard that. I don't play with the AI. @RogerCooper have you seen this with the AI recently ?

**Comment by panther2** [comment] 2022-04-01 10:13
@frigoref @DanVanAtta @beelee1 

The reason to 'overbomb' might be to attract enemy fighter to act as interceptors  - so they cannot have an active part in the follow up battle. So this really is an AI-issue only.

**Comment by beelee1** [comment] 2022-04-01 10:32
@panther2 yea AI only and not against the rules but it'd perform better if it didn't do that though. I would think most humans would just let the AA take a crack at the Bmbrs and let their Ftrs sortie elsewhere. Would depend on there Air Battle value I guess.

**Comment by panther2** [comment] 2022-04-02 09:12
@beelee1 Just wanted to point that out again. I remember discussions on A&A .org where players made have use of overbombing and others erroneously thought it was against the rules.

**Comment by frigoref** [comment] 2022-04-02 10:01
@beelee1 @panther2 At should be the new rule to be implemented for our AI?
I would suggest something like 
'strategic bombing only if no AA guns and hit potential >= min damage to kill at least one unit'.
What are your suggestions?

**Comment by panther2** [comment] 2022-04-03 13:03
@frigoref 

As in some games facilities have their own 'built-in' AAA "no AA guns" would never qualify.

I'd suggest an AI rule as simple as: 'strategic bombing only if current damage < max. damage'.

**Comment by frigoref** [comment] 2022-04-03 13:21
> @frigoref
> 
> As in some games facilities have their own 'built-in' AAA "no AA guns" would never qualify.
> 
> I'd suggest an AI rule as simple as: 'strategic bombing only if current damage < max. damage'.

Current damage and max. damage of what, @panther2 ?

**Comment by panther2** [comment] 2022-04-04 09:05
@frigoref 

Current damage and max. damage of facilities subject to being bombed. 

Or have I misunderstood something?

**Comment by frigoref** [comment] 2022-04-06 23:03
@panther2 , @beelee1 , @DanVanAtta 
Can someone have a look for my commit [667701f](https://github.com/frigoref/triplea/commit/667701f60cf80a4073500f3c9b13d44ecb84a858)?
It is my first in the AI area and I am not sure the logic makes sense in all cases.

My test was positive and I derived it from the initially provided save game. Here for your own retest [sb_max_dmg_IT_combat.zip](https://github.com/triplea-game/triplea/files/8434866/sb_max_dmg_IT_combat.zip)

**Comment by frigoref** [comment] 2022-04-19 21:27
Pretty please :innocent: (@panther2 , @beelee1 , @DanVanAtta )

**Comment by beelee1** [comment] 2022-04-20 05:37
@frigoref heh heh I can test the save but @asvitkine and @RoiEXLab would be better suited to reviewing your code changes :)

**Comment by frigoref** [comment] 2022-04-20 07:12
@beelee1 A functional test on your end would be great to confirm the issue is solved from a user perspective.
Please provide feedback here.

**Comment by asvitkine** [comment] 2022-04-20 11:41
@frigoref Thanks for looking at this.

I think when you're looping through `for (final Unit targetUnit : t.getUnitCollection()) {`, you need to check if the units are factories that can be bombed, and not just any unit. So you need something like `Matches.unitCanProduceUnitsAndCanBeDamaged()`.

But also, there's a check above for `.and(Matches.unitIsLegalBombingTargetBy(unit))`, so I'm not sure a map that's independent of the units makes sense in this case. Perhaps start with just doing the computation each time so we can get the logic right, and then we can see if there's an opportunity to optimize? Bombers are fairly rare so it may not be necessary to do more optimization...

**Comment by frigoref** [comment] 2022-04-20 20:59
@asvitkine Thanks for the feedback! 
I have added another commit [8e48922](https://github.com/frigoref/triplea/commit/8e48922ce9ed20ae288e711ca2b7e940c3f0c6d5) and was able to reuse a match for this.
Please check the new version and let me know if you see anything else.

**Comment by frigoref** [comment] 2022-04-25 17:32
@asvitkine 
Thanks for your feedback! I have create PR [10367](https://github.com/triplea-game/triplea/pull/10367) AI Strategic Bombs (Issue 6718)

Concerning your example **A bombs B and X bombs Z** (B and Z are different factory types) I have to say I am not that familiar with this. If I understand you correctly, than what is missing is the maxDamage check against the individual target unit.
If this is the case, then that is not the topic of this issue, but a separate one, right?
Before there was no such check and with the PR there is still none, so the PR could go through nevertheless.

My understanding would be that for your described case the damage would have to be assigned only to the potential target units. Then the territory is only a potential target for bombing if for any units `minDamageNeeded <= maxDamage`.
Is that also your understanding? Could it be that a factory unit has a minimal damage _for each_ bombing unit, meaning is it correct to sum up the potential damage of all bombing units?
I already have something in the making, but I can commit this after the questions are clarified and potentially after  PR [10367](https://github.com/triplea-game/triplea/pull/10367).

**Comment by asvitkine** [comment] 2022-04-26 13:31
> Concerning your example **A bombs B and X bombs Z** (B and Z are different factory types) I have to say I am not that familiar with this. If I understand you correctly, than what is missing is the maxDamage check against the individual target unit. If this is the case, then that is not the topic of this issue, but a separate one, right? Before there was no such check and with the PR there is still none, so the PR could go through nevertheless.

I was going by the actual APIs and code that exist in the game right now, which seem to imply the above scenario is possible. Notably:

```
  public static Predicate<Unit> unitIsLegalBombingTargetBy(final Unit bomberOrRocket) {
    return unit -> {
      final UnitAttachment ua = UnitAttachment.get(bomberOrRocket.getType());
      final Set<UnitType> allowedTargets =
          ua.getBombingTargets(bomberOrRocket.getData().getUnitTypeList());
      return allowedTargets == null || allowedTargets.contains(unit.getType());
    };
  }
```

This implies that there can be different types of bombers that are allowed to bomb different buildings. Since the code above checks the attachment on the bomber/rocket and checks the allowed targets on that attachment. Let's continue discussion on the PR.

**Comment by panther2** [comment] 2022-04-27 07:41
FWIW, indeed, different bombers can attack different targets. E.G. Tactical bombers may bomb Harbors and/or Airfields, while Strategic Bombers may bomb Industrial Complexes and/or Harbors and/or Airfields (example taken from 1940_global).

**Closed** 2022-06-29 15:57 UTC
Labels: Problem, AI

**Comment by frigoref** [comment] 2022-06-29 17:49
@asvitkine As the coding avoids any air battles, wouldn't the additional feature  be:
**Also** when there is a potential air battle, bombers should be considered bombing when expected damage is less than the expected cost of losing the plane. 
Or how can a bomber be damaged during bombing at the moment?

**Comment by asvitkine** [comment] 2022-06-29 17:51
I think it doesn't take into account AA?

**Comment by drockken** [comment] 2022-06-29 18:58
As the submitter of this problem report to begin with, I think the context of the original issue has been lost, or at least I can't see that it has been directly addressed.

Take a major factory that can have a maximum of 20 damage and has been damaged to the maximum extent (20).  The AI should not send bombers to bomb that same factory, because the built in AA could shoot down the bomber but no additional damage could be inflicted to the factory.   If this no longer happens, then as far as I am concerned, the issue has been fixed.

Surely, the AI could be improved to make decisions in circumstances when the factory is only at 16/20 damage, whether there are intercept (or escort fighters), or other better uses of the bomber.  But that is beyond the scope of the submitted problem and could go in as a separate tracking item.

~drock
________________________________
