### ISSUE TITLE
Various parse errors

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#3115] opened 2018-02-23 00:11 UTC
### My Operating System:
windows 10
### Engine version:
9176
### Map name and version:
Bad-Ass 4-Nation FFA, Big World 3, Invasion USA, TWW Beta
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Getting various parse errors for many existing maps. 

And on one map, a missing map message.

### Do you have the exact error text? Please copy/paste if so

1. Could not parse:file:/C:/Users/joew2/triplea/downloadedMaps/Bad-Ass_4-Nation_FFA-master/map/games/Bad-Ass_4-Nation_FFA_v.1.6.0.20_v1.9.xml
games.strategy.engine.data.GameParseException: Missing property definition for option: isParatroop

2. For big world 3 it asks me to download because its missing, but not correct, does exist.

3. Could not parse:jar:file:/C:/Users/joew2/triplea/downloadedMaps/invasion_usa-master.zip!/invasion_usa-master/map/games/UnderSiege_America.xml
games.strategy.engine.data.GameParseException: Missing property definition for option: productionOnly

4. Could not parse:jar:file:/C:/Users/joew2/triplea/downloadedMaps/total_world_war-master.zip!/total_world_war-master/map/games/Total_World_War_Dec1941_Beta.xml
games.strategy.engine.data.GameParseException: Missing property definition for option: TransportCapacity

### Instead of this error, what should have happened?
They all load in 8932

### Any additional information that may help:
There's probably many more maps that wont load too. Looks large scale.

**Comment by ron-murhammer** [comment] 2018-02-23 01:23
@RoiEXLab @ssoloff @DanVanAtta Did we merge something that effects map parsing recently. Looks like the reflection removal isn't merged yet.

**Comment by ssoloff** [comment] 2018-02-23 01:26
@ron-murhammer #3042 was merged 12 hours ago.

**Comment by ron-murhammer** [comment] 2018-02-23 01:27
@ssoloff Ah, I see now. I saw the new PR to fix the issue from that and thought it was the original still. Looks like we are aware of the issues.

**Comment by prastle** [comment] 2018-02-23 01:27
Could be the ld v3 bw  error returning but either way parsing the bots takes forever! Just some help. I could be out to lunch.

**Comment by ssoloff** [comment] 2018-02-23 01:52
@General-Dru-Zod This probably wasn't communicated on the forum, but several maps were updated in order for them to work properly with the changes in #3042.  You may have versions of those maps that aren't the latest (they were updated three days ago).  Could you please update your maps and try again?  (Note that the updated maps should be backwards compatible with older engines, so you should still be able to use them if you switch back to an older engine version.)

I tried the latest _Total_World_War_Dec1941_Beta.xml_, and it works fine.  I'll look into the others in the meantime.

BTW, where do I find Big World 3?

**Comment by ssoloff** [comment] 2018-02-23 01:56
I was able to reproduce the problem in Invasion USA.  Investigating now.

Another BTW, where do I find Bad-Ass 4-Nation FFA?

**Comment by ssoloff** [comment] 2018-02-23 02:15
Confirmed a code bug for Invasion USA.  We didn't have a handler for the `productionOnly` property of `TerritoryAttachment`.  I'll submit a PR shortly.

**Comment by ssoloff** [comment] 2018-02-23 02:31
I see that Bad-Ass 4-Nation FFA is a custom map that does not yet have a repo.  However, I confirmed that, once again, there is no handler for the `isParatroop` property of `UnitAttachment`.  Note that this property has been deprecated, but I'm going to go ahead and add a no-op handler for it anyway, similar to how the current stable processes it.

@General-Dru-Zod Could you please provide a link to the latest Bad-Ass map so I can test the fix?

**Comment by ssoloff** [comment] 2018-02-23 02:36
@RoiEXLab I suspect typos similar to the ones you fixed in the triplea-maps repos are present in unofficial maps like those published by @General-Dru-Zod and @RogerCooper.  You might want to create a forum thread so we can coordinate those fixes.

We should also announce that official maps have to be updated to the latest in order for them to work with the pre-releases 9147 and later.  (Apologies if I missed that already on the forum.)

**Comment by ssoloff** [comment] 2018-02-23 02:43
Never mind about Big World 3; I found it.  However, I'm not able to reproduce the problem described above.

**Comment by ron-murhammer** [comment] 2018-02-23 02:58
@ssoloff Looks like TWW has the same problem with capitalization: TransportCapacity. Is there a reason we decided not to still support capitalizing the first letter. My guess is there are a bunch of maps in progress and maps outside the official repo that probably will be broken.

**Comment by DanVanAtta** [comment] 2018-02-23 03:06
v9176 is not yet released as a latest, is this problem impacting users with the latest release version (1.9.0.0.7621)?

**Comment by ssoloff** [comment] 2018-02-23 03:06
@ron-murhammer

> Looks like TWW has the same problem with capitalization

I believe @RoiEXLab fixed that prior to merging #3042.  As I mentioned above, that was only a few days ago, so you'll need to update to the latest map.  (I only tested _Total_World_War_Dec1941_Beta.xml_, which is working; if you're seeing it in other maps please advise.)

> Is there a reason we decided not to still support capitalizing the first letter.

 @DanVanAtta asked that question [here](https://github.com/triplea-game/triplea/pull/3042#issuecomment-366788407), and @RoiEXLab responded [here](https://github.com/triplea-game/triplea/pull/3042#issuecomment-366788922).  My interpretation of @RoiEXLab's answer is that those maps were technically malformed and should be fixed.

That's not a big deal when we can update the maps.  Unfortunately, it did not occur to us (well, at least to me) to consider unofficial maps where we can't easily update them.  It should be straightforward to lookup the property names in a case-insensitive manner, but I'll let @RoiEXLab comment on that.

**Comment by ssoloff** [comment] 2018-02-23 03:08
@DanVanAtta The specific problems described in this issue should not affect users on latest stable.  However, to be safe, let me try loading some of the recently-modified maps in 7621 to ensure we don't have a P0/1 issue.

**Comment by ron-murhammer** [comment] 2018-02-23 03:09
Thought we were using P0 for live stable issues and P1 for issues with master?

**Comment by General-Dru-Zod** [comment] 2018-02-23 03:09
Sorry as Big World 3 goes, it's actually fine. I have an obsolete version I was missing with called Bigger World 3 and accidently clicked that one in my list. 

As Bad-Ass 4-Nation FFA goes, I have 2 versions. One of which is in progress of being coded for a new feature. Here is the link https://www.sendspace.com/file/bwke05. I have a couple other experimental versions too. But I can fix them, if you can post something explaining the deal.

The TWW beta is most likely updated version of mine. But I have found at least one more that doesn't like "isMechanized". I most likely have some more of them, since I have games not on depot. Some from Roger Cooper's library.

**Comment by ron-murhammer** [comment] 2018-02-23 03:13
@ssoloff Yeah, I'm guessing there are at least some unofficial or in-progress maps with capitalization issues given that we found around 10 in the official repo. Its probably not a huge deal though leaving the capitalization of the first letter might cause less headaches.

**Comment by ssoloff** [comment] 2018-02-23 03:23
@DanVanAtta @ron-murhammer I tested several maps which were updated to work with #3042 using 7621, and they appear to work fine.

However, the latest Invasion USA blows up in 7621.  There have been a ton of modifications to that map over the past two weeks.  I'll report the issue to @WCSumpton over in that repo.

**Comment by ssoloff** [comment] 2018-02-23 03:24
> The TWW beta is most likely updated version of mine. But I have found at least one more that doesn't like "isMechanized"

@General-Dru-Zod Yeah, I saw that `isMechanized` was going to cause the same problem as `isParatrooper`, so I just fixed it at the same time in #3117.

**Comment by DanVanAtta** [comment] 2018-02-23 03:29
> Thought we were using P0 for live stable issues and P1 for issues with master?

Sorry if not clear, P0 and P1 are both for live issues, just different priorities. P0 is fix now, users can't play the game, P1 is something bad that should be fixed very quickly (basically prioritized bugs).

**Comment by ssoloff** [comment] 2018-02-23 04:07
@General-Dru-Zod I confirmed that the Bad-Ass map you linked loads fine with the fix in #3117.  So you should be good with build 9190 or later.

**Comment by ron-murhammer** [comment] 2018-02-23 04:13
@DanVanAtta Ok. I think we are starting to end up in label hell again. They've kind of multiplied over the last couple of months.

**Comment by DanVanAtta** [comment] 2018-02-23 04:31
funny enough, merging the 'type' and 'category' has reduced a good number : )
They've increased a good bit lately with the new "PR" labels.

@ron-murhammer should this still be open, or are we saying the problem is with the maps?

**Comment by DanVanAtta** [comment] 2018-02-23 04:32
Are maps that have been updated, are they compatible with the current latest? *that* is a potential p1 or p0

**Comment by ron-murhammer** [comment] 2018-02-23 04:34
@DanVanAtta I believe the remaining issues are with the specific maps and all known bugs are addressed. Only somewhat outstanding question is whether capitalization of the first letter of properties should be added back in as my guess is that some of the maps not in the official repo probably will have that issue.

**Comment by General-Dru-Zod** [comment] 2018-02-23 04:46
Using 9191 now, the games mentioned above are good now, thank you.

I loaded one from Rogers site, called "Apocalypse 2012"and "Cold War 1965", gets Missing property definition for option 'IsAirTransportable' in attachment 'unitAttachment'. I m guessing it's caused by capitalization of the "I".

**Comment by ssoloff** [comment] 2018-02-23 04:54
> Are maps that have been updated, are they compatible with the current latest? that is a potential p1 or p0

@DanVanAtta As mentioned above, I tested a few earlier in 7621, and there were no problems.  The "legacy" game parser was case-insensitive, so it shouldn't care about the title-case changes @RoiEXLab made to the various map repos.

> I loaded one from Rogers site, called "Apocalypse 2012"and "Cold War 1965", gets Missing property definition for option 'IsAirTransportable' in attachment 'unitAttachment'. I m guessing it's caused by capitalization of the "I". Or was that one deprecated too?

@General-Dru-Zod That property is still supported in the latest game parser, so yes, it's just the capitalization of the leading "I" causing the problem.

**Closed** 2018-02-23 05:50 UTC
Labels: Release Blocker, category: bug
