### ISSUE TITLE
Possibility to choose air unit types that move onto a newly build carrier

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1751] opened 2017-05-24 09:29 UTC
Please add possibility to choose what type of air units should move out onto a newly build carrier. Right now it seems that there is no possibility to choose what type of air units that are to move out onto a carrier after it has been placed. The short version of the current behavior (long can be seen at forum: https://forums.triplea-game.org/topic/73/iron-war-official-thread/79):

•	After carrier placement, there is a popup that lets the player choose how many “fighters” are to be moved to the carrier (at least if the XML has "Move existing fighters to new carriers" value="true")
•	There is no option to choose what type of air units to move in case one has more than one.
•	The engine seems to choose for you, and I do not know the parameters for the engine’s choice. In Iron War it seems to choose 1 fighter and 1 bomber over 3 fighters, and that is not an optimal choice.

**Here are an example from Star Wars Galactic War:**
Going to place a carrier with 1 capacity (1 air unit)
![unavngivet](https://cloud.githubusercontent.com/assets/15268177/26396536/c40d01ae-4073-11e7-984a-3976bc4e5458.png)

After placement I can ofcourse max choose 1, but not what type, even if there are three possible fighters.
![unavngivet2](https://cloud.githubusercontent.com/assets/15268177/26396541/ca7b4640-4073-11e7-8416-e32fce8664f9.png)

Engine just chooses one of the types for you.
![unavngivet3](https://cloud.githubusercontent.com/assets/15268177/26396549/d40a6196-4073-11e7-8327-f57aa7e58ced.png)

**Comment by panther2** [comment] 2017-05-24 09:55
I am not familiar with your map. So sorry if this does not help.

In WWII_Global, the engine lets you choose which sort of **new plane** you want to place on a newly placed carrier:
![tra](https://cloud.githubusercontent.com/assets/20812775/26397659/56051260-4077-11e7-95a7-36e443a02de1.gif)

Concerning **existing planes** you move them during Noncombat Move Phase to the seazone where your carrier will be built a little bit later.

Is that different in your map?

Planes to land on carriers have the `<option name="carrierCost" value="1"/>` coded with them. But I think you know that better than me...

**Comment by FrostionAAA** [comment] 2017-05-24 12:01
I think you are talking about some of the other fighter/carrier options:

- “Land existing fighters on new carriers” (where fighters may non-combat to a sea zone expecting a carrier to be placed so they can land)
- “Produce fighters on carriers” (where newly purchased fighters may be placed along with newly purchased carriers. Like in your animation.)
- “Produce new fighters on old carriers” (where newly purchased fighters may be placed on old carriers that are in a sea zone bordering the factory’s territory)

I am talking about the behavior of "Land existing fighters on new carriers". Both the maps I mention has these settings:
- "Produce fighters on carriers" "true"
- "Produce new fighters on old carriers" "true"
- "Move existing fighters to new carriers" "true"
- "Land existing fighters on new carriers" "false"

If the TripleAs unit placement system can show and let the player choose specific unit types, then I hope it can be done to also let the player chose what fighters are to fly out to the sea zone and land on the newly placed carrier.

**Comment by panther2** [comment] 2017-05-24 13:37
Got it, so your issue is about a fighter movement that occurs after the placement of the new unit.

**Comment by FrostionAAA** [comment] 2017-05-24 14:12
Yes

**Comment by ron-murhammer** [comment] 2017-05-25 22:29
@FrostionAAA This should be implemented once #1755 is merged.

**Comment by FrostionAAA** [comment] 2017-05-25 22:47
Nice! Looking forward to testing it out.

**Comment by Cernelius** [comment] 2017-05-25 23:31
Why the hell no NWO / WAW / TRS players ever complained about this thing??? I've never noticed, cause I never play this kinda stuff.
I just tested it now, and, yes, I see that in World At War, for example, if you have a bunch of existing Fighter and Adv.Fighter you can't decide what to redeploy upon placement, on the Carrier (it just takes first the Adv.Fighter and, then, the Fighter too, but only if not enough Adv.Fighter to redeploy).
Very strange nobody ever raised this issue, all this time. This would not work correctly in any maps having more than 1 unit type able to stay on Carriers, not just NWO etc..

Actually, by correct rules, you should be able to choose to redeploy whatever air able to stay on carrier, not just your own, but also air units of your allies, not only the ones of the same player that placed the carrier, but the engine doesn't allow you to do that, either.
So, it is not just that you can't choose the type, but that you also can't choose the owner, of the air unit.
However, if you will ever correct this bug / limit, as well, I suggest adding 1 property for keeping the current behaviour, and likely add that property to Revised, if people want it, because that is an unsupported rule few people know they can edit and, by now, many custom maps have been made and balanced without that being possible, as ice says.
Like, if you correct this problem too, and make, for example, an Americans fighter able to redeploy on a British carrier (instead of and like a British fighter), immediately when British places it, on the British placement phase, as it should work, I think you should have a property for limiting to the current behaviour, and set this behaviour limited to owned units only in NWO, WAW and TRS, and add this exception to correct Revised rules in notes, as I would not risk to maybe somewhat unbalance them.
I guess @ron-murhammer knows this, since he is a Revised veteran and this is an old Revised rule, that has never been implemented in the engine, thus far.
Personally, aside from this very diverse map, I don't normally like this obsolete Revised rule (already changed in LHTR), since it allows you to move your air of 1 more, during placement, for free, and this doesn't make sense, in my mind; even more confusing since you can move air of your allies too, this way (tho, this is not supported by the engine, as I said). I mean, just referring to the common maps structure here.

**Comment by ron-murhammer** [comment] 2017-05-26 01:12
@Cernelius Yeah, I was kind of surprised by this as well. I think most players forget about this rule of moving fighters to newly built carriers.

"Actually, by correct rules, you should be able to choose to redeploy whatever air able to stay on carrier, not just your own, but also air units of your allies". I've actually never heard that before (also never really thought about it). Are you sure that is the case? Is it in the rules somewhere?

**Comment by Cernelius** [comment] 2017-05-26 14:41
Well, as I said, I wouldn't want you to go ahead and correcting this limit / bug and that's it.
The problem is that a lot of custom games (like NWO) have been made and balanced based on how the engine works; so I surely believe that, if this is de-bugged, the current wrong / limited behaviour should be still possible to be had, with a sub-property.
I mean, I think you should also add a property like this:

"**Redeploy existing fighters owner restricted**"
- This property does nothing if "Move existing fighters to new carriers" is false.
- This property limits what at "Move existing fighters to new carriers" to the air units of the turn player only (not any allies).

And this property should be at least added as true in NWO, TRS and WAW, to keep the behaviour as it is and has always been, unless a bunch of xp players can confirm this "change" would not somehow kill the existing balance (a confirmation we all know we are not getting).
Plus, I should add an explanation about this in WAW notes (that you can't redeploy allies) and I would also add the property as option.

If, like, you would just make the "Move existing fighters to new carriers" work correctly, without anymore the possibility of having the current behaviour, I'm extant to push the matter and I'm not sure if this move would be totally good, just based on how many custom games have been already created with the current behaviour in mind.
I don't actually care myself as, as I said, I don't play nor have maps having this rule, but I'm just fearing that changing this behaviour as per correct rule might be a problem.
Also, while I don't think I would use the rule as a whole, I think this is a bad rule, and the way it works in TA currently is better, because being able to move air units of players outside their turns would be very messy and annoying to calculate / consider, while playing, especially in big maps.
So, you can see I'm not totally sure I want to push for making a rule that I think it would be worse than the current limited / wrong behaviour we have (unless a property is also made for still having it).

Maybe this limited behaviour was specifically intended, based on how messy / strange would be to move someone else air on your turn (tho you can already do something like that for allied air on your carrier).

I don't think I can proof without pasting copyrighted material. But if you still can't manage to see it yourself, let me know I can just send you a mail.
But I'm really not suggesting this if you are not making a sub-property for keeping how it works now, if wanted (of course, not default), also because I think how it works now is better for gameplay, than the correct behaviour (and it is just strange that like the Germans move the Japanese air on its carrier during the Germans turn).

Moreover, and this is very important to, this is a rule made for games in which the only possible relationships were **alliance** and **war**, and never changing, thus **you were sure that if, during your turn, any air was in a territory of yours, those can be only your allies, but this should not be taken as granted, here.** So, you should also be sure that this works only with an "allied" relationship, meaning that both the archetype neutral and war won't allow it, because, in a FFA, you can end up with neutral and even enemy air in the territory you are producing the carrier from, when you downgrade (a map could allow you to downgrade relationship from allied to war).

**Comment by ron-murhammer** [comment] 2017-05-27 17:00
@Cernelius Alright well since no one is reporting or complaining about not being able to move allied fighters to carriers, I'm not planning to make any changes are this for now.

**Closed by ron-murhammer** 2017-05-27 17:00 UTC
Labels: category: game engine > UI, close pending confirmation, type: feature request

**Comment by FrostionAAA** [comment] 2017-05-27 20:47
@ron-murhammer When I test this out it seems to work fine. But I am wondering why the written text is altered so drastically.
![unavngivet](https://cloud.githubusercontent.com/assets/15268177/26524287/32dcb20c-432e-11e7-8638-a70cce9c9ec8.png) 
The old “How many fighters do you want to move from X to new carrier?” is altered to the very short “Choose units” and it is written in a grey colored box.

I would say that the old sentence is way too long, but how about something like “Move air units from X to new carrier?” / “Choose air units to move” / “Choose air units to move to carrier”.

And maybe change the headline “Move fighters to carrier” to state “Move air units to carrier”, as I would think it could also be bombers on many maps. Just my thoughts :-)

**Comment by ron-murhammer** [comment] 2017-05-27 22:41
@FrostionAAA The reason for the change is it actually uses a different code component for the popup (same one as when you click on a territory). I'm not sure if the gray text is customizable currently. I do agree with changing it to "air units" instead of "fighters" and will do that.
