### ISSUE TITLE
Private Hosts Stay Open For Guests When The Hoster Closes (1.9.0.0.3307)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1353] opened 2016-11-26 20:26 UTC
When a host is closed and you are a guest in it, you have still it open and it says you have left too; moreover (and this is the real issue), it seems that it stays up as a process after they close, and you need to kill it with taskmanager. I'm not sure the broken java process is related to this issue or it always happens in this case.
I've never seen something like this before the latest release (1.9.0.0.3266), but I've seen it consistently thereafter.

In the image below, I didn't exit the host on my initiative.

![20161126](https://cloud.githubusercontent.com/assets/19562310/20643053/74d561e4-b41e-11e6-98f7-87389c30f31b.png)

**Comment by DanVanAtta** [comment] 2017-01-09 02:44
I was not able to reproduce this with a simple local hosted game. 

@Cernelius  can you hit this by hosting a game, joining it, and then having the host leave? I am wondering if this is lobby only, or if it requires for the host to crash rather than a simple clean exit.

**Comment by Cernelius** [comment] 2017-01-09 06:27
Haven't joined any other games since them, but I'll see. I think it happened 2 out of 2 times that I did, since the release, but I'm not sure I remember correctly.

If anyone else can tell if it happens or not to them, that would be even better.

**Comment by Cernelius** [comment] 2017-01-09 06:35
Ah, actually, as I said, I was not playing at all there, just guesting. I think it happened to me a couple of times, maybe I was just a guest both times.

I guess it not relevant, but in that game Hard AI was playing, beside 2 or 4 players, don't remember (I think it was a multi of 4 players plus Hard AI).

So, yes, I guess it is not really reproducible, since it happened as I was a guest and didn't happen again to me, while I was guest in several other games for sure, since them.

So, I suggest you unassign me. I can only confirm it didn't happen again under similar conditions.

**Comment by Cernelius** [comment] 2017-01-16 01:13
Had it again when somebody else (elbert70) was hosting and closed when we were waiting for players.

![20170116_02](https://cloud.githubusercontent.com/assets/19562310/21968016/650433fa-db90-11e6-873b-aeec90d29618.png)

But it appears being just a delay maybe, as the game closed after some minutes.

Then, about the other bug off topic, we went on in General_Zod host, and prastle kept disconnecting as soon as placing stuff, this is the chat:

> Cernel:  as I said
> Cernel:  you should bug report that
> Cernel:  telling that prastle disconnected when placing
> elbert70:  not sure how
> Cernel:  and pasting the java log
> elbert70:  ok
> prastle:  would if i got a java error
> Ugly_The_Noob has joined
> General_Zod:  tech?
> General_Zod:  off
> prastle:  ll or dice?
> General_Zod:  dice
> Ugly_The_Noob:  cern
> Cernel:  y?
> Ugly_The_Noob:  what rules are dif from reg revised?
> prastle has left
> Ugly_The_Noob:  omg
> Cernel:  this is v3 rules
> Cernel:  so zod
> Ugly_The_Noob:  what rules is reg revised?
> Cernel:  did you get a java error
> General_Zod:  no errors
> Cernel:  uhm ok
> Cernel:  well, I'm not sure how you should report that
> General_Zod:  lest try to edit the bid in

Then prastle hosted himself, and he didn't bug off anymore.

I'm not reporting this other bug properly, as I've never experienced it, either as a hoster or as a player, but I know it's a recurring bug, and I told people in lobby experiencing it to report it, but I believe nobody did so far.

In general people rarely report bugs, even if instructed to.

**Comment by Cernelius** [comment] 2017-01-16 05:02
Regarding the off topic, I managed to hit it, but I tested that this bug (disconnecting when placing) seems existing only on old versions and not on latest, so should be no problem (not a current bug), as long as using latest engine. This should close this off topic.

**Comment by Cernelius** [comment] 2017-06-05 04:04
It has been a long time since I had this issue, and it appears nobody else is reporting it, either. I let you decide if this can be closed, just because of the long time without anyone affirming to experience anything like this anymore (I surely haven't).

**Comment by Cernelius** [comment] 2017-06-05 04:06
Also, de-assign me, please, I don't know how can I investigate or reproduce this matter.

**Comment by Cernelius** [comment] 2017-06-07 16:48
I see that you now have changed the way this works and now when you are hosted by someone else, and that user closes its host, you have it opened with the notification:

Cernel:  *** Was Disconnected ***

And it stays open till you close it.

I agree with this new behaviour, as it allows you to read what was going on until the moment the host was closed, especially if you were inattentive.

Only thing I would point out is that it would be better if it is written in a form you can't write yourself, like:

***Cernel: was disconnected***

Otherwise one could just write down:

*** Was Disconnected ***

and would look the same.

Also, you might as well be disabled from further posting in the chatroom (currently you still can), as noone would read what you are writing.

So, upon confirmation that this new behaviour is intended (that private hosts stay open for guests when the hoster closes), now I believe this issue can be closed, as I understand now the host is actually meant never to close itself, but just give a disconnection notification in chat, when the hoster closes it on its own end.

**Comment by DanVanAtta** [comment] 2017-08-09 09:00
Couple comments, potentially two updates at play:
1. most obvious, we updated it so on error game clients do not kill the game, allows users some time to save.
2. less obvious, the way a new java process was launched and closed on network games was updated quite a bit for 1.9. That code is really something.. That will probably be fixed by rewriting it so we launch no new processes when a game is started.

I actually suggest we not focus on this bug, instead focus on the rewrite. We suspect we could finish either one with the same effort. If not, the rewrite is at least far more valuable than yet another patch fix.

**Comment by Cernelius** [comment] 2017-08-09 10:15
As I said:

> I agree with this new behaviour, as it allows you to read what was going on until the moment the host was closed, especially if you were inattentive.

I think it is an improvement not having the chat closed on your face as soon as the host is closed or you are disconnected from it; letting the guest close it whenever it wishes to is preferable.

**Comment by Cernelius** [comment] 2017-08-09 10:18
I can't see any actual bugs here anymore, and suggest closing this issue, eventually opening a new one for any other related matters.

> allows users some time to save.

You mean that there is a time limit?

**Comment by DanVanAtta** [comment] 2017-08-10 00:38
> I think it is an improvement not having the chat closed on your face as soon as the host is closed or you are disconnected from it; letting the guest close it whenever it wishes to is preferable.

Chat functionality relies on host connection if I'm not mistaken, options are limited. Gracefully indicating that state and allowing user to save and close seems best and roughly only course of action.


>> allows users some time to save.
> You mean that there is a time limit?

I did not intend to imply an upper bound. Not too long ago it was 'zero', the intent is to allow the user to choose when the game is closed after losing connection to host.

**Comment by DanVanAtta** [comment] 2017-08-10 00:38
> I can't see any actual bugs here anymore, and suggest closing this issue, eventually opening a new one for any other related matters.

sounds good, thanks!

**Closed by DanVanAtta** 2017-08-10 00:38 UTC
Labels: regression, type: bug
