### ISSUE TITLE
NPE during combat with edit mode enabled

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3744] opened 2018-08-07 01:54 UTC
Bug repro:
- start a game, do combat moves to set up some combats
- enable edit mode
- proceed with combats

Notice:
- error message pop-up reporting NPE

Expected:
- no errors

**Comment by DanVanAtta** [comment] 2018-08-08 03:04
We'll need to see if this is a problem in the logs still; the feature is not that we have questionable optionals, but instead we were avoiding/fixing game crashes. The action item here then is 'check logs', a ticket assigned to myself is not appropriate for that.

@ron-murhammer I do understand why you otherwise cut this ticket since we reverted some code, it's a really question fix now and I would personally go back to the original problem we were solving before re-applying (hence the action item is to check logs rather than to resurrect the removed code).

**Comment by DanVanAtta** [comment] 2018-08-08 03:05
The task here is not actually to re-implement #3669, it is in a way, but that would add back in a bug. This probably should be a bug report ticket, I'll update the description to reflect that.

**Comment by DanVanAtta** [comment] 2020-03-11 03:22
Was not able to reproduce this. Perhaps we should require a save-game of bug reports and close them if they get too old and do not have a save game.

**Closed by DanVanAtta** 2020-03-11 03:22 UTC
Labels: Impact: Game Crashing, Problem
