### ISSUE TITLE
URGENT: axisandallies.org is now https only

### ISSUE THREAD

**Issue by djensen47** [triplea-game/triplea#2562] opened 2017-11-02 20:41 UTC
People are experiencing an issue where TripleA is not handling a redirect from http to https for the axisandallies.org forums.

Allowing any http traffic after transitioning to https is going to seriously affect SEO so I would rather not re-enable http.

**Comment by djensen47** [comment] 2017-11-02 21:26
Thanks!

**Comment by ssoloff** [comment] 2017-11-02 21:29
@djensen47 Sent you a message on Gitter regarding some trouble I'm having registering.  Can you please take a look so I can start testing this in a few hours?  Thanks!

**Comment by ssoloff** [comment] 2017-11-02 21:52
> It probably just needs to be modified similar to what ...

Actually, I think I'm making this more difficult than it needs to be.  If axisandallies.org is switching to HTTPS, then we probably just need to update the URL schemes, and leave everything else unchanged.  There will be no HTTP-to-HTTPS redirect in that case.

**Comment by ron-murhammer** [comment] 2017-11-02 21:56
@ssoloff Correct. Please review if you have a few minutes: #2563

**Comment by ssoloff** [comment] 2017-11-02 21:59
Thanks, @ron-murhammer.  We can extract the common base URL to `UrlConstants` in a follow-up PR.

**Comment by ron-murhammer** [comment] 2017-11-02 21:59
@ssoloff Agree. Just did the minimal effort to get it working for now.

**Comment by ron-murhammer** [comment] 2017-11-02 22:06
@djensen47 The PR switching to HTTPS is merged now. A pre-release build should be put out shortly.

**Comment by ron-murhammer** [comment] 2017-11-02 22:19
@djensen47 https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.7378

**Comment by ssoloff** [comment] 2017-11-03 00:07
@djensen47 Just a heads-up when users start using this fix...  If a user has some kind of web content filtering app installed on their machine (e.g. parental controls), they're likely to be unable to post using the new HTTPS URL.  See #2468, #2472, and #2554 for the progress we've made in tracking down the root cause.

Unfortunately, we haven't had a user get all the way through the steps we think are necessary to fix the issue.  Ideally, once we do that, we can provide an FAQ with a recipe users can follow to fix the problem without having to open an issue on GitHub.  Just letting you know in case you start seeing a spike in users reporting an error along the lines of the following:

`sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by djensen47** [comment] 2017-11-06 20:09
Should we close this? It appears to be working.

**Closed** 2017-11-06 20:09 UTC
Labels: category: code, close pending confirmation, type: feature request
