### ISSUE TITLE
New Release is unusable for Lobby 

### ISSUE THREAD

**Issue by Heppisorus** [triplea-game/triplea#3740] opened 2018-08-06 20:47 UTC
.11122

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

![image](https://user-images.githubusercontent.com/30943648/43740118-57ee39b4-9998-11e8-9572-597fe6f509a5.png)

### Instead of this error, what should have happened?

Not this. ;)

**Comment by Heppisorus** [comment] 2018-08-06 21:07
As a follow up question... what would be the last pre-release that would be functional?

Just want to be sure as I am directing people to update their engine based on the game design.

**Comment by ssoloff** [comment] 2018-08-06 21:10
Root cause appears to be due to #3723 trying to format the time as an `Instant` instead of a `LocalDateTime`:

```diff
diff --git a/game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java b/game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
index cbeaeecc8..23b6ffb13 100644
--- a/game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
+++ b/game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
@@ -168,6 +167,7 @@ class LobbyGameTableModel extends AbstractTableModel {
   }
 
   private static String formatBotStartTime(final Instant instant) {
-    return TimeManager.getLocalizedTimeWithoutSeconds(LocalDateTime.ofInstant(instant, ZoneOffset.systemDefault()));
+    return new DateTimeFormatterBuilder().appendLocalized(null, FormatStyle.SHORT).toFormatter()
+        .format(instant);
   }
 }
```

> As a follow up question... what would be the last pre-release that would be functional?

@Heppisorus Try 1.9.0.0.11092.  That was the last build before #3723 was merged.

**Comment by ron-murhammer** [comment] 2018-08-06 21:43
@ssoloff Well, problem is that 11092 has the tile rendering issues but should get around that error but then you can't really play games :)

Looks like we need to revert all or a portion of #3723. Were you gonna take a look at that tonight? Otherwise I can.

**Comment by ssoloff** [comment] 2018-08-06 21:44
@ron-murhammer Was a quick fix.  PR forthcoming.

**Closed** 2018-08-07 00:11 UTC
Labels: Release Blocker, category: bug
