### ISSUE TITLE
How to Deal with Error Reports that are not actually "Error Reports"

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#7824] opened 2020-10-03 06:31 UTC
Branching from #7814, as this would be a meta-discussion and thus inappropriate to continue there.

@tvleavitt said: "Why is this an Error Report at all? We're telling the user exactly what to do, and we know exactly what's wrong already. An Error Report adds no value to the process."

@DanVanAtta responded: "I agree. The problem here is rampant control-flow-by-exception, an anti-pattern. The layer that detects this condition is pretty well below the controlling layer and what makes it complicated is that we rely on an exception being thrown beyond the controlling layer to abort game execution."

In my view, there are two solutions to this:

a) Fix the problem (in the code) by preventing these irrelevant Error Reports from being generated in the first place.

or

b) Fix the problem (the practical impact of these reports in the form of wasted time dealing with them and pollution of the GitHub issues queue) by preventing this specific Error Report from being posted (as we do with duplicate error reports from the same version of a release).

(b) is kind of ugly, but we know the problem exists, and we can create an issue with (a) as the problem to ensure it isn't rendered completely invisible, and we already have precedent for this approach (as cited); let me know if I should file that Bug Report or if you're more equipped to define the problem @DanVanAtta .

Thoughts?

**Comment by DanVanAtta** [comment] 2020-10-03 07:25
In the example raised, we can't fix the root cause without an architecture change. We do have such a change on our roadmap to specifically make it so save game compatibility is not such a burden for everyone:  https://github.com/triplea-game/triplea/issues/7710

https://github.com/triplea-game/triplea/issues/7814 would do well to be in  a bug report stating that the handling of incompatible saves needs to be improved. It is a deeper change though. We require an uncaught exception to kill the new game that is launched and an uncaught exception is always eligible for bug reports. 

Another fix, that we've wanted, is for the game to never spawn new processes. The game is doing a System.exec to launch a a new java whenever you transition from the staging screens to the main game. This is high on the list of things to remove:
- makes debugging way easier
- should not be necessary to do this, questionable resource usage
- requirement for us to be listed on steam. Steam games are not allowed to make System.exec calls.

**Comment by DanVanAtta** [comment] 2020-10-03 07:26
Back to the meta-topic, do we identify as part of a bug report that the problem is just error handling, or perhaps a flavor of error handling, or do we create a new issue to track this? IMO letting the bug report track it keeps the number of issues down and we have context in more or less one place that way. Perhaps we need a label for triage of "bad error handling" and something like "game crash" to differentiate.

**Comment by tvleavitt** [comment] 2020-10-03 18:59
@DanVanAtta My interpretation of the above is that:

a) you've ruled out (b)

b) you've outlined a third option, better labeling of error reports for easier filtering and prioritization

c) (a) is the ultimate goal, but addressing this one concern it not possible without enough engineering that would only be reasonable to pursue in the context of a larger scope

Addressing (a) and (b): my concern is the cumulative cognitive burden that disposition of these ancillary issues puts on developers and other participants; I see a total of 422 messages matching a search for "notifications@github.com" in my Gmail Trash in the last 30 days. That's likely at least an hour a week just evaluating incoming emails and dismissing them as not suitable for further attention. From my perspective, anything that can be done to reduce this is a good thing. We know there is a need for better error handling, we've seen this issue before multiple times, the 3rd or 4th or 5th reminder that it exists provides no value. How many potential developers are going to look at the issue queue and the volume of emails and notifications generated, and decide they don't have the ability to keep up?

**Comment by tvleavitt** [comment] 2020-10-03 19:53
On review (I've been systematically setting up filters in Gmail to reduce and organize the incoming flood), I see that this is a continuation of the discussion in #7065, with somewhat similar non-resolution because we're both very busy. Given the second part of my response above, perhaps this should be retitled, "Reducing the cognitive burden of email generated by TripleA notifications", LOL.

Here's one take: maybe Error Reports generated by TripleA should go into an entirely separate queue, and then developers and other volunteers can periodically review it, and manually replicate important issues to the main queue (this one)? What value do we get out of the 40th report of a MISSING UNIT IMAGE? Perhaps a small amount, in that it shows that this is a widespread and user annoying problem, but no one incident is worthy of specific attention, and clearly the cumulative number of incidents hasn't prompted any code to address them, although we do have my suggestion and @DanVanAtta's concurrence that some kind of tool for map makers allowing them to check for missing unit images would be useful. I don't think we've created a feature request issue yet for that, should I go ahead and do so?

Should we close this issue, reference it in #7065, and continue that discussion there?

**Comment by DanVanAtta** [comment] 2020-10-03 20:35
I am pro: consolidating-similar-issues.

>  What value do we get out of the 40th report of a MISSING UNIT IMAGE

It can be debated. I've been meaning to:
- add an error report count to report uploads that would be visible in the created issues. This way we would get a better sense of impact and it would not be the case that simply unique error messages create a skewed priority
- the error report upload mechanism is still relatively new. We are being flooded. After 2 or 3 more releases I would hope that we would have enough fixes in that we would not be flooded. This is probably going to remain a problem for another 3-6 months at least.

In the short term dealing with the flood needs some attention. I'm personally okay with the email as I do tend to read the ones that come in and getting a few per day is not too bad. Also frequent releases help as the de-dupe is by release number. When we push 2.3, we'll close down all of the 2.2 bug reports and then see what the new reports are. Again, the hope is to rinse-wash & repeat and hopefully by the 2.5 or so release it won't be nearly so bad.

**Comment by DanVanAtta** [comment] 2020-10-03 20:38
I do think we probably should triage the bug reports. I'd propose three buckets (IE: labels):
- bad error handling
- severe (eg: game crashes)
- rare (low frequency)

**Comment by tvleavitt** [comment] 2020-10-03 21:10
> I do think we probably should triage the bug reports. I'd propose three buckets (IE: labels):
> 
> * bad error handling
> * severe (eg: game crashes)
> * triaged (not severe, not bad error handling - presumably low frequency)

I support this as a tangible response to the issue. This is a manual process, right?

The OP, where an error report was generated via an attempt to load an incompatible save game (likely increasingly rare), would definitely be "bad error handling"

Where do the MISSING UNIT IMAGE reports belong? I guess for lack of applicability otherwise, "Bad Error Handling". Could we address this, in the absence of a map validation mechanism, by instead utilizing a generic unit image, something ugly and highly obvious, which would allow the player to continue the game without being flooded with error messages, and prevent us from being flooded with generic error reports? Maybe have some kind of reporting trigger at the end of games that rather than generating an Error Report, adds to some kind of structured server-side log that we can use for reporting purposes, run queries against?

**Comment by tvleavitt** [comment] 2020-10-03 21:24
#7170 is also a related discussion, specific to the issue of MISSING UNIT IMAGE reports, but aspects of it are more general in nature as well.

**Comment by trevan** [comment] 2020-10-04 15:47
> Where do the MISSING UNIT IMAGE reports belong? Is this a "Triage" or a "Bad Error Handling question?

I think "missing unit image" needs to be triaged according to their map.  The same map can cause multiple different missing unit images but they really are all caused by the same thing.  It would also be nice to recognize if the map is a "quality" map.  Anything not in "quality" should probably be ignored or somehow sent to the map maker.

**Comment by trevan** [comment] 2020-10-05 03:10
I just went through all of the missing unit image errors.  The majority of them are not fixable by the engine.  The map itself needs to be fixed.  Only two of them are engine issues and one of those issue probably should be fixed in the map itself (it depends on images that triplea used to include).

**Comment by tvleavitt** [comment] 2020-11-05 02:24
> I just went through all of the missing unit image errors. The majority of them are not fixable by the engine. The map itself needs to be fixed. Only two of them are engine issues and one of those issue probably should be fixed in the map itself (it depends on images that triplea used to include).

Could we eliminate this problem by using a generic default image instead (and just logging the error somewhere other than GitHub)? Or maybe in a separate queue for map errors, so that when a map has a known maintainer (there are a few), the error report can be assigned to them? Or maybe have it automatically post to a dedicated thread on the forums?

**Comment by DanVanAtta** [comment] 2020-11-06 22:29
@tvleavitt I think those are reasonable suggestions. We need to balance priorities though.
I think living with excess missing image errors is okay and fixing as many maps, in the map, where it's legitimate issue will make the best progress. Personally I'm really focused on map-uploads and have put that to the side to start work on deprecating bots. Trevan is quite busy working on fixing up battle calc code and is starting on reworking the save game technology. I think we need to probaby stay focused for the next few months on those fixes which then lead to a more stable system. Perhaps our biggest priority is stability right now, particularly with the bots. Getting rid of the bots in favor of a network bridge would bring a lot of benefit and reduce around 30%-50% of the total yearly project cost.

**Closed** 2021-08-06 02:35 UTC
Labels: Discussion
