### ISSUE TITLE
Japanese Navy

### ISSUE THREAD

**Issue by eeeeeerik** [triplea-game/triplea#1682] opened 2017-05-06 16:40 UTC
Hello, 

Every time I play a game of Axis and Allies World War II Revised and I am playing anyone but Japan the Japanese navy disappears on turn 3 of their offensive move.  It makes beating them very easy but not at all challenging.

Thanks
Erik Hertwig

**Comment by simon33-2** [comment] 2017-05-07 08:54
Steps to reproduce problem? I just tried setting every nation bar USA to "Does Nothing AI" and clicked through to round 4. Japanese fleet still there.

**Comment by panther2** [comment] 2017-05-07 10:37
Can't reproduce it either, please provide a savegame, @eeeeeerik

**Comment by eeeeeerik** [comment] 2017-05-07 11:32
When I set up game I set Russia to fast and all other nations to easy no matter if I pick US, UK, or Germany these are the settings I choose and the Japanese navy disappears turn 3 on their offensive move.

**Comment by panther2** [comment] 2017-05-07 13:36
@eeeeeerik 
Again: Please provide a savegame containing this situation.

**Comment by eeeeeerik** [comment] 2017-05-07 15:04
Ok, 
I cant drop them in chat.  How may I get them to you?

**Comment by panther2** [comment] 2017-05-07 15:50
Just zip the file and try again dropping the zip-file.

**Comment by eeeeeerik** [comment] 2017-05-07 15:56
[NewZipAA.zip](https://github.com/triplea-game/triplea/files/981704/NewZipAA.zip)
I saved three versions of the game.  End of Brits turn 2, End of Brits turn 3, and Start of Brits turn 4.  Japanese ships go missing between Japan and Manchuria.

**Comment by panther2** [comment] 2017-05-07 16:17
Thanks. Now we can take a look. Maybe we can figure out what happened. Stay tuned.

**Comment by panther2** [comment] 2017-05-07 17:39
Thanks again for providing the file. I found out what happened. The error has it's origin in the Japanese Noncombat Move of turn 3 (to be seen when using the history feature with the file `Brit start T4.tsvg.` 

See:
![tra](https://cloud.githubusercontent.com/assets/20812775/25783375/b79f2b74-335b-11e7-8c1c-9ebe9690ed53.PNG)

This error appears to be AI related maybe ( @ron-murhammer ). When loading the file `Brit end T3.tsvg` and setting Japan to `manual` and doing reasonable moves with Japan manually the game continues as normal.

Error log:

```
java.lang.IllegalStateException: Not all units present in:61 Sea Zone.  Trying to remove:[transport owned by Japanese, transport owned by Japanese] present:[transport owned by Japanese]
	at games.strategy.engine.data.changefactory.RemoveUnits.perform(RemoveUnits.java:38)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:501)
	at games.strategy.engine.history.History.gotoNode(History.java:123)
	at games.strategy.triplea.ui.history.HistoryPanel.gotoNode(HistoryPanel.java:262)
	at games.strategy.triplea.ui.history.HistoryPanel.treeSelectionChanged(HistoryPanel.java:252)
	at games.strategy.triplea.ui.history.HistoryPanel.lambda$new$48(HistoryPanel.java:173)
	at javax.swing.JTree.fireValueChanged(Unknown Source)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
	at javax.swing.JTree.setSelectionPath(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:354)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
java.lang.IllegalStateException: Not all units present in:61 Sea Zone.  Trying to remove:[transport owned by Japanese, transport owned by Japanese] present:[transport owned by Japanese]
	at games.strategy.engine.data.changefactory.RemoveUnits.perform(RemoveUnits.java:38)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:501)
	at games.strategy.engine.history.History.gotoNode(History.java:123)
	at games.strategy.triplea.ui.history.HistoryPanel.gotoNode(HistoryPanel.java:262)
	at games.strategy.triplea.ui.history.HistoryPanel.treeSelectionChanged(HistoryPanel.java:252)
	at games.strategy.triplea.ui.history.HistoryPanel.lambda$new$48(HistoryPanel.java:173)
	at javax.swing.JTree.fireValueChanged(Unknown Source)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
	at javax.swing.JTree.setSelectionPath(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:354)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
Thank you for reporting this.

**Comment by panther2** [comment] 2017-05-07 17:52
@eeeeeerik 
Please add which TripleA and Map version you are using. Thank you.

**Comment by eeeeeerik** [comment] 2017-05-07 18:12
Map Version 1.4.1
Engine Version 1.9.0.0.3627

**Comment by ron-murhammer** [comment] 2017-05-08 03:39
Does this only happen with the Easy AI? Human, Fast AI, and Hard AI don't have any issues?

**Comment by panther2** [comment] 2017-05-08 07:20
Starting with the file `Brit end T3.tsvg` I can reproduce the issue only using the Easy AI,

**Comment by ron-murhammer** [comment] 2017-05-08 22:46
@panther2 @eeeeeerik 
There is a bug here which was introduced into Route.java by this PR: https://github.com/triplea-game/triplea/pull/1433/files#diff-d0faf2d176e45d370c31ae9629b5b544

The problem is this particular change where the Easy AI expects the end of the route to be returned as null if it has only 1 territory (route with same beginning and end):
`-    if (m_steps.size() == 0) {
 -      return null;
 +    if (m_steps.isEmpty()) {
 +      return m_start;`

I'll need to either revert this change or modify the Easy AI to handle this Route change. Funny enough I actually commented on the change about it having potentially adverse effects :)

**Comment by ron-murhammer** [comment] 2017-05-09 00:00
This is now fixed with https://github.com/triplea-game/triplea/pull/1692. If you reload from UK turn 2, the Japanese navy will no longer disappear. Closing this issue. Please re-open if you still have problems.

**Closed by ron-murhammer** 2017-05-09 00:00 UTC

**Comment by eeeeeerik** [comment] 2017-05-09 00:52
Do I need to go and down load game again?

**Comment by ron-murhammer** [comment] 2017-05-09 00:55
@eeeeeerik Yeah, you can download a pre-release build here: https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.4205

Eventually we'll update the download on the website.

**Comment by eeeeeerik** [comment] 2017-05-10 03:50
I just noticed the same thing happens during game version 4.
