### ISSUE TITLE
2.6.14525 using Air-Transport An unexpected error occured!

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12013] opened 2023-10-04 08:42 UTC
Using TripleA 2.6.14525
**Map 1941 GCD**
https://drive.google.com/file/d/164EADrFgLICzAElsld3l5WewYarzHAzh/view?usp=sharing

**Saved Game**
[autosaveAfterBattle-J26.zip](https://github.com/triplea-game/triplea/files/12801284/autosaveAfterBattle-J26.zip)

TT Port Moresby Papua
Select Air-Transport
Load 2x Inf-Elite
Fly to Christchurch-S.New Zealand

![image](https://github.com/triplea-game/triplea/assets/71022517/cd710f3a-38e2-4de5-8c0b-f9fb7a9373ef)

**Comment by asvitkine** [comment] 2023-10-05 02:53
Interestingly, just transporting one doesn't error.

**Comment by asvitkine** [comment] 2023-10-05 02:58
The problem is actually that the Convoy in SZ 046 is marked as still transporting one of those units!
So it's thinking that that's the transport rather than the air transport...

So some problem must have happened earlier that resulted in that state.

**Comment by asvitkine** [comment] 2023-10-05 04:50
So, going through game history, it seems the underlying issue (`transportedBy` not cleared from past turns) happens a bunch of times.

Looks like the issue is related to `unloadTransportChange()` not clearing `transportedBy` due to `dependentBattle`. But the `dependentBattle` isn't actually a real battle, it's just taking over an undefended convoy zone.

I think the sz "battle" is the one that's supposed to be clearing the field, but it doesn't do it for some reason.
This seems similar to https://github.com/triplea-game/triplea/issues/4446 except evidently the fix for that didn't cover whatever is different about this case.

**Comment by asvitkine** [comment] 2023-10-06 00:05
Aha, the other fix doesn't work in the cases where the transport isn't marked as participating in the battle (because, say, a sub moved first to do the battle) and so when we go to clear dependents, we only look at units participating in the battle, but not others that were moved in later, but were never added to the battle. Messy!

**Comment by asvitkine** [comment] 2023-10-06 01:42
The issue should be fixed for new games. Unfortunately, the existing save game will still have this issue for some units.

**Closed** 2023-10-06 01:42 UTC
