### ISSUE TITLE
NPE hosting network game in speakerAdded()

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3487] opened 2018-06-28 23:37 UTC
I get the following exception when hosting a game:

ava.lang.NullPointerException
	at games.strategy.engine.chat.Chat$1.speakerAdded(Chat.java:295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:157)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:126)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invoke(UnifiedMessenger.java:149)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:48)
	at com.sun.proxy.$Proxy2.speakerAdded(Unknown Source)
	at games.strategy.engine.chat.ChatController.joinChat(ChatController.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:157)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:126)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:102)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:52)
	at com.sun.proxy.$Proxy1.joinChat(Unknown Source)
	at games.strategy.engine.chat.Chat.<init>(Chat.java:83)
	at games.strategy.engine.chat.ChatPanel.createChatPanel(ChatPanel.java:48)
	at games.strategy.engine.framework.startup.mc.ServerModel.createServerMessenger(ServerModel.java:283)
	at games.strategy.engine.framework.startup.mc.ServerModel.lambda$createServerMessenger$1(ServerModel.java:250)
	at java.util.Optional.map(Optional.java:215)

This is at tip of tree at 06c97c312c46da3997458af86eeef6fcbb8c0961.

**Comment by asvitkine** [comment] 2018-06-28 23:42
The issue is that nodes is still null when the following line is called in Chat ctor:

    final Tuple<Map<INode, Tag>, Long> init = controller.joinChat();

**Comment by RoiEXLab** [comment] 2018-06-29 12:03
Duplicate of #3371
I already tried fixing this issue in a PR, but this caused tests to fail on the build server (worked fine on my machine), so there wasn't much I could effectively do to find the root cause for this.
So if you want to try your luck on this one, go for it.

**Closed by RoiEXLab** 2018-06-29 12:03 UTC
