### ISSUE TITLE
java.lang.IllegalStateException when attempting to show game history

### ISSUE THREAD

**Issue by Grill-Meister** [triplea-game/triplea#1134] opened 2016-08-25 02:01 UTC
I loaded a saved game, clicked on "Show Game History", then clicked on a particular round, and the exception was received.  Stack trace and properties are as follows:

triplea.engine.version.bin:1.9
Loading map: domination_1914_no_mans_land, from: C:\Users\dreyerd\triplea\downloadedMaps\domination_1914_no_mans_land.zip
Loading map: domination_1914_no_mans_land, from: C:\Users\dreyerd\triplea\downloadedMaps\domination_1914_no_mans_land.zip
java.lang.IllegalStateException: Could not set property:uses subject:TriggerAttachment attached to:PlayerID named:Austria with name:triggerAttachmentAustriaP new value:975
    at games.strategy.util.PropertyUtil.set(PropertyUtil.java:17)
    at games.strategy.util.PropertyUtil.set(PropertyUtil.java:32)
    at games.strategy.engine.data.ChangeAttachmentChange.perform(ChangeAttachmentChange.java:75)
    at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
    at games.strategy.engine.data.GameData.performChange(GameData.java:493)
    at games.strategy.engine.history.History.gotoNode(History.java:123)
    at games.strategy.triplea.ui.history.HistoryPanel.gotoNode(HistoryPanel.java:262)
    at games.strategy.triplea.ui.history.HistoryPanel.treeSelectionChanged(HistoryPanel.java:252)
    at games.strategy.triplea.ui.history.HistoryPanel.lambda$new$44(HistoryPanel.java:173)
    at javax.swing.JTree.fireValueChanged(Unknown Source)
    at javax.swing.JTree$TreeSelectionRedirector.valueChanged(Unknown Source)
    at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(Unknown Source)
    at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(Unknown Source)
    at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
    at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
    at javax.swing.JTree.setSelectionPath(Unknown Source)
    at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(Unknown Source)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:156)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@3823699
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at games.strategy.util.PropertyUtil.set(PropertyUtil.java:15)
    ... 53 more
java.lang.IllegalStateException: Not all units present in:Posen.  Trying to remove:[infantry owned by Germany, infantry owned by Germany, infantry owned by Germany, field_gun owned by Germany, infantry owned by Germany, field_gun owned by Germany] present:[]
    at games.strategy.engine.data.changefactory.RemoveUnits.perform(RemoveUnits.java:38)
    at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
    at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
    at games.strategy.engine.data.GameData.performChange(GameData.java:493)
    at games.strategy.engine.history.History.gotoNode(History.java:123)
    at games.strategy.triplea.ui.history.HistoryPanel.gotoNode(HistoryPanel.java:262)
    at games.strategy.triplea.ui.history.HistoryPanel.treeSelectionChanged(HistoryPanel.java:252)
    at games.strategy.triplea.ui.history.HistoryPanel.lambda$new$44(HistoryPanel.java:173)
    at javax.swing.JTree.fireValueChanged(Unknown Source)
    at javax.swing.JTree$TreeSelectionRedirector.valueChanged(Unknown Source)
    at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(Unknown Source)
    at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(Unknown Source)
    at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
    at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
    at javax.swing.JTree.setSelectionPath(Unknown Source)
    at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(Unknown Source)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:156)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
Heap utilization statistics [MB]
Used Memory: 152
Free memory: 354
Total memory: 507
Max memory: 910
SYSTEM PROPERTIES
awt.toolkit sun.awt.windows.WToolkit
exe4j.consoleCodepage cp0
exe4j.isInstall4j true
exe4j.launchName C:\Program Files\TripleA_1.9.0.0.2823\TripleA.exe
exe4j.moduleName C:\Program Files\TripleA_1.9.0.0.2823\TripleA.exe
exe4j.semaphoreName Local\c:_program_files_triplea_1.9.0.0.2823_triplea.exe0
exe4j.tempDir 
exe4j.unextractedPosition 0
file.encoding Cp1252
file.encoding.pkg sun.io
file.separator \
install4j.appDir C:\Program Files\TripleA_1.9.0.0.2823\
install4j.exeDir C:\Program Files\TripleA_1.9.0.0.2823\
install4j.launcherId 33
install4j.swt false
java.awt.graphicsenv sun.awt.Win32GraphicsEnvironment
java.awt.printerjob sun.awt.windows.WPrinterJob
java.class.path C:\Program Files\TripleA_1.9.0.0.2823.install4j\i4jruntime.jar;C:\Program Files\TripleA_1.9.0.0.2823.\bin\triplea.jar
java.class.version 52.0
java.endorsed.dirs c:\program files\java\jre1.8.0_92\lib\endorsed
java.ext.dirs c:\program files\java\jre1.8.0_92\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.home c:\program files\java\jre1.8.0_92
java.io.tmpdir C:\Users\dreyerd\AppData\Local\Temp\1\
java.library.path C:\ProgramData\Oracle\Java\javapath;C:\Oracle\Client_11_2_1\bin;c:\oracle\product\11.2.0\client_1;c:\oracle\product\11.2.0\client_1\bin;C:\Program Files (x86)\Support Tools\;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Sybase\Shared\PowerBuilder\;C:\Program Files (x86)\Sybase\SQL Anywhere 9\win32;C:\Program Files (x86)\Sybase\Shared\win32;C:\Program Files (x86)\Sybase\Shared\Sybase Central 4.3\win32;C:\Program Files (x86)\Sybase\Shared\Web Targets;C:\Program Files (x86)\Sybase\Shared\DataDirect;C:\Program Files (x86)\Sybase\Shared\DataDirect52;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;;c:\program files\java\jre1.8.0_92\bin
java.net.useSystemProxies true
java.runtime.name Java(TM) SE Runtime Environment
java.runtime.version 1.8.0_92-b14
java.specification.name Java Platform API Specification
java.specification.vendor Oracle Corporation
java.specification.version 1.8
java.vendor Oracle Corporation
java.vendor.url http://java.oracle.com/
java.vendor.url.bug http://bugreport.sun.com/bugreport/
java.version 1.8.0_92
java.vm.info mixed mode
java.vm.name Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name Java Virtual Machine Specification
java.vm.specification.vendor Oracle Corporation
java.vm.specification.version 1.8
java.vm.vendor Oracle Corporation
java.vm.version 25.92-b14
line.separator 

os.arch amd64
os.name Windows 7
os.version 6.1
path.separator ;
sun.arch.data.model 64
sun.awt.enableExtraMouseButtons true
sun.awt.exception.handler games.strategy.triplea.ui.ErrorHandler
sun.boot.class.path c:\program files\java\jre1.8.0_92\lib\resources.jar;c:\program files\java\jre1.8.0_92\lib\rt.jar;c:\program files\java\jre1.8.0_92\lib\sunrsasign.jar;c:\program files\java\jre1.8.0_92\lib\jsse.jar;c:\program files\java\jre1.8.0_92\lib\jce.jar;c:\program files\java\jre1.8.0_92\lib\charsets.jar;c:\program files\java\jre1.8.0_92\lib\jfr.jar;c:\program files\java\jre1.8.0_92\classes
sun.boot.library.path c:\program files\java\jre1.8.0_92\bin
sun.cpu.endian little
sun.cpu.isalist amd64
sun.desktop windows
sun.io.unicode.encoding UnicodeLittle
sun.java.command C:\Program Files\TripleA_1.9.0.0.2823\TripleA.exe
sun.jnu.encoding Cp1252
sun.management.compiler HotSpot 64-Bit Tiered Compilers
sun.os.patch.level Service Pack 1
triplea.engine.version.bin 1.9
user.country US
user.dir C:\Program Files\TripleA_1.9.0.0.2823
user.home C:\Users\dreyerd
user.language en
user.name dreyerd
user.script 
user.timezone America/New_York
user.variant

**Comment by DanVanAtta** [comment] 2016-08-25 03:01
Would you mind putting the save game in a zip and attaching it to this issue, and indicating which round throws the error?  

This part looks like it might be a problem with the XML:
```
java.lang.IllegalStateException: Could not set property:uses subject:TriggerAttachment attached to:PlayerID named:Austria with name:triggerAttachmentAustriaP new value:975
```
But this look likes a problem with the engine:
```
java.lang.IllegalStateException: Not all units present in:Posen. Trying to remove:[infantry owned by Germany, infantry owned by Germany, infantry owned by Germany, field_gun owned by Germany, infantry owned by Germany, field_gun owned by Germany] present:[]
```

**Comment by RoiEXLab** [comment] 2016-08-25 12:31
@DanVanAtta I can reproduce such a scenario on classic WW II 3rd:
See https://gist.github.com/RoiEXLab/117400150f37943d7e625c75547af6fe
No specific savegame needed... Just start it with all players set to human and try to click something in the histroy tab...

**Comment by Grill-Meister** [comment] 2016-08-25 14:44
I tried the workaround of loading and setting all players to human, but still received an exception with the following stack trace.  I've attached the savegame.  Any round creates the error.
[autosave_1134.zip](https://github.com/triplea-game/triplea/files/437299/autosave_1134.zip)

triplea.engine.version.bin:1.9
Loading map: domination_1914_no_mans_land, from: C:\Users\dreyerd\triplea\downloadedMaps\domination_1914_no_mans_land.zip
Loading map: domination_1914_no_mans_land, from: C:\Users\dreyerd\triplea\downloadedMaps\domination_1914_no_mans_land.zip
java.lang.IllegalStateException: Could not set property:uses subject:TriggerAttachment attached to:PlayerID named:Austria with name:triggerAttachmentAustriaP new value:975
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:17)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:32)
	at games.strategy.engine.data.ChangeAttachmentChange.perform(ChangeAttachmentChange.java:75)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:493)
	at games.strategy.engine.history.History.gotoNode(History.java:123)
	at games.strategy.triplea.ui.history.HistoryPanel.gotoNode(HistoryPanel.java:262)
	at games.strategy.triplea.ui.history.HistoryPanel.treeSelectionChanged(HistoryPanel.java:252)
	at games.strategy.triplea.ui.history.HistoryPanel.lambda$new$44(HistoryPanel.java:173)
	at javax.swing.JTree.fireValueChanged(Unknown Source)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
	at javax.swing.JTree.setSelectionPath(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:156)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@5554127b
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:15)
	... 53 more

**Comment by RoiEXLab** [comment] 2016-08-25 15:47
@Grill-Meister 

> I tried the workaround of loading and setting all players to human, but still received an exception with the following stack trace. I've attached the savegame. Any round creates the error.

You misunderstood something there... While all players are set to human I can reproduce the error - it happens in this case!

**Comment by DanVanAtta** [comment] 2016-08-26 05:28
The bottom of the stack trace looks to have the root cause:
`Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@5554127`

**Comment by DanVanAtta** [comment] 2016-08-29 04:05
How consistent is this? I could not repro.. Any tips for hitting the problem?

**Comment by DanVanAtta** [comment] 2016-12-16 22:39
@Grill-Meister  - please re-open if you can still hit this problem (and if you could attach a new stack trace/error message and save game, that would be perfect)

Looking at the code, I did not see any obvious reasons for why we would be getting this error. It *could* maybe be due to a XML problem using an unknown 'uses' property. 

Regardless, the save game attached above no longer loads. Since I'm unable to repro, or find where this problem is in code, will close this issue for now.

**Closed by DanVanAtta** 2016-12-16 22:39 UTC
Labels: Bug Backlog
