### ISSUE TITLE
Allow isInfrastructure unit to attacking with only AA attack to last for multiple rounds

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1966] opened 2017-06-23 16:50 UTC
**Description:**
There seems to be a problem if a land unit uses only AA attack (no matter what the unit or AA attack is named), has isInfrastructure true, and can attack move into combat. The unit seems to only fire once even though it is set to infinite rounds. If the same unit is defending, everything works, but just not when attacking.

Here is a test xml with a setup that can be tested (mod of xml in world_war_ii_classic-master.zip):
[text-XML-for-world_war_ii_classic-master.zip](https://github.com/triplea-game/triplea/files/1098462/text-XML-for-world_war_ii_classic-master.zip)

Here is the AA unit used in the XML testing:
```
        <attachment name="unitAttachment" attachTo="aaGun" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
            <option name="isInfrastructure" value="true"/>
                <option name="attackAA" value="1"/>
                <option name="offensiveAttackAA" value="1"/>
                <option name="maxAAattacks" value="1"/>
                <option name="maxRoundsAA" value="-1"/>
                <option name="isAAforCombatOnly" value="true"/>
                <option name="isAAforBombingThisUnitOnly" value="false"/>
                <option name="isAAforFlyOverOnly" value="true"/>
                <option name="mayOverStackAA" value="true"/>
            <option name="transportCost" value="1"/>
            <option name="movement" value="1"/>
        </attachment>
```
 
**Example 1 (Works):**
Russia attacks with Infantry and fighter. The German aaGun shoots its 1 every round, as long as enemy fighter lives and as long as USSR units are also alive.
![unavngivet](https://user-images.githubusercontent.com/15268177/27491924-870b8d6e-5844-11e7-8995-5cc7ffe726c5.png)
![unavngivet2](https://user-images.githubusercontent.com/15268177/27491928-8b4c2b9a-5844-11e7-8c8f-3f7083e53cf9.png)

**Example 2 (Bug):**
Russia attacks with Infantry and aaGun. The Russian aaGun should be attacking in infinite rounds, as long as there is a German fighter. But the Russian aaGun only shoots once and is not displayed either. In second battle round there is no more “Russians AA fire”.

![unavngivet3](https://user-images.githubusercontent.com/15268177/27491946-98b191c6-5844-11e7-92c5-5407d4a23865.png)
![unavngivet4](https://user-images.githubusercontent.com/15268177/27491947-9c3ed182-5844-11e7-91e7-ccdbecaf83df.png)

Forum diskussion here:
https://forums.triplea-game.org/topic/154/aa-gun-only-attacking-once-on-offence-help

**Comment by Cernelius** [comment] 2017-06-24 09:51
I'll add that (until a developer solves) you can hack around this bug using a support 0 to itself, that keeps the unit in combat.

**Comment by ron-murhammer** [comment] 2017-06-24 19:19
@FrostionAAA @Cernelius So I have an initial PR to fix this by updating a filter that always removed isInfra units that had no support or combat values to include a get for combat AA. Once that is merged, I'd appreciate testing on a variety of maps especially any you know of that have different types of infra units that can attack to see if it works as intended or if there are any unintended side effects.

**Comment by FrostionAAA** [comment] 2017-06-24 19:40
Well I know of Iron War and Dragon War. I will be happy to test it out on those maps.

**Closed** 2017-08-14 20:58 UTC
Labels: category: game engine > game rules, close pending confirmation, type: feature request
