### ISSUE TITLE
Bug trying to move transport

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1479] opened 2017-01-21 00:42 UTC
[ErrorMovingTransport.zip](https://github.com/triplea-game/triplea/files/720797/ErrorMovingTransport.zip)

Thought I'd report this. One transport has already moved from SZ89 to SZ101 and back. If you try moving the second transport from SZ89 to SZ101 as soon as the mouse enters SZ101 the Triple-A error console appears and the mouse movement is blocked.

Worked around this by undoing the move and moving both transports together. Thought I'd report it though.

**Comment by ron-murhammer** [comment] 2017-05-31 05:05
@simon33-2 That problem appears to occur when edit mode was used in round 6 during UK combat move to move the US transport from sz91 to sz89. After that, the transport is bugged and any time you try to move it then you get an error. I don't see how you worked around this error as I undid all moves on the USA turn and tried moving both transports then still get the error.

**Comment by ron-murhammer** [comment] 2017-06-01 00:06
@simon33-2 I'm not able to reproduce the issue with the bugged unit referring to the wrong game data. I tried loading before the editing and redoing it but it works fine.

Closing this as we are unable to reproduce it. Please re-open if you run into it again.

**Closed by ron-murhammer** 2017-06-01 00:06 UTC
Labels: type: bug
