### ISSUE TITLE
MacOS Map scroll bug

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#3324] opened 2018-03-27 20:21 UTC
### Engine version
9824 up to 9925
### My Operating System
MacOS High Sierra 10.13.3
### Map name
NWO, WW2 Europe 1940 original
Any map that should have no connection left to right.
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Mouse on the map, use two finger scroll to go to right edge of map, you jump to left edge of map.
It's not a smooth scroll as in a world map, you kinda get warped over instantly.
Left to right is normal, you don't jump.
### Instead of this error, what should have happened?
You don't jump

**Comment by DanVanAtta** [comment] 2018-03-27 21:04
Closing, duplicate of: https://github.com/triplea-game/triplea/issues/3280

(@ZjelcoP thanks for submitting, this is a pretty bad bug it turns out, makes Civil War almost unplayable on a Mac because you can't view the right hand edge of the screen without it jumping around).

FWIW I found we can repro this problem by holding shift and using the mousewheel to scroll, you'll get a left/right scroll and can observe same behavior.

**Closed by DanVanAtta** 2018-03-27 21:04 UTC

**Comment by ZjelcoP** [comment] 2018-03-27 21:13
Ah, well i checked all issues with bug label, didn't see it there.

**Comment by DanVanAtta** [comment] 2018-03-28 00:40
I suppose this should be considered a bug since the wrapping is on one side and not the other. I'll add the bug label to that issue.
