### ISSUE TITLE
Route Drawer Of Units Unable To Reach Bug (1.9.0.0.2965)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#1150] opened 2016-08-28 01:49 UTC
BugReportCernel14_Napoleonic Empires: FFA 8 Player_02_1.9.0.0.2965_20160828

In "Napoleonic Empires: FFA 8 Player", skipping all Politics, on France Combat Move round 1, when trying to move all units in Picardy to Cologne (only the Dragoons can move there), the route drawer bugs off and you receive this error (it is related to the units you selected having not enough movement, as the error doesn't happen if all units have enough movement to reach the target territory):

https://gist.github.com/Cernelius/1ff243b3c07cd9b34b3ce159d926f2f5

**Comment by ron-murhammer** [comment] 2016-08-28 15:45
@Cernelius Yeah I reproduced this error. Both this and #1151 appear to be the same underlying issue. The issue seems to stem from the changes to route drawing to fix infinite scrolling maps. I think any non-infinite scrolling map (Nap, 270 BC, Great War, etc) are affected by this bug.

**Comment by Cernelius** [comment] 2016-08-28 16:05
The main thing is that I think this proves the prerelease gets very little testing. I discovered this because I was updating a mod of mine to the new changes (Impassable etc.). This, for example, means that not a single user playtested 1 not-infinite scrolling map as of late.
Maybe you should close my other issue, if it is the same thing.

**Comment by RoiEXLab** [comment] 2016-08-28 17:57
I only have a couple hours left... I see what I can do, shouldn't be that difficult to fix

**Comment by RoiEXLab** [comment] 2016-08-28 17:59
Ohh I know what the issue is now... I should have fixed this in a couple minutes... Hold on

**Comment by RoiEXLab** [comment] 2016-08-28 18:08
#1153 should Fix this error

**Comment by RoiEXLab** [comment] 2016-08-28 18:21
@ron-murhammer @Cernelius could somebody confirm, that this error was resolve by the latest PR? Not sure on how to follow the reproducing steps exactly ^^ too complicated too me, since I'm mainly playing classic WW II

**Comment by Cernelius** [comment] 2016-08-28 18:44
Skipping all Politics just means you skip all politic phases, doing nothing on them but clicking done.

**Comment by RoiEXLab** [comment] 2016-08-28 18:51
Ok that's what I did...
Can you confirm that this error is no longer happening? 
If so, please close this issue

**Comment by Cernelius** [comment] 2016-08-28 19:19
The 1.9.0.0.2980 doesn't look like a true prerelease. Am I supposed to download the zip?

**Comment by RoiEXLab** [comment] 2016-08-28 19:22
No, looks like we have a problem there.
@ron-murhammer looks like we have a building problem

**Comment by Cernelius** [comment] 2016-08-28 19:45
And why did you remove bug backlog?

**Comment by DanVanAtta** [comment] 2016-08-28 20:50
> "The 1.9.0.0.2980 doesn't look like a true prerelease. Am I supposed to download the zip?"

No, the travis build failed to push artifacts to github. That happens occasionally, we push a lot of data on each release.

> "And why did you remove bug backlog?"

Backlog is a list of items to do in the future. 'next release' effectively means we have picked this off of the backlog and are doing it now.

**Comment by RoiEXLab** [comment] 2016-08-28 20:52
@Cernelius I believe this I just to mark this issue as resolved until we know more...
@DanVanAtta Any ideas why the automatic deployment is not working?

**Comment by Cernelius** [comment] 2016-08-28 21:09
Then better having 2 labels: "Bug" and "Backlog"; so you can remove the "Backlog" and keep it classified as "Bug".

**Comment by RoiEXLab** [comment] 2016-08-28 22:04
So @Cernelius are you able to reproduce?

**Comment by Cernelius** [comment] 2016-08-28 22:33
OMG. Where's the all platform? The others suck, all distorted and blurred in my PC.

**Comment by Cernelius** [comment] 2016-08-28 22:40
Haven't tried them in a while, tho. So, downloading the installer. Eventually I may just download the new jar and paste it, I guess.

**Comment by Cernelius** [comment] 2016-08-28 23:26
Ok, I confirm this can be closed, but I hope you have not removed the all platform, because the installer is all messed up.

**Comment by DanVanAtta** [comment] 2016-08-29 02:36
> "because the installer is all messed up."

Please open an issue to describe what you are seeing, screenshots are very helfpul too.

We have a lot of different OS's, system configs etc.. It's valuable to know what is different on your system so we can look to reproduce and fix it.

**Closed by DanVanAtta** 2016-08-29 02:36 UTC
Labels: Close Pending Confirmation, Next Release
