### ISSUE TITLE
Americans AI stuck in combat. Game won't proceed. 

### ISSUE THREAD

**Issue by zared619** [triplea-game/triplea#2663] opened 2017-11-30 05:49 UTC
### Instead of this error, what should have happened? The game should proceed
[Axis on easy.zip](https://github.com/triplea-game/triplea/files/1516660/Axis.on.easy.zip)

**Comment by ssoloff** [comment] 2017-12-01 17:39
Confirmed I can reproduce this on 1.9.0.0.7667.

Breaking in with the debugger during the "frozen" American combat phase, the "Triplea start thread" stack trace is

```
Thread [Triplea start thread] (Suspended)	
	String.intern() line: not available [native method]	
	Class<T>.searchMethods(Method[], String, Class<?>[]) line: 3003	
	Class<T>.privateGetMethodRecursive(String, Class<?>[], boolean, MethodArray) line: 3048	
	Class<T>.getMethod0(String, Class<?>[], boolean) line: 3018	
	Class<T>.getMethod(String, Class<?>...) line: 1784	
	EndPoint.invokeSingle(RemoteMethodCall, Object, INode) line: 156	
	EndPoint.invokeMultiple(RemoteMethodCall, INode) line: 146	
	EndPoint.invokeLocal(RemoteMethodCall, long, INode) line: 132	
	UnifiedMessenger.invokeAndWait(String, RemoteMethodCall) line: 103	
	UnifiedInvocationHandler.invoke(Object, Method, Object[]) line: 51	
	$Proxy8.fightBattle(Territory, boolean, IBattle$BattleType) line: not available	
	GeneratedMethodAccessor67.invoke(Object, Object[]) line: not available	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	DefaultPlayerBridge$GameOverInvocationHandler.invoke(Object, Method, Object[]) line: 154	
	$Proxy8.fightBattle(Territory, boolean, IBattle$BattleType) line: not available	
	WeakAI(AbstractAI).battle(IBattleDelegate, GameData, PlayerID) line: 586	
	WeakAI(AbstractAI).start(String) line: 478	
	ServerGame.waitForPlayerToFinishStep() line: 524	
	ServerGame.runStep(boolean) line: 410	
	ServerGame.startGame() line: 266	
	LocalLauncher.launchInNewThread(Component) line: 61	
	LocalLauncher(AbstractLauncher).lambda$0(Component) line: 51	
	173862863.run() line: not available	
	Thread.run() line: 748	
```

Stepping through a bit more, it appears the engine is stuck in the infinite loop within `AbstractAI#battle()`:

```java
protected void battle(final IBattleDelegate battleDelegate, final GameData data, final PlayerID player) {
  // generally all AI's will follow the same logic.
  // loop until all battles are fought.
  // rather than try to analyze battles to figure out which must be fought before others
  // as in the case of a naval battle preceding an amphibious attack,
  // keep trying to fight every battle
  while (true) {
    final BattleListing listing = battleDelegate.getBattles();
    if (listing.isEmpty()) {
      return;
    }
    for (final Entry<BattleType, Collection<Territory>> entry : listing.getBattles().entrySet()) {
      for (final Territory current : entry.getValue()) {
        final String error = battleDelegate.fightBattle(current, entry.getKey().isBombingRun(), entry.getKey());
        if (error != null) {
          logger.fine(error);
        }
      }
    }
  }
}
```

Both the battle in the Arabian Peninsula and Iraq are returning the error "Must finish Battle in France first".  Thus, those battles never get removed from the battle list, and the engine never exits the infinite loop.

The root cause of the infinite loop probably has something to do with why the UK battle in France was never marked as complete.  That's going to require a bit more digging.

**Comment by ron-murhammer** [comment] 2017-12-01 23:45
@ssoloff I'm pretty sure there is a problem with this save game. Most likely either it was corrupted or it is from the battle calc bug that was fixed. If you run the USA turn with Hard AI then you get a different error that indicates the game data is most likely corrupted:

`SEVERE: 2 Battle results workers aborted by exception
java.lang.IllegalStateException: Duplicate Units Detected: Original List:[artillery owned by Americans, artillery owned by Americans, infantry owned by Americans, infantry owned by Americans]  HashSet:[artillery owned by Americans, infantry owned by Americans, infantry owned by Americans]
	at games.strategy.triplea.delegate.DiceRoll.rollDiceNormal(DiceRoll.java:956)
	at games.strategy.triplea.delegate.DiceRoll.rollDice(DiceRoll.java:373)
	at games.strategy.triplea.delegate.Fire.rollDice(Fire.java:90)
	at games.strategy.triplea.delegate.Fire.access$000(Fire.java:22)
	at games.strategy.triplea.delegate.Fire$1.execute(Fire.java:214)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:41)
	at games.strategy.triplea.delegate.MustFightBattle.fight(MustFightBattle.java:384)
	at games.strategy.triplea.oddsCalculator.ta.OddsCalculator.calculate(OddsCalculator.java:193)
	at games.strategy.triplea.oddsCalculator.ta.OddsCalculator.calculate(OddsCalculator.java:163)
	at games.strategy.triplea.oddsCalculator.ta.OddsCalculator.call(OddsCalculator.java:208)
	at games.strategy.triplea.oddsCalculator.ta.OddsCalculator.call(OddsCalculator.java:55)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by ssoloff** [comment] 2017-12-05 04:11
@ron-murhammer I think I see what you mean.  Something happened to get the battle in France on the battle list twice.  Looking through the entire history, I don't see any other UK battles in France, so I'm guessing the corruption occurred in the current round (14).

The attached save appears to have been produced after the battle in Calcutta but before the battle in France.  I wonder if saving at that point and possibly reloading later to continue the game caused the corruption?

@zared619 It's not clear what the root cause of the corruption is in your save game.  However, as a workaround, I was able to use the **Save Game at this point (BETA)** feature to go back to the beginning of the UK's turn in round 14, reproduce the same moves you originally made, and the battle in France didn't trigger the duplicate battle error.  Continuing on in that round, I confirmed the USA did not get stuck during its combat phase, and its turn ended normally.  That may be the best we can do to help you without additional information to reproduce the save game corruption.

**Comment by ssoloff** [comment] 2017-12-05 04:19
Based on what I postulated above, I tried that scenario to see if I could reproduce the corruption:

1. Load the save game I mentioned above using **Save Game at this point (BETA)** (changing all players to Human).
1. Reproduce UK's moves through the Combat Move phase.
1. Run battle in Calcutta to completion.
1. Save game at this point.
1. Leave and load the save game created in the previous step.
1. Run battle in France to completion.

At the end of the battle in France, the Error Console was _not_ displayed with the message about a pending battle not in the battle list as with the original save game.  So my theory from my previous comment didn't seem to go anywhere. 😞

**Comment by zared619** [comment] 2017-12-05 06:11
@ssoloff Sorry I can't really provide more info. I just started using the game last week and I ran into this issue on my first single player experience. I figured I would report it so if it was a bug, then someone could take a look at it and get it fixed. If it somehow got corrupted, then maybe it's in the code that creates the save instance?

I'm not really sure how it could have gotten corrupted.

**Comment by ssoloff** [comment] 2017-12-05 17:21
> I figured I would report it so if it was a bug, then someone could take a look at it and get it fixed.

@zared619 Bug reports are always appreciated, even if we can't fix them. :smile:

<hr>

I debugged this a bit further.  The key seems to be figuring out how to trigger the `BattleExtendedDelegateState#m_currentBattle` field to be non-`null` when saving.  In the OP's save game, this field is non-`null` during deserialization (and refers to the battle in France), which causes `BattleDelegate#m_currentBattle` to be non-`null` when the game is loaded.  However, none of the code that resets `BattleDelegate#m_currentBattle` to `null` is ever run (e.g. in `BattleDelegate#fightCurrentBattle()` and `BattleDelegate#fight()`).  The fact that `m_currentBattle` is non-`null` at the end of the battle in France is what causes the "battle is not on the pending list" error to occur.

I tried saving a game at various points during the combat phase both when a battle is and is not in progress.  Unfortunately, I was never able to get the `BattleExtendedDelegateState#m_currentBattle` to be non-`null` in the save game.

<hr>

@zared619 Let me ask you two more questions:

1. What version of TripleA were you using when you created the save game?  This is displayed in the upper-left corner of the main screen after the label "Engine Version".  From the save game, it appears it is version 1.9.0.0.7527, but I just want to confirm that.
1. Do you remember exactly where you were in the game when you created the save you attached to this issue?  It appears you saved it immediately before Germany had to select casualties from UK naval bombardment in France, but I want to make sure that matches your recollection.

**Comment by zared619** [comment] 2017-12-07 00:41
@ssoloff I am using version 1.9.0.0.7527. I don't remember the exact spot unfortunately. I just know it was on Germany's turn.

**Comment by ssoloff** [comment] 2017-12-08 02:00
So, 1.9.0.0.7527 was the release that was withdrawn due to data corruption issues caused by the battle calculator changes in #2540.  However, I thought we isolated that bug to only affecting the Hard AI.  I double-checked and couldn't find any way that the Fast (Easy) AI could have triggered that bug (which might nicely explain why we can no longer reproduce this issue).

@ron-murhammer Can you confirm that the Fast AI does not depend on `GameData`, and thus could not have been affected by #2540 not cloning it?

**Comment by ron-murhammer** [comment] 2017-12-08 02:03
@ssoloff I think you mean Weak AI which is Easy AI not Fast AI. Both Hard AI and Fast AI are potentially affected by the battle calc bug but Easy AI shouldn't be.

**Comment by ssoloff** [comment] 2017-12-08 02:16
@ron-murhammer Derp.  Yes, thanks for the correction.  I should have been looking at the Weak AI classes.  (But, in reality, I wasn't able to find where not cloning `GameData` would affect Fast AI, which is why I'm glad I asked you anyway. :smile:)

Once again, I'm not really sure where to go with this issue due to lack of reproducibility.  I'm going to go ahead and close it.  @zared619 Please re-open or submit a new issue if you encounter this problem again in 1.9.0.0.7621 or later.

**Closed by ssoloff** 2017-12-08 02:16 UTC
Labels: category: code, type: bug
