### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by llfletch** [triplea-game/triplea#4798] opened 2019-03-28 18:43 UTC
### Engine version

TripleA-1.9.0.0.13066

### My Operating System
Windows 10

### Map name
Any Map

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Launch the game.

Then 
1) Open a save game.
2) Start the game.
3) Leave the game (quit to main menu).

If I repeat the 3 steps enough times (usually 4-5 times, but it may be more sometimes) it will trigger the error.
Basically there is a memory leak and the program runs out of memory.

### Do you have the exact error text? Please copy/paste if so
No, sometimes it fails to load, sometimes it overloads the GC (I think that is the Global Cache). There is a third, memory related error, but I don't remember it.

### Instead of this error, what should have happened?
The program shouldn't run out of memory.

### Any additional information that may help
Part of the problem may be loading the sound files more than once.

[Loren5.zip](https://github.com/triplea-game/triplea/files/3019661/Loren5.zip)

**Comment by RoiEXLab** [comment] 2019-03-31 14:48
So I tried reproducing this in a Profiler. Here's the result:
```
Mär 31, 2019 4:25:56 PM games.strategy.engine.framework.GameRunner lambda$start$0
SCHWERWIEGEND: Java heap space
java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:76)
    at java.awt.image.Raster.createInterleavedRaster(Raster.java:266)
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:391)
    at games.strategy.ui.Util.createImage(Util.java:60)
    at games.strategy.triplea.ui.screen.Tile.<init>(Tile.java:40)
    at games.strategy.triplea.ui.screen.TileManager.createTiles(TileManager.java:172)
    at games.strategy.triplea.ui.MapPanel.recreateTiles(MapPanel.java:237)
    at games.strategy.triplea.ui.MapPanel.lambda$new$3(MapPanel.java:203)
    at games.strategy.triplea.ui.MapPanel$$Lambda$1230/2134588216.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

Mär 31, 2019 4:26:09 PM games.strategy.engine.framework.GameRunner lambda$start$0
SCHWERWIEGEND: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at org.pushingpixels.substance.internal.widget.menu.MenuSearchWidget$SearchPanel.<init>(MenuSearchWidget.java:132)
    at org.pushingpixels.substance.internal.widget.menu.MenuSearchWidget.installUI(MenuSearchWidget.java:499)
    at org.pushingpixels.substance.internal.ui.SubstanceMenuBarUI.installUI(SubstanceMenuBarUI.java:74)
    at javax.swing.JComponent.setUI(JComponent.java:666)
    at javax.swing.JMenuBar.setUI(JMenuBar.java:144)
    at javax.swing.JMenuBar.updateUI(JMenuBar.java:153)
    at javax.swing.JMenuBar.<init>(JMenuBar.java:121)
    at games.strategy.triplea.ui.menubar.TripleAMenuBar.<init>(TripleAMenuBar.java:32)
    at games.strategy.triplea.ui.TripleAFrame.lambda$new$4(TripleAFrame.java:276)
    at games.strategy.triplea.ui.TripleAFrame$$Lambda$1221/1897867897.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Mär 31, 2019 4:26:12 PM games.strategy.engine.framework.GameRunner lambda$start$0
SCHWERWIEGEND: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
    at java.lang.StringBuilder.append(StringBuilder.java:136)
    at javax.swing.plaf.basic.BasicButtonUI.installDefaults(BasicButtonUI.java:111)
    at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.installDefaults(SubstanceButtonUI.java:216)
    at javax.swing.plaf.basic.BasicButtonUI.installUI(BasicButtonUI.java:88)
    at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.installUI(SubstanceButtonUI.java:193)
    at javax.swing.JComponent.setUI(JComponent.java:666)
    at javax.swing.AbstractButton.setUI(AbstractButton.java:1810)
    at javax.swing.JButton.updateUI(JButton.java:147)
    at javax.swing.AbstractButton.init(AbstractButton.java:2176)
    at javax.swing.JButton.<init>(JButton.java:137)
    at javax.swing.JButton.<init>(JButton.java:91)
    at javax.swing.JButton.<init>(JButton.java:122)
    at games.strategy.triplea.ui.EditPanel.<init>(EditPanel.java:512)
    at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:406)
    at games.strategy.triplea.ui.TripleAFrame.lambda$create$0(TripleAFrame.java:237)
    at games.strategy.triplea.ui.TripleAFrame$$Lambda$1213/1052835221.get(Unknown Source)
    at games.strategy.ui.SwingAction.lambda$invokeAndWaitResult$1(SwingAction.java:114)
    at games.strategy.ui.SwingAction$$Lambda$13/99550389.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)

Mär 31, 2019 4:26:15 PM games.strategy.engine.framework.GameRunner lambda$start$0
SCHWERWIEGEND: Java heap space
java.lang.OutOfMemoryError: Java heap space

Mär 31, 2019 4:26:17 PM games.strategy.engine.framework.GameRunner lambda$start$0
SCHWERWIEGEND: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
```
SCHWERWIEGEND means SEVERE btw.

I'll try figuring out the root cause.

**Comment by ron-murhammer** [comment] 2019-03-31 16:11
@RoiEXLab Probably if you just take a heap dump, it should hopefully be obvious what we aren't cleaning up after each time a game is quit.

**Comment by RoiEXLab** [comment] 2019-03-31 16:17
@ron-murhammer Well you are correct to say that we aren't cleaning up, however I realized that any TripleAFrame (the root JFrame of any game) is never garbage collected at all, and thus all of the tiles etc. are never garbage collected either.

**Comment by ron-murhammer** [comment] 2019-03-31 16:18
Interesting. Wonder if its always been that way or we made an update at some point to cause that?

**Comment by RoiEXLab** [comment] 2019-03-31 16:20
I was wondering about this too, it's definitely bad news.
The fact that there are way too much cyclic references doesn't make it easy to find out at which point a reference is kept that shouldn't

**Comment by RoiEXLab** [comment] 2019-03-31 17:05
@DanVanAtta @ron-murhammer Not making any progress on this. There are way too many objects with a reference to TripleAFrame to check them all.
Maybe you have a better approach to find the evil reference.

**Comment by RoiEXLab** [comment] 2019-04-01 21:37
Coming back at this I think I have figured out the most problematic bit:
This line is somewhat broken, the cleanup mechanism doesn't work:
https://github.com/triplea-game/triplea/blob/e02e3b532cf6ca307cc56a44ca2c7c66b634322d/game-core/src/main/java/games/strategy/triplea/TripleA.java#L115
The code adds a windowClosing listener that is supposed to remove the reference to TripleAFrame, however this listener is never being called by swing for whatever reason, so the reference stays where it is.
I haven't been able to find a good fix for this, I just commented out this line for testing purposes. However I noticed there are still some other "memory leaks" that are minor, but still consume a noticeable amount of memory:
![JProfiler](https://user-images.githubusercontent.com/8350879/55361168-a76a3200-54d6-11e9-87d9-a5c78726ffe4.png)

**Comment by simon33-2** [comment] 2019-04-02 10:21
If this can be fixed, that would be awesome. Although I'd have to say, exiting and restarting does work.

**Comment by RoiEXLab** [comment] 2019-04-02 10:41
@simon33-2 Well obviously restarting the whole application works, but this is not the goal

**Comment by llfletch** [comment] 2019-04-02 21:54
On a related note, since the users are going to have to exit the program at some point rather than staying at the main menu, it would be nice if the program could remember the most recent save game file between restarts.

**Comment by DanVanAtta** [comment] 2019-08-24 05:22
@RoiEXLab , is this mostly fixed now? Please re-open if not. 

@llfletch , if you're willing to test the latest pre-release for problems, it would be really appreciated.

**Closed by DanVanAtta** 2019-08-24 05:22 UTC
Labels: Problem

**Comment by RoiEXLab** [comment] 2019-08-24 10:50
Well a leak is still there, at least the last time I checked a couple of days ago.
Basically TripleAFrame doesn't get garbage collected after getting closed, which has references to the entire game logic, so nothing gets garbage collected.
After spending hours profiling I wasn't able to find all the references.
I found a couple of them, but there are some left.

**Comment by RoiEXLab** [comment] 2019-08-24 10:52
Also odds are #5070 might reduce places where a leak could occur
