### ISSUE TITLE
Napoleon Empires crash

### ISSUE THREAD

**Issue by jnm3** [triplea-game/triplea#4731] opened 2019-03-05 23:01 UTC
### Engine version

Version 1.9.0.0.13066
### My Operating System
macOS Mojave Version 10.14.3
### Map name
Napoleonic Empires
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
In round three I'm waiting for AI to complete a players turn and an error pops up with a stop message and something do do with threads.
### Do you have the exact error text? Please copy/paste if so
```
Mar 06, 2019 10:02:52 AM games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: Two history synchers?
java.lang.IllegalStateException: Two history synchers?
	at games.strategy.triplea.ui.TripleAFrame.showHistory(TripleAFrame.java:1813)
	at games.strategy.triplea.ui.TripleAFrame.updateStep(TripleAFrame.java:1596)
	at games.strategy.triplea.ui.TripleAFrame.lambda$new$46(TripleAFrame.java:1539)
	at games.strategy.engine.framework.AbstractGame.notifyGameStepListeners(AbstractGame.java:85)
	at games.strategy.engine.framework.ServerGame.notifyGameStepChanged(ServerGame.java:546)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:506)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:414)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:290)
	at java.util.Optional.ifPresent(Optional.java:159)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:41)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Thread.java:748)
```
### Instead of this error, what should have happened?
[Nap.2019.3.4.Start.tsvg.zip](https://github.com/triplea-game/triplea/files/2933477/Nap.2019.3.4.Start.tsvg.zip)
[Nap.2019.3.5.Crash.tsvg.zip](https://github.com/triplea-game/triplea/files/2933460/NAP.2019.3.5.Crash.tsvg.zip)
This file is the file I saved at the start -- it happens at the same place each time. Even if I start from scratch.

**Comment by jnm3** [comment] 2019-03-05 23:01
Saved games start and crash

**Comment by RoiEXLab** [comment] 2019-03-06 13:52
@jnm3 I'm not able to reproduce your error using your savegames. Could you try reproducing it yourself and edit your message to provide the error message and a screenshot perhaps?

**Comment by jnm3** [comment] 2019-03-06 15:22
[Archive.zip](https://github.com/triplea-game/triplea/files/2936939/Archive.zip)
[Archive.zip](https://github.com/triplea-game/triplea/files/2936950/Archive.zip)
The first zip file contains screen shots and the second contains the content of the console tabs.
I hope this helps. 
And thank you.

**Comment by RoiEXLab** [comment] 2019-03-06 15:31
@jnm3 Thanks, I updated the original post with the relevant information.
Also this other error occured:
```
Mar 06, 2019 10:02:52 AM games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: null
java.lang.NullPointerException
	at games.strategy.triplea.ui.TripleAFrame.lambda$showGame$54(TripleAFrame.java:1974)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Not sure if it's related.

**Comment by RoiEXLab** [comment] 2019-03-06 16:15
For reference: The other error seems somewhat related. The error looks like a concurrency error being caused by non-atomic boolean checks and writes.

@jnm3 Could you try reproducing your error with the [latest pre-release (1.10.14271)](https://github.com/triplea-game/triplea/releases/tag/1.10.14271)?
Note that your savegame wont work there.

**Comment by jnm3** [comment] 2019-03-06 17:52
Downloaded and installed from your link the version you will see in the txt files, from the  Mac .dmg file.
I used the game enabled edit mode (if that helps) to make a few changes. 
Start of round three: NullPointerException Error.
[Archive.zip](https://github.com/triplea-game/triplea/files/2937586/Archive.zip)

**Comment by jnm3** [comment] 2019-03-06 17:53
To the previous message I started a new game.

**Comment by RoiEXLab** [comment] 2019-03-08 01:28
Hey @jnm3 Could you try reproducing your error using the latest pre-release? 
https://github.com/triplea-game/triplea/releases/tag/1.10.14329
I'm hoping that the issue might be fixed in this release, in case it isn't I'll have to revisit this topic in-depth.

**Comment by jnm3** [comment] 2019-03-08 04:00
Same thing crashes at the start of round three.

**Comment by jnm3** [comment] 2019-03-08 10:34
It didn't work, same place start of round three.

**Comment by panther2** [comment] 2019-03-08 15:22
FWIW I treid the savgame on Windows, and went flawlessy through the third turn, too. So I can't reprodcue the issue, either. Maybe another MAC-only issue.

BTW, which exact Java version are you using, @jnm3 ?

**Comment by jnm3** [comment] 2019-03-08 21:17
From the link you sent:
This "TripleA_1.10.14329_macos.dmg"

**Comment by RoiEXLab** [comment] 2019-03-10 00:15
I ran out of Ideas. I tried to reproduce this issue by adding random delays at places but no luck.
Maybe @DanVanAtta or @ron-murhammer have an Idea?

**Comment by ron-murhammer** [comment] 2019-03-10 03:55
Hmm. Nothing comes to mind and I haven't seen anything like that before. I'd guess its some kind of edge case threading issue that maybe is more likely on Macs.

**Comment by panther2** [comment] 2019-03-10 14:37
@jnm3 

> BTW, which exact Java version are you using, @jnm3 ?

> From the link you sent:
> This "TripleA_1.10.14329_macos.dmg"

Find the **Java** version TripleA is using on the top left side of the TripleA screen that shows after starting the pre-release:
![javaver](https://user-images.githubusercontent.com/20812775/54086503-525d5500-434a-11e9-9281-31580e98f679.PNG)

**Comment by RoiEXLab** [comment] 2019-03-10 14:43
@panther2 Thanks for your efforts, but I don't think this one is cause by a java incompatibility.

**Comment by panther2** [comment] 2019-03-10 20:41
@RoiEXLab OK, nevermind then, @jnm3 .

**Comment by DanVanAtta** [comment] 2020-03-11 04:47
The history sync problem can be reproduced if the history is open/closed very quickly, but should nto be game crashing. 

Given the age of this and failure to reproduce so far, I don't think we can action this ticket.

**Closed by DanVanAtta** 2020-03-11 04:47 UTC
Labels: Impact: Game Crashing, Problem
