### ISSUE TITLE
Mini-Flag Proliferation 

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#684] opened 2016-05-17 06:30 UTC
1. Flags do not need to be drawn on factory
2. The flag probably should always be drawn below units
3. Perhaps we only need to draw the flag once per unit group? (territories with multiple nations on them may need a representative unit chosen)

In small and large mode, there are a lot of flags drawn:
![flag_proliferation](https://cloud.githubusercontent.com/assets/12397753/15313135/1a4c1bd0-1bbe-11e6-8333-39c05dd63cd9.png)

![large](https://cloud.githubusercontent.com/assets/12397753/15313138/1e6b19aa-1bbe-11e6-8ecf-fa5db9c5ca7d.png)

**Comment by RoiEXLab** [comment] 2016-05-17 11:02
> Flags do not need to be drawn on factory

Yes you're right. The Problem is, that Factories have different names per Map e.g. factory != xyfactory. Those "exceptions" need to be added to th exceptions list in UnitsDrawer.java.

> The flag probably should always be drawn below units

This would be a little bit more tricky... Currently the little Flags are drawn just before/after each unit. This means that in order to achieve this, a new completely independent method needs to be called iterating through all those units before/after the UnitsDrawer gets called...

> Perhaps we only need to draw the flag once per unit group? (territories with multiple nations on them may need a representative unit chosen)

Same... A completely new method needs to be called iteration to a filtered collection of units...

**Comment by DanVanAtta** [comment] 2016-05-21 04:33
Maybe let's do this:
- let's bind a `hotkey` that you can hold down to toggle the flags on/off

Then we would have one checkbox menu option:
1. "Show unit flags (`hotkey`)"

And anoher menu option with a radio button selection:
1. Show small flag
2. Show large flag

@RoiEXLab , thoughts?

**Comment by RoiEXLab** [comment] 2016-05-21 17:13
I don't get what exactly you are trying to achieve with this... D:

**Comment by DanVanAtta** [comment] 2016-05-21 19:37
See the source forge forum post about the issue, it was not well received as a default on option. I suspect many will turn the flags on, and will probably never turn them back on. In which case I think they would be most useful with an activation key, to turn it on when needed.

**Comment by RoiEXLab** [comment] 2016-05-21 20:12
> I suspect many will turn the flags on, and will probably never turn them back on.

Off or on? ^^

I will look into that once all of those PRs are merged - I planned to replace a method with Enum.valueOf in there anyway...

**Comment by RoiEXLab** [comment] 2016-06-05 19:42
@DanVanAtta  Is a Map-related default setting an "easy-to-implement" option?
On some Maps like 270BC (when the current little flags get removed) this feature would be neccesary - so a on-by-default would be very useful...
This will be my next protect to work on

**Comment by DanVanAtta** [comment] 2016-06-06 04:32
We don't really have a mechanism for per-map defaults. 
I'm still of the opinion the best route is off by default with a hotkey to turn it on/off.

**Comment by RoiEXLab** [comment] 2016-06-06 12:57
Hmm...
What about a reminder to turn it on on maps like 270BC?
Similar to the way, the turorial map works...

**Comment by ron-murhammer** [comment] 2016-06-10 03:33
@RoiEXLab @DanVanAtta There are relatively simple ways to add an optional map property to show or hide the flags. I actually think on a good deal of maps this would be a good default on option. One thing I did notice though is it seems to slow down the initial map drawing some as on many maps there are so many little flags.

**Comment by DanVanAtta** [comment] 2016-06-10 03:35
IF there are some maps where it is a good default on option, I've no objection at all.

**Closed** 2016-06-10 03:35 UTC
Labels: Feature Request
