### ISSUE TITLE
Why are 5 players shown in the lobby screen but 9 are in there?

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6969] opened 2020-06-30 22:04 UTC
### How can the problem be recreated?
Right click on a bot server and select show players from the moderator toolbox.
### Do you have any ideas for an expected fix?
It should list the correct number of players,  (Is it listing the ghosts?)
Game Version: Current stable.

- [ ] yes
- [ ] no

### Is there anything else we should know?
![2020-06-30 (2)](https://user-images.githubusercontent.com/17258293/86181519-2300c780-bafc-11ea-8802-f1728875fd8c.png)

**Comment by Cernelius** [comment] 2020-06-30 22:12
Yeah, I wanted to open an issue like this too.

Side note, this has nothing to do with any "moderatol toolbox", I think. I can say at least one user confirmed the behaviour too.

It makes this feature partially useless and it's confusing. I'm almost sure the ghost players are the players that left the host recently the most.

**Comment by prastle** [comment] 2020-06-30 22:16
@Cernelius it is also interesting that the lobby displays the correct number of "current" players but the toolbox does not.  TY for confirming.

**Comment by prastle** [comment] 2020-06-30 22:26
something that is also interesting is apparently we are seeing an empty bot in the lobby Bot302 but here is what the toolbox shows

![2020-06-30 (5)](https://user-images.githubusercontent.com/17258293/86183072-34979e80-baff-11ea-8ab5-166f7f102a5e.png)

**Comment by prastle** [comment] 2020-06-30 22:28
It should be noted that coolswede is not even in the lobby ...

**Comment by DanVanAtta** [comment] 2020-07-01 06:52
This is a bug. When players leave a game they are not reliably being removed from the list of present players. There is likely a player left mechanism that was not accounted for considering how common this problem is.

For context, when a game joins lobby, it'll message lobby which players are in the game. Then when players join or leave, the game is supposed to message the lobby that players have joined or left. Seemingly the 'player left' message is either not being reliably sent or is being mishandled and not recorded properly.

**Comment by RoiEXLab** [comment] 2020-07-02 22:43
Could this be related to  #6894 ?

**Comment by DanVanAtta** [comment] 2020-07-02 23:14
Different call paths @RoiEXLab 

One is a user querying the lobby for chatters. The chatter list is stored in-memory. If a users view of chatters become out of sync, then they can query for a user that DNE. I think websocket updates when a machine goes to sleep is potentially related.

This issue is a game does not successfully tell lobby that a player left. The players-in-game list is maintained in database IIRC. A game is responsible to notify lobby of the players that are in the game when the game connects, when a player leaves, and joins. If a game disconnects, the players in game is cleared.

**Comment by Cernelius** [comment] 2020-07-05 18:14
This screenshot has been taken a few minutes ago:
![20200705_001](https://user-images.githubusercontent.com/19562310/86539298-9f7c1780-befb-11ea-9dcc-2e740ebf97c9.png)

3 players (actually, 2 players and 1 spectator) present in Bot305_California, but the list is 44 long!

Also, I would not list the bot (in this case Bot305_California).

And, of course, there is still the old issue that anyone inside any host is identified as "player", even if it is not playing anything.

**Comment by prastle** [comment] 2020-07-05 20:44
Ya I noticed that as well when I came back from camping today lol ... @RoiEXLab  @DanVanAtta

**Comment by Cernelius** [comment] 2020-07-06 13:45
Moreover, the host players listing has all upper case starting names prioritized, which is currently inconsistent with the lobby usernames listing.

Related to:
https://github.com/triplea-game/triplea/pull/6802

**Comment by DanVanAtta** [comment] 2021-01-17 22:23
duplicate of: https://github.com/triplea-game/triplea/issues/7804

**Closed by DanVanAtta** 2021-01-17 22:23 UTC
Labels: Problem
