### ISSUE TITLE
Mongolian rule bug

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4812] opened 2019-04-14 10:29 UTC
### Engine version
1.9.0.0.13066

### My Operating System
Ubuntu

### Map name
Global 40 House Rules
also WW2 Global 1940 Balanced Mod3

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Blitz through Amur while the Mongolian rule is still in play. Undo the move. Mongolian rule will be activated incorrectly

### Instead of this error, what should have happened?
Mongolian rule should not be activated if the move which activated it is undone.

**Comment by simon33-2** [comment] 2019-04-14 10:51
[MongolianRuleBug1.zip](https://github.com/triplea-game/triplea/files/3077269/MongolianRuleBug1.zip)

**Comment by panther2** [comment] 2019-04-14 12:02
Just adding here, that it is handled correctly in ww2global40_2nd_edition.xml (OOB):

[mongolian_rule_undo_move_test.zip](https://github.com/triplea-game/triplea/files/3077316/mongolian_rule_undo_move_test.zip)

**Comment by beelee1** [comment] 2019-04-14 23:59
so i tested "Global 40 House Rules" similar to the test panther ran on global 40 oob and it behaved the same as his test. Also tried editing the same conditions to the one simon has but it still behaved correctly.

I'll manually go through a oob game and see if I can reproduce. I didn't see anything different in the oob xml and the mods either. 

Here's the first test

global 40 house rules mongolia undo test.zip

**Comment by beelee1** [comment] 2019-04-15 03:11
try this again
[global _40 _house _rules_ mongolia_ undo_ test.zip](https://github.com/triplea-game/triplea/files/3078292/global._40._house._rules_.mongolia_.undo_.test.zip)

**Comment by panther2** [comment] 2019-04-15 06:21
@beelee1 
In my tests I have tried moves and it did not make a difference.
I have tested with a new BM game myself, now, and could not reproduce the issue, either.

I tend to think that this is something related to that special game, as we sometimes experience it.

**Comment by simon33-2** [comment] 2019-04-15 08:41
Interesting. It does indeed only occur if you do the blitz in a single move with the ctrl-click. If you do it in two moves as in @panther2 's example, the problem doesn't occur.

I can reproduce it with Global 1940 2nd Ed.

**Comment by panther2** [comment] 2019-04-15 09:23
@simon33-2 @beelee1 

That's it! In my testings I always moved the blitzing tank back to where it came from (without ctrl-click) and in two steps. When the second move goes anywhere else and is done using ctrl-click, the problem is reproducable.

**Comment by beelee1** [comment] 2019-04-15 20:30
right on. well we know what it is now. Don't know how hard it'd be to fix but at least there is a workaround

**Comment by ron-murhammer** [comment] 2019-04-16 01:11
This should be fixed once #4813 is merged. 

The problem was that blitz moves create "placeholder battles" for empty territories that are conquered (Amur in this case). The engine was only removing any battles that were empty from the end territory of a route not any intermediate steps. This is now fixed so that it'll undo these blitz battles as well. In 99.9% of cases this didn't matter and only matters in this case as triggers are checking if there was any battle in territories adjacent to Mongolia.

**Comment by simon33-2** [comment] 2019-04-16 08:18
Is 1.10 going to be ready for beta testing soon? Sounds like regression testing that should be done at the same time as everything else. I might get a chance over Easter to look at this though.

**Comment by ron-murhammer** [comment] 2019-04-17 03:11
Closing as this should be resolved. Please comment if its not fixed.

**Closed by ron-murhammer** 2019-04-17 03:11 UTC
Labels: Impact: Bad Game Rules
