### ISSUE TITLE
Still two *.jar in <bin>

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#3314] opened 2018-03-25 08:17 UTC
### Engine version
1.9.0.0.9893

Despite #3300 there are still two *.jar-files inside the bin-directory.

**Comment by RoiEXLab** [comment] 2018-03-25 14:41
Did you do a clean reinstall?

**Comment by prastle** [comment] 2018-03-25 14:50
Yes I can confirm we have game-core-1.9.0.dev and 1.9.0.09893 .  on a clean install is that what you are expecting?  @RoiEXLab

**Comment by RoiEXLab** [comment] 2018-03-25 15:06
@prastle Not at all.
I just wanted to confirm the additional jar file isn't an old artifact of an earlier installation.
Looks like @DanVanAtta or someone else needs to look at this again.

It's interesting that the naming schemes of the 2 jar files differ.

**Comment by panther2** [comment] 2018-03-25 16:59
@RoiEXLab 

> Did you do a clean reinstall?

Yes, I always do.

**Comment by DanVanAtta** [comment] 2018-03-26 21:57
We can see the problem from the release size, it is still ~20MB. Locally I was able to repro and fix and saw 16MB files. Because we do not clean the workspace in travis, the assets that were intended to be excluded would be created on previous steps and get included (thanks to us including everything in artifacts instead of pulling in files explicitly). 

#3316 should fix more properly by putting these unwanted artifacts in a different folder.

**Comment by DanVanAtta** [comment] 2018-03-26 21:58
I'll be following up with #3316, assigning this to myself accordingly.

**Comment by DanVanAtta** [comment] 2018-03-31 17:31
Now fixed :sweat_smile: 

![screenshot from 2018-03-31 10-29-56](https://user-images.githubusercontent.com/12397753/38165825-9e4fa5b6-34ce-11e8-87a5-375d4a5329ee.png)

**Closed by DanVanAtta** 2018-03-31 17:31 UTC
Labels: category: bug
