### ISSUE TITLE
Reported issue on a Mac (Scramble Units Dialog Broken) 

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1269] opened 2016-09-28 01:33 UTC
OS X 10.10.5

Reportedly:
"Well, I spoke too soon.

This game is, unfortunately, unplayable.

There's a major bug: when the prompt comes up to select units for scramble it just blinks on and off and there's no way to make it stop and you can't interface with it.

I'm guessing that it simply won't play nice with a Mac and is, therefore, unplayable.

I can start it up again with the old game if you want, but this one's toast."

Any suggestions?

**Comment by panther2** [comment] 2016-09-28 08:09
Preinstalled Java or latest JRE from java.com?

**Comment by DanVanAtta** [comment] 2016-10-04 04:26
We need more information for this to be actionable. I somewhat assume scramble is not consistentlyk broken on that version of Mac OS, otherwise I am really disturbed that we had not received more / earlier bug reports.

**Comment by simon33-2** [comment] 2016-10-10 00:53
I've received more info. They think it's to do with the Java version - they've tried updating the Java but get an "unauthorised" message. I've asked about the Java they have installed.

**Comment by simon33-2** [comment] 2016-10-15 23:35
Java -version output:
This is what Terminal said: java version "1.6.0_65"

Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4828a)

Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Doesn't 1.9 require Java 1.8? Why doesn't it tell you that your Java is out of date?

**Comment by DanVanAtta** [comment] 2016-10-16 00:32
Mac installer should be installing a bundled one, that might be the one used with the game and not the  OS default JRE.

**Comment by panther2** [comment] 2016-10-25 08:06
Here is a new thread on aaa.org concerning this subject:
http://www.axisandallies.org/forums/index.php?topic=38728.0

**Comment by simon33-2** [comment] 2016-10-30 04:02
I can (or could this morning) duplicate a similar problem on my ancient MacBook with OS X Lion.

The scramble box flashes on and off as though there is some kind of race condition as to which window should in front. Sometimes the issue is resolved and it stays on. Sometimes not.

Is that at all helpful? What info would you like?

**Comment by simon33-2** [comment] 2016-11-04 04:18
Can I question if there are any reports of Triple-A 1.9 being playable on a Mac?

**Comment by Cernelius** [comment] 2016-11-09 01:19
I figure I copypaste this thing here. It seems that somebody on Mac is unable to download maps and maybe other issues. Told him to make a report. This is a very loose report, so feel free to ignore it, imo.

> (22:16:46) Liveespn777:  I've been in here for two hours waiting to join whats the deal with this?
> (22:16:54) TheKhan:  Frank never returned
> (22:16:56) Liveespn777:  I thought this was like AA
> (22:17:09) Cernel:  what's the problem?
> (22:17:09) TheKhan:  what map you play?
> (22:17:17) TheKhan:  and hi Live
> (22:17:22) Liveespn777:  I haven't been able to play a game
> ChasmDiver has joined
> (22:17:26) Master_Blaster:  yes whats th e problem
> (22:17:27) TheKhan:  hey cernel
> (22:17:46) TheKhan:  Live you play NWO?
> (22:17:49) Master_Blaster:  we help u
> (22:17:58) Cernel:  well you can host yourself (click on Host Game), join a game waiting for players or take possession of an empty bot
> (22:18:03) Liveespn777:  I used to play gametable all the time
> (22:18:26) TheKhan:  cernel why does specktators have to be barthered with combat reports ?
> ChasmDiver has left
> (22:19:27) Liveespn777:  I hosted a game but I don't see it in the lobby
> wirkey (1) has joined
> (22:19:43) prastle:  so when you host dont click
> (22:19:43) TheKhan:  Live join bot RambO
> (22:20:01) TheKhan:  i give you a game
> (22:20:05) prastle:  if it says unreachable from interent
> (22:20:15) prastle:  choose yes and let triplea try to set up
> Courtney123abc has joined
> (22:20:50) Courtney123abc:  hai
> (22:20:52) Liveespn777:  ok I joined RambO but it still says 1 player
> Courtney123abc has left
> Courtney123abc has joined
> Courtney123abc has left
> ISunkYourBattleship has left
> (22:21:26) TheKhan:  you need map
> Captain_butter has joined
> (22:21:38) TheKhan:  download new world order
> (22:22:04) Cernel:  yeah, you click on choose game and select the map you want to play, then wait for somebody to join you (if you want you can also advertise here in lobby)
> pekka74 has left
> (22:22:16) Cernel:  for solving the hosting issues:
> (22:22:28) Cernel:  Hosting Help: http://tinyurl.com/gnkrxx5
> (22:23:08) Cernel:  well, that is quite an outdated topic
> (22:23:19) TheKhan:  he should be able to join bot or?
> (22:24:51) TheKhan:  WAW - NML - TRS - NWO - Antient times anybody up for game?
> (22:25:45) Cernel:  You just slapped Liveespn777
> (22:25:47) Cernel:  If you see a game you want to play with the Status Waiting For Players you can join that and ask the user inside if he wants to play with you
> (22:25:47) Liveespn777:  where do I download maps?  It doesn't let me choose anything. 
> Kaptain has joined
> wirkey has left
> (22:26:10) TheKhan:  thx Cernel but i know this
> (22:26:13) Cernel:  To download maps, click on the Download Maps button
> (22:26:39) Cernel:  or just join a game in progress and you will be prompted to download that map, if you don't have it
> (22:26:46) Liveespn777:  it pops up this ancient looking .dos 
> (22:27:01) Cernel:  uhm, no no dos should pop up
> (22:27:06) Liveespn777:  there is no option to download anything... I run a mac pro
> (22:27:13) Cernel:  so you are saying that you click on "Download Maps" and it doesn't work?
> KingKelly has left
> (22:27:19) Cernel:  ahh a Mac
> (22:27:24) Liveespn777:  its a second window that looks like all the code
> (22:27:28) Cernel:  better you open an issue about that
> (22:27:35) prastle:  ask epi we did yesterday
> (22:27:38) Cernel:  that is surely a bug
> (22:27:44) prastle:  ah he not here
> (22:27:51) Cernel:  open an issue here explaining the problem:
> (22:28:01) Cernel:  Bug Reports: https://github.com/triplea-game/triplea/issues
> (22:28:50) prastle:  he used the mac post in source forge cer
> (22:29:05) Liveespn777:  yea i just looked through the forum... I don;t have the download maps option
> (22:29:21) TheKhan:  Mac sucks ;-)
> (22:29:30) prastle:  ;)
> (22:29:41) Cernel:  yes, that may be a bug; just open an Issue in github detailing the problem with screenshots
> ISunkYourBattleship has joined
> yippi has left
> (22:30:45) Cernel:  the Mac seems having various bugs; I don't know if this one has been already reported
> (22:31:05) prastle:  naw no bugs he had
> (22:31:12) prastle:  just hard to find
> (22:31:28) Liveespn777:  For gaming it blows... Can't play Heroes 3 on this either!  They just came out with a bush league simplified HD version with half the features 
> (22:31:30) prastle:  popped 4 rooms after
> Liveespn777 has left
> d5d5-sfc- has left
> (22:32:20) Cernel:  just open an issue; the developers are fixind the regressions; hopefully all reported will fixed in a couple weeks
> (22:32:41) Cernel:  ok he left

**Comment by Sabovitch** [comment] 2016-11-12 21:33
So we still don't have a fix for this yet for mac users?

**Comment by ron-murhammer** [comment] 2016-11-13 01:11
@Sabovitch Not yet. It appears to be an issue for all Mac users as its been reported several times now.

**Comment by Sabovitch** [comment] 2016-11-13 01:15
Bummer......

Well, I'll keep checking time to time in hopes we figure it out. Love this game.

________________________________

**Comment by simon33-2** [comment] 2016-11-20 05:06
@Sabovitch 

You can still use 1.8.0.9 on a mac.

**Comment by simon33-2** [comment] 2016-11-30 15:10
FWIW, it seems to work for me after I minimise Triple-A. Then I can select the scramble options and continue on. Hardly ideal and debateably playable.

**Comment by simon33-2** [comment] 2016-12-11 11:40
I have tracked this bug to line 1261 in src/games/strategy/triplea/ui/TripleAFrame.java

This is the line which calls continueLatch.await(); // continueLatch = new CountDownLatch(1)

Called after the runnable is sent to swing and "addShutdownLatch(continueLatch)" is called.

Hope that is helpful to those with more Java experience. Seems to be a built in Java utility and Googling quickly doesn't reveal known issues.

**Comment by RydbirkJr** [comment] 2016-12-15 19:18
Any idea when this will be fixed? The game is unplayable on Mac.

**Comment by DanVanAtta** [comment] 2016-12-15 20:51
Which versions of Mac is this effecting?

FYI - a workaround seems to be to minimize the game and then maximize it again.

One data point - I was not able to reproduce on linux. Hopefully will get fixed soon'ish, this is close to the top of the list to fix.

**Comment by RydbirkJr** [comment] 2016-12-15 21:14
I'm running on a MacBook Pro (Retina, 15-inch, Late 2013) with macOS Sierra v 10.12.1 (16B2555).

I have tried the minimize trick but with no luck. However, when I minimize, it stops flashing, and the scramble dialog is shown on top of Google Chrome or whatever program I had running in the background. However, I cannot use the scramble dialog. If I click it, it maximizes the game and starts flashing again.

The same happens when I try to leave the game: It stops flashing, but I cannot click it since the "Leave game" dialog is open.

Feel free if you have further questions, happy to help :-)

**Comment by simon33-2** [comment] 2016-12-15 23:57
I would say it happens on all macs. My mac is OS X Lion (10.7) which is the earliest which will run Java 8. I didn't even know there was a 10.12.

I find neither of the tricks works every time and not always straight away but you can ultimately get it to work.

**Comment by DanVanAtta** [comment] 2016-12-16 04:10
Please give the latest version a try http://www.triplea-game.org/download/ (1.9.0.0.3373)

I removed the 'always on top' setting for scramble. With some luck it will avoid the flashing (though we *might* see that the pop-up shows up in the background, but with luck it'll appear properly)

**Comment by simon33-2** [comment] 2016-12-16 07:02
Seems to work.

**Comment by RydbirkJr** [comment] 2016-12-16 07:04
I'll test it later today, thanks!

Den 16. dec. 2016 08:02 skrev "simon33-2" <notifications@github.com>:

**Comment by RydbirkJr** [comment] 2016-12-16 10:43
I've just tested it, but unfortunately, it's still not working for me. Do I have to remove the old installation or any settings upon install? 

It seems to be interfering with the rendering of the rest of the game. If I scroll on the map while the scramble dialog is flashing, the map is only updated on each "flash" of the dialog.

**Comment by simon33-2** [comment] 2016-12-16 11:19
Concur. It worked the first time though.

**Comment by RydbirkJr** [comment] 2016-12-16 11:28
Only difference is that if I press CMD + L (leave game), the scramble box goes to the background, and it stops flashing even after closing the leave game dialog. However, when bringing it to focus again, it starts flashing again..

**Comment by DanVanAtta** [comment] 2016-12-16 20:01
Okay, I *think* maybe I've spotted the issue. There is logic to trigger a 'wait' action on any unknown property change event. It could be the case that on Mac OS we are getting these frequently which would then 'cycle' the scramble screen. I've removed the 'wait' and and 're-cycle' functionality of the scramble dialog, hopefully that will do the trick.

If you would, please give the latest version a try:  http://www.triplea-game.org/download/ (1.9.0.0.3379) and let me know how it goes.

**Comment by DanVanAtta** [comment] 2016-12-16 20:02
> "Do I have to remove the old installation or any settings upon install?"

No, different versions should install side-by-side without any issue. Just be sure to launch the latest one (the game version is printed on the main screen, should be a good confirmation you have the latest launched)

**Comment by DanVanAtta** [comment] 2016-12-16 20:06
@simon33-2  - the "continueLatch.await(); // continueLatch = new CountDownLatch(1)" is code in TripleA, it's custom. It does go into library code after not long, so I can see the confusion. Overall I'm not a huge fan of the game 'latch'.  Effectively the countdown latch is a procedural way to halt the progression of the game and wait for some event. An alternative to using a count down latch would have been to use a callback of one form or another.

**Comment by DanVanAtta** [comment] 2016-12-16 22:02
Correction to above @simon33-2 - CountDownLatch is not our code.. Though, it's pretty heavily used though for game wait events.

**Comment by RydbirkJr** [comment] 2016-12-16 23:03
@DanVanAtta It's working now with .3379 - good job! :-) Thanks for the help.

**Comment by DanVanAtta** [comment] 2016-12-17 00:46
Good to hear, thank you for reporting the problem.

**Closed by DanVanAtta** 2016-12-17 00:46 UTC
Labels: Bug Backlog, UI Related, Urgent
