### ISSUE TITLE
6157 - Battle Calc NPE

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2225] opened 2017-08-15 19:18 UTC
Not certain on the repro, got this when closing a game:

```
java.lang.NullPointerException
	at games.strategy.triplea.delegate.BattleCalculator.selectCasualties(BattleCalculator.java:539)
	at games.strategy.triplea.delegate.Fire.selectCasualties(Fire.java:166)
	at games.strategy.triplea.delegate.Fire.access$100(Fire.java:21)
	at games.strategy.triplea.delegate.Fire$2.execute(Fire.java:228)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:41)
	at games.strategy.triplea.delegate.MustFightBattle.fight(MustFightBattle.java:399)
	at games.strategy.triplea.delegate.BattleTracker.fightBattleIfOnlyOne(BattleTracker.java:1177)
	at games.strategy.triplea.delegate.BattleDelegate.start(BattleDelegate.java:103)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:511)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:407)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:271)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by RoiEXLab** [comment] 2017-08-17 03:46
Analysing the code prior to @ron-murhammer's refactoring changes, it seems the ITripleAPlayer#selectCasualties method [is returning null](https://github.com/triplea-game/triplea/blob/e1b0b01c8a3e2e31faeb75e50335c146a1fd02aa/src/main/java/games/strategy/triplea/delegate/BattleCalculator.java#L535).
So there are to possible, potential explanations: Either the AI is returning null once it notices the game is over, or the code returns null if the player closes the game while in the casualty selection screen.
I'd appreciate some testing on this

**Comment by ssoloff** [comment] 2017-08-17 03:48
Reproduction steps:

1. Get into combat where the battle window prompts you to press <kbd>SPACE</kbd> to select casualties.
1. Instead of pressing <kbd>SPACE</kbd>, select **File > Leave Game** from the main menu.

In addition to the exception reported in the original description, I observed two instances of `ConcurrentModificationException` prior to the NPE (some line numbers in the NPE are different because I reproed on latest `master` [1.9.0.0.6200]):

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at games.strategy.util.CountDownLatchHandler.shutDown(CountDownLatchHandler.java:61)
	at games.strategy.triplea.ui.AbstractUIContext.shutDown(AbstractUIContext.java:225)
	at games.strategy.triplea.ui.UIContext.shutDown(UIContext.java:176)
	at games.strategy.triplea.ui.TripleAFrame.stopGame(TripleAFrame.java:548)
	at games.strategy.triplea.ui.display.TripleADisplay.shutDown(TripleADisplay.java:106)
	at games.strategy.triplea.TripleA.shutDown(TripleA.java:89)
	at games.strategy.engine.framework.ServerGame.stopGame(ServerGame.java:343)
	at games.strategy.triplea.ui.TripleAFrame.leaveGame(TripleAFrame.java:581)
	at games.strategy.triplea.ui.menubar.FileMenu.lambda$2(FileMenu.java:90)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:48)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        <. . . snip . . .>
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at games.strategy.util.CountDownLatchHandler.shutDown(CountDownLatchHandler.java:61)
	at games.strategy.triplea.ui.AbstractUIContext.shutDown(AbstractUIContext.java:225)
	at games.strategy.triplea.ui.UIContext.shutDown(UIContext.java:176)
	at games.strategy.triplea.ui.TripleAFrame.stopGame(TripleAFrame.java:548)
	at games.strategy.triplea.ui.display.TripleADisplay.shutDown(TripleADisplay.java:106)
	at games.strategy.triplea.TripleA.shutDown(TripleA.java:89)
	at games.strategy.engine.framework.ServerGame.stopGame(ServerGame.java:343)
	at games.strategy.triplea.ui.TripleAFrame.leaveGame(TripleAFrame.java:581)
	at games.strategy.triplea.ui.menubar.FileMenu.lambda$2(FileMenu.java:90)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:48)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        <. . . snip . . .>
java.lang.NullPointerException
	at games.strategy.triplea.delegate.BattleCalculator.selectCasualties(BattleCalculator.java:532)
	at games.strategy.triplea.delegate.Fire.selectCasualties(Fire.java:166)
	at games.strategy.triplea.delegate.Fire.access$1(Fire.java:98)
	at games.strategy.triplea.delegate.Fire$2.execute(Fire.java:228)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:41)
	at games.strategy.triplea.delegate.MustFightBattle.fight(MustFightBattle.java:400)
	at games.strategy.triplea.delegate.BattleTracker.fightBattleIfOnlyOne(BattleTracker.java:1178)
	at games.strategy.triplea.delegate.BattleDelegate.start(BattleDelegate.java:103)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:511)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:407)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:271)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Thread.java:748)
```

Also, the battle window is still visible after returning to the main menu, and I am unable to close it.  I ended up having to forcefully kill the JVM process.

**Comment by ssoloff** [comment] 2017-08-17 04:15
What @RoiEXLab said. :smile:  The problem is at the end of `BattleDisplay#getCasualties()`:

```java
mapPanel.getUiContext().addShutdownLatch(continueLatch);
try {
  continueLatch.await();
} catch (final InterruptedException ex) {
  ClientLogger.logQuietly(ex);
} finally {
  mapPanel.getUiContext().removeShutdownLatch(continueLatch);
}
return casualtyDetails.get();
```

`continueLatch` is added to the list of latches to be released when the game is shut down.  At the time we run the **File > Leave Game** command, the thread running this code is parked on the `continueLatch.await()` line.  Shutting down the game releases the latch, and this thread proceeds to return `casualtyDetails.get()`, which is `null` because the user has yet to select any casualties (see the `casualtyDetails.set(response)` statement a few lines prior, which is never hit).

My first inclination is to say that `null` is a valid return value for this method (and probably for all of its callers, as well).  Thus, the `BattleCalculator#selectCasualties()` method needs to appropriately handle a `null` `casualtySelection` before line 532 is executed.  However, I'm not sure what "appropriately" means in this case.  If you look towards the top of this method, you'll see several guard clauses where an empty:

```java
if (targetsToPickFrom.isEmpty()) {
  return new CasualtyDetails();
}
```

or effectively empty:

```java
if (dice.getHits() == 0) {
  return new CasualtyDetails(Collections.emptyList(), Collections.emptyList(), true);
}
```

`CasualtyDetails` is returned.  Not sure if that's the appropriate thing to do when `ITripleAPlayer#selectCasualties()` returns `null`.

**Comment by ron-murhammer** [comment] 2017-08-17 04:19
@ssoloff Makes sense. I guess the question is what changed since the current release version? Was this method updated so that it could return null? Was the calling code updated to not handle the null?

**Comment by ssoloff** [comment] 2017-08-17 04:30
@ron-murhammer I'm not exactly sure.  Looking at the corresponding `BattleCalculator` and `BattleDisplay` code at tag 1.9.0.0.3635, I don't see any significant differences.  That is, it looks like `BattleDisplay#getCasualties()` can return `null`, and `BattleCalculator#selectCasualties()` does not handle a `null` return value.

When I run the repro steps on 1.9.0.0.3635, I get the same behavior as reported above **except** for the NPE.  That is, the two `ConcurrentModificationException`s occur, the battle window stays open after returning to the main menu, and I can't close it.  I'll try running 3635 through the debugger to see why the NPE isn't triggered.

**Comment by ron-murhammer** [comment] 2017-08-17 04:31
@ssoloff Interesting as when I test on 1.9.0.0.3635, everything works fine and I don't see any exceptions.

**Comment by ssoloff** [comment] 2017-08-17 04:37
@ron-murhammer Should have mentioned I was testing on Linux.  When I test 3635 on Windows, I also don't see a problem.  Hmmm...

Stepping through the debugger with 3635 on Linux, the NPE _is_ being triggered; it's just not being output to the console.  I remember a few months ago fixing some Checkstyle warnings where we were completely swallowing exceptions, and I fixed them by adding some `ClientLogger` calls.  I suspect whatever handler is catching this particular NPE was one of those that I fixed.

**Comment by ron-murhammer** [comment] 2017-08-17 04:47
@ssoloff Probably a good hypothesis and I do agree it appears the NPE was already possible in the current release but probably was swallowed up somewhere. It'd be nice to confirm the change the caused it to be thrown now though it terms of fixing my thought is to just initialize the CasualtyDetails() so it can't be returned as null.

**Comment by ssoloff** [comment] 2017-08-17 05:52
@ron-murhammer My theory about the NPE being swallowed in 3635 is wrong.  There seems to be something fundamentally different in how the battle is run between 1.9.0.0.3635 and 1.9.0.0.6200 that causes the NPE to be propagated differently.

Here's the stack trace for the NPE from 1.9.0.0.3635:

```
Thread [Triplea start thread] (Suspended (breakpoint at line 541 in BattleCalculator))	
	BattleCalculator.selectCasualties(String, PlayerID, Collection<Unit>, Collection<Unit>, PlayerID, Collection<Unit>, boolean, Collection<Unit>, Territory, Collection<TerritoryEffect>, IDelegateBridge, String, DiceRoll, boolean, GUID, boolean, int, boolean) line: 541	
	Fire.selectCasualties(IDelegateBridge) line: 177	
	Fire.access$1(Fire, IDelegateBridge) line: 101	
	Fire$2.execute(ExecutionStack, IDelegateBridge) line: 243	
	ExecutionStack.execute(IDelegateBridge) line: 35	
	MustFightBattle.fight(IDelegateBridge) line: 392	
	BattleDelegate.fightBattle(Territory, boolean, IBattle$BattleType) line: 227	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	DelegateExecutionManager$1.invoke(Object, Method, Object[]) line: 148	
	$Proxy4.fightBattle(Territory, boolean, IBattle$BattleType) line: not available	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	EndPoint.invokeSingle(RemoteMethodCall, Object, INode) line: 172	
	EndPoint.invokeMultiple(RemoteMethodCall, INode) line: 150	
	EndPoint.invokeLocal(RemoteMethodCall, long, INode) line: 132	
	UnifiedMessenger.invokeAndWait(String, RemoteMethodCall) line: 101	
	UnifiedInvocationHandler.invoke(Object, Method, Object[]) line: 50	
	$Proxy4.fightBattle(Territory, boolean, IBattle$BattleType) line: not available	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	GameOverInvocationHandler.invoke(Object, Method, Object[]) line: 162	
	$Proxy4.fightBattle(Territory, boolean, IBattle$BattleType) line: not available	
	TripleAPlayer.battle() line: 484	
	TripleAPlayer.start(String) line: 131	
	ServerGame.waitForPlayerToFinishStep() line: 531	
	ServerGame.runStep(boolean) line: 424	
	ServerGame.startGame() line: 272	
	LocalLauncher.launchInNewThread(Component) line: 61	
	LocalLauncher(AbstractLauncher).lambda$0(Component) line: 43	
	155363318.run() line: not available	
	Thread.run() line: 748	
```

and here's the stack trace for the NPE from 1.9.0.0.6200:

```
Thread [Triplea start thread] (Suspended (breakpoint at line 532 in BattleCalculator))	
	BattleCalculator.selectCasualties(String, PlayerID, Collection<Unit>, Collection<Unit>, PlayerID, Collection<Unit>, boolean, Collection<Unit>, Territory, Collection<TerritoryEffect>, IDelegateBridge, String, DiceRoll, boolean, GUID, boolean, int, boolean) line: 532	
	Fire.selectCasualties(IDelegateBridge) line: 166	
	Fire.access$1(Fire, IDelegateBridge) line: 98	
	Fire$2.execute(ExecutionStack, IDelegateBridge) line: 228	
	ExecutionStack.execute(IDelegateBridge) line: 41	
	MustFightBattle.fight(IDelegateBridge) line: 400	
	BattleTracker.fightBattleIfOnlyOne(IDelegateBridge) line: 1178	
	BattleDelegate.start() line: 103	
	ServerGame.startStep(boolean) line: 511	
	ServerGame.runStep(boolean) line: 407	
	ServerGame.startGame() line: 271	
	LocalLauncher.launchInNewThread(Component) line: 61	
	LocalLauncher(AbstractLauncher).lambda$0(Component) line: 51	
	1031859907.run() line: not available	
	Thread.run() line: 748	
```

You'll observe that in 3635, the battle step is running during `ServerGame#waitForPlayerToFinishStep()`, while in 6200, the battle step is running during `ServerGame#startStep()`.  When run in `waitForPlayerToFinishStep()`, the delegate is invoked through the messaging system, whereas when run in `startStep()`, the delegate is invoked directly.

Because 3635 is running through the messaging system, the NPE gets intercepted and wrapped in an `InvocationTargetException`.  The ITE eventually gets handled in `DelegateExecutionManager#createInboundImplementation()`.  This handler calls `assertGameNotOver()`, which because `m_isGameOver` is `true`, throws a `GameOverException`, thus discarding the NPE.  So now we at least know why the NPE doesn't make it to the console on 3635.

The obvious question is why does the battle run during `ServerGame#startStep()` in 6200 but during `ServerGame#waitForPlayerToFinishStep()` in 3635?  The only thing I could find is commits 5a42315 and 685280d, which seem to run the battle during `startStep()` if there is only a single battle to fight (which is the scenario I've been testing).  **Sure enough, if I fight two battles, and then leave the game when prompted to choose casualties from the first battle, I do not get an NPE.**

I don't think there's anything wrong with the referenced commits--they simply exposed the NPE by running the code in a different context.  However, I don't know this part of the engine well, so I'll let others comment on whether or not we should be running a battle from `startStep()`.

Regardless, I think your suggestion to always return a non-`null` `CasualtyDetails` is a good idea, and I'll look into that sometime tomorrow.

**Comment by ssoloff** [comment] 2017-08-17 17:31
I've attached a [save game](https://github.com/triplea-game/triplea/files/1232104/issue-2225.tsvg.zip) that can be used to reproduce the NPE and verify when it has been fixed.

1. **Open Saved Game > Start Local > Play**.
1. Wait for game to load.
1. Click **Done** to end combat move phase.
1. Battle window will be displayed; wait for prompt to select casualties.
1. From main menu, select **File > Leave Game**; click **Yes** when asked to confirm leave game.

Console will open here with the NPE.

**Comment by ssoloff** [comment] 2017-08-18 05:47
I checked this on Linux one last time in the 1.9.0.0.6225 release.  Everything looks good.  Please re-open if anyone still experiences this issue on other platforms.

**Closed by ssoloff** 2017-08-18 05:47 UTC
Labels: regression, type: bug
