### ISSUE TITLE
Arrow drawing bug- unnecessary horizontal line being drawn

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#1056] opened 2016-08-13 12:46 UTC
I installed “triplea_windows-x64_1.9.0.0.2728.exe”.

I don’t have any other versions installed at the moment, so this version is where can see the bug, but I don’t know if it is an older bug. It is also present and can be reproduced in the tutorial map.

The short version:
If a units moves from one place to another, generating an arrorw, and both ends of the arrow can be displayed inside the viewable area, then everything is OK.

But if one of the ends of the arrow is outside the viewable area in the west/left direction, then the end of the arrow in that direction is moved to a far-right/far-east destination.

It seems that it does not matter if it is the pointy or round end of the arrow that gets hidden from view, the error is the same.

I made a screen recording of the bug to supplement these pictures. (8 MB, MP4)
Showing is so much easier then telling :-)
https://dl.dropboxusercontent.com/u/91867373/ArrowBug.mp4

Before the left side of arrow is hidden, all is good:
![bug1](https://cloud.githubusercontent.com/assets/15268177/17643250/71e62fd4-6164-11e6-979d-88ec3d80ae64.png)
After hiding the left side, the arrow bug is seen:
![bug2a](https://cloud.githubusercontent.com/assets/15268177/17643247/47db1b32-6164-11e6-908c-348ceb1fc7d2.png)

**Comment by ron-murhammer** [comment] 2016-08-13 17:38
@FrostionAAA Yeah, I noticed this as well. We'll need to fix this.

**Comment by RoiEXLab** [comment] 2016-08-13 18:29
I hate Math for this particular case...
The Problem is clear to me as I was working on the "new" Arrow/Path UI...
On infinite-scrolling Maps the Point Coordinates are not the same like the screen coordinates, e.g. a USA in the east has the same Map-Coordinates as the same USA in the west, but the Screen coordinates differ.
In order to have a straight line between coordinates unlike #863 I implemented a system which "corrects" the screen coordinates if the map coordinate is off-screen...
The Route is not coming from nowhere, it's actually coming from the same map-coordinate, but a different screen coordinate, the one in the east.

@DanVanAtta @ron-murhammer 
If you may have a look at RouteDrawer.java, you may notice that this correction is done for all points each...
If you have any theoretical ideas on how to solve this, please let me know...

**Comment by ron-murhammer** [comment] 2016-08-15 04:09
@RoiEXLab Would it be possible to write a unit test that fails because of this issue?

**Comment by DanVanAtta** [comment] 2016-08-15 04:44
@ron-murhammer I am concerned that we will not be able to catch this bug via unit test effectively without some major work. A patch fix would be good here if it allows for this feature to catch the 1.9 train. Otherwise we're at a point where features that fail get Q/A are going to be reverted, instead of being patched. We need to get 1.9 out.

**Comment by ron-murhammer** [comment] 2016-08-15 05:10
@DanVanAtta Agree and I'm fine reverting the route draw changes if necessary.

**Comment by RoiEXLab** [comment] 2016-08-15 07:16
@DanVanAtta @ron-murhammer
A fix wouldn't be too hard... The only thing I'm struggling with is what exactly to check...
How does the left point differ from the right one?
Is it nearer to to middle of the screen? Is it nearer to the next point (if so, what is the next point)?

**Comment by RoiEXLab** [comment] 2016-08-15 07:17
I'll try to get a PR out today...

**Comment by RoiEXLab** [comment] 2016-08-15 09:34
#1065 has a fix

**Comment by RoiEXLab** [comment] 2016-08-16 06:35
This should be fixed now, please close the issue then

**Comment by RuinChristmas** [comment] 2016-08-29 13:01
is this the same issue?

![arrow](https://cloud.githubusercontent.com/assets/17838115/18052242/cd69d6c4-6dbe-11e6-9b60-1c3fcc0fa045.jpg)

**Comment by RoiEXLab** [comment] 2016-08-29 15:50
No it's not, but somewhat related... This happens very rarely to me, and when it does I cannot reproduce it. This has a lower priority... But I will see what I can do once I'm back home

**Comment by RuinChristmas** [comment] 2016-08-29 16:07
@roi if you play revised, set the other players to AI and move the fighter
like that I think it always happens

**Comment by RoiEXLab** [comment] 2016-08-29 19:14
Ok then...
@DanVanAtta @ron-murhammer
If this issue is urgent, the method that is not properly working is the normalize(all)lines method... This Method is supposed to make the lines go through map borders. 
I would like to help, but without my PC I'm only half a developer.

**Comment by DanVanAtta** [comment] 2016-08-29 21:25
Does not sound like it is terribly urgent. A point fix is going to be acceptable enough. Going forward the key will be to preserve lobby->client compatibility, and save game compatibility.

**Comment by Cernelius** [comment] 2016-09-05 04:44
Looks like it is just broken for whatever wrapping path, except maybe the ones wrapping on both axis (I see that "HexGlobe FFA" is fine). Since TripleA maps normally wrap, I'm not sure if this is can be even called an improvement over the stable, all around.

![01](https://cloud.githubusercontent.com/assets/19562310/18237453/fdd7c3d4-7331-11e6-9a74-5c4f7d795400.png)

![02](https://cloud.githubusercontent.com/assets/19562310/18237468/21f4f12e-7332-11e6-8434-bdd07b848df9.png)

![03](https://cloud.githubusercontent.com/assets/19562310/18237499/79037486-7332-11e6-9880-6d6328d06059.png)

![04](https://cloud.githubusercontent.com/assets/19562310/18237572/8368ece8-7333-11e6-9f2b-3c682d48bd6d.png)

Are you sure you want to release this?

**Comment by DanVanAtta** [comment] 2016-09-05 06:02
how common is the problem exactly? is it just the one rare path??

@RoiEXLab , thoughts on how to fix?

**Comment by DanVanAtta** [comment] 2016-09-05 06:11
looks whenever there is a route from the left of the map seam going to the right of it, the direction is reversed.

Should be an easy enough of a fix it looks, once we spot where the problem is.

![screenshot from 2016-09-04 23-09-37](https://cloud.githubusercontent.com/assets/12397753/18238735/d4f5abf8-72f4-11e6-96b7-d7c1e3b3f546.png)
![Uploading Screenshot from 2016-09-04 23-09-48.png…]()

**Comment by Cernelius** [comment] 2016-09-05 07:12
Sorry, just noticed that the problem exists for HexGlobe FFA too, on the X axis; just not on the Y axis.

So, I guess the only wrapping maps that would be unaffected would be those with Y only (not X) scrolling.

I suggest you use HexGlobe FFA as the main referring game for this issue.

**Comment by DanVanAtta** [comment] 2016-09-06 01:48
#1199 has a fix for the horizontal case. On hexglobe, it looked like things were fine, but I would not be 100% surprised if the vertical case had issues.

**Comment by RuinChristmas** [comment] 2016-09-11 02:09
It works now if you go directly there but if you move a fighter from hawaii towards china, then wait, decide you want it in ECan, you get this:
![us1](https://cloud.githubusercontent.com/assets/17838115/18414717/954c9552-779a-11e6-9925-a5fa9d8b7db7.png)
If you go around the world, in 1.8.0.9, it draws a neat arrow but now does this:
![us1a](https://cloud.githubusercontent.com/assets/17838115/18414718/b41a24a4-779a-11e6-9c96-e4122af84bdf.png)

**Comment by Cernelius** [comment] 2016-09-12 00:59
I confirm what Ruin says.

There is something serious bugging off when you select an unit and go around with the mouse to possible destinations (nobody else but this: not clicking anything else but the initial selection of the unit), and it happens even if you never actually try to wrap around a border.

For example, here the Yamamoto submarine seems convinced that the best way of going to an adjacent sea zone (I didn't set any path with Ctrl or anything) is by going 24 times around the world:

![pathfinder](https://cloud.githubusercontent.com/assets/19562310/18421907/6c97a962-7894-11e6-96c3-e64b322140ed.jpg)


I surmise that you need to make sure that the path is given at any time regardless of what paths were given in the past, as it seems the previous ones somewhat influence the current one for no reasons.
In the above case, I obtain that if I previously go around with the mouse, while it doesn't happen if I only move it from the starting to the ending sea zone.
It looks like the previous paths leak into the new ones.

**Comment by RoiEXLab** [comment] 2016-09-12 04:21
@DanVanAtta what have you done? You created a monster! 
I'd suggest reverting you fix + my cleanup PR in order to create a new, better fix

**Comment by ron-murhammer** [comment] 2016-09-12 04:24
Yeah, this I think is the only showstopper bug we have left.

**Comment by DanVanAtta** [comment] 2016-09-12 04:31
@RoiEXLab , please double check which updates introduced this. The update I applied a week ago made the problem a lot less likely.

**Comment by DanVanAtta** [comment] 2016-09-12 04:40
@Cernelius , from which SZ is the sub in? I was not able to repro. 

I've only been able to reproduce when the unit is very far from the map 'seam'. Which is a rare thing. @ron-murhammer , we can fix this in a point release since no game data is involved. Hence I do not think it is a show stopper.

**Comment by RoiEXLab** [comment] 2016-09-12 04:40
@DanVanAtta Sorry, if I'm wrong at some point...
AFAIK There was this "small" bug which had this single line in some cases. I think the bug seen now is the result of #1199

**Comment by DanVanAtta** [comment] 2016-09-12 04:42
"this single line in some cases"

Which single line? Which "small" bug?

**Comment by RoiEXLab** [comment] 2016-09-12 04:43
@DanVanAtta I mean the Screenshot sent by @RuinChristmas

**Comment by DanVanAtta** [comment] 2016-09-12 04:45
I was able to repro the screenshot from @RuinChristmas .  That was a problem before #1199. The move in that screenshot is not a valid move. Hence, this issue AFAIK is going to be pretty rare to hit.  I'm concerned by Cernel's report that he can hit it with movement to an adjacent territory (which I have not been able to repro, hoping for some more info)

**Comment by DanVanAtta** [comment] 2016-09-12 06:34
@Cernelius can you give details on how you were able to get the screenshot above, which SZ was the sub in to start with? I put a sub in every pac SZ in that region and could not hit the route wrapping problem.

**Comment by Cernelius** [comment] 2016-09-12 07:39
Of course, I'm using the latest prerelease (3154).

As I said, it is a thing that sums up, so I cannot reproduce it exactly as before, unless I like make the same moves, I guess.

Just select the submarine and move the mouse around (nothing else!); you should soon see horizontal lines piling and piling up in a neverending stream of red spaghetti.

It always happens in a different way, like:

![bug_path_02](https://cloud.githubusercontent.com/assets/19562310/18428088/4bb4fd7a-78cc-11e6-8c36-467a3cddaf45.png)

or:

![bug_path_03](https://cloud.githubusercontent.com/assets/19562310/18428124/8c48806e-78cc-11e6-884d-07bd963a7014.png)

And, yes, never happened with the current release.

**Comment by DanVanAtta** [comment] 2016-09-12 07:44
Still, not seeing it. Please give  step by step instructions if you would @Cernelius . Which SZ is the sub in?

**Comment by DanVanAtta** [comment] 2016-09-12 07:52
Okay, hit it. Looks like first you have to move the mouse cursor and route to be very far away, scrolling around the map. Once triggered, adjacent territories no longer have their routes drawn correctly.

**Comment by Cernelius** [comment] 2016-09-12 08:11
Ah yeah, forgot to say that the map was zoomed 50% (as you can see). You are unlikely to hit it if that one is at 100%, I guess, but it is quite easy at 50%.

**Comment by Cernelius** [comment] 2016-09-12 08:16
And, yes, it starts from a move somewhere illegal, and then it continues when you go legal, but this is very easy to it in WAW, because you hit the islands or the borders that are a "none" spot; I don't really know which one of the two causes it.
The more you move around, the more they sum up.

**Closed** 2016-09-14 05:10 UTC
Labels: Bug Backlog, Close Pending Confirmation
