### ISSUE TITLE
6157 - odd UI look for place units dialog

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2215] opened 2017-08-15 18:19 UTC
![weird_place_units_dialog](https://user-images.githubusercontent.com/12397753/29329663-73b5c2f8-81ab-11e7-9c58-fdbe8d6a1c66.png)

1. The 'Choose Units' text field looks odd, should the background color match the text box?
2. Should we be using a text field at all for 'choose units', maybe an `<h1>` label might be more appropriate? At that, do we really need the 'choose units' text field at all? The window title seems to be the thing to serve that purpose, the text field 'choose units' is a bit redundant.

**Comment by Cernelius** [comment] 2017-08-15 23:59
Just remove the "Choose units" box and text.

**Comment by Cernelius** [comment] 2017-08-16 00:11
Also, if this issue can be reformulated about anything regarding the "Place units" window, I would add that it is weird you can click "OK" when you have none selected. While technically it is true that you are deciding to place nothing, in this case clicking "OK" and clicking "Cancel" is the same, thus you have the option of two different buttons for doing the same thing, which is strange.
Also considering that it is not like that if you click on "OK" with none selected then it is recorded in history that you have placed none at that point, I definitely suggest the "OK" button being not clickable when you have none selected (you can click only on "Cancel").

Also, I don't like "OK" as a word; it is too informal: I would never use it.

**Comment by ron-murhammer** [comment] 2017-08-16 02:26
@DanVanAtta It looks considerably better on the Substance Graphite L&F. Given that I think we are going to reinstate that as the default for now, I'd say to just close this:
![image](https://user-images.githubusercontent.com/1427689/29344851-5393a17a-8200-11e7-8051-2a38f3059e32.png)

**Comment by DanVanAtta** [comment] 2017-08-16 03:04
> Substance Graphite L&F. Given that I think we are going to reinstate that as the default for now,

That is likely to be very temporary, my understanding is we will go to Nimbus. Even with the more cohesive colors, the label is still weird. It's a quick fix, I don't think it's worth debating when to fix it, let's jsut fix it.

**Comment by ssoloff** [comment] 2017-08-16 03:05
@DanVanAtta It looks like you are using Nimbus.  I noted elsewhere that I observed Nimbus does not use a different background color for read-only vs writable text areas, and that's why I switched over to Metal when I was testing the new settings window.  So, item (1) is really out of our control (i.e. I don't think we should be tweaking colors to compensate for one L&F).

(For whatever reason, someone added the line `title.setBackground(this.getBackground());` to `UnitChooser`.  I removed that line and confirmed that the background is still the same color under Nimbus.)

Regarding item (2), my guess is someone copy-pasted a lot of this code from a similar dialog, probably one that had much more text in the `title` field.  I see no reason why this control should even be a `JTextArea`.  A `JLabel` would probably be more appropriate.  Switching to a `JLabel` would also make item (1) moot as the control background will be transparent:

![choose-units-with-label](https://user-images.githubusercontent.com/4826349/29345575-bf5f6cb0-820d-11e7-9c7b-226f92d52cf3.png)

(It probably could use some extra bottom margin though.)

**Comment by DanVanAtta** [comment] 2017-08-16 03:34
My initial reaction is to remove the extraneous text altogether, less is more. Then again, I'm not the one testing and pushing a fix for it at the moment :grin:

**Comment by ssoloff** [comment] 2017-08-16 03:43
> My initial reaction is to remove the extraneous text altogether, less is more.

That was @Cernelius's suggestion, as well.  I agree the "title" text area offers very little beyond the dialog title itself.

**Comment by ssoloff** [comment] 2017-08-16 05:04
Upon further investigation, it appears the title text area can contain other (possibly much longer) messages than just "Choose units."  There are six calls to `UnitChooser#setTitle()` throughout the UI code that ultimately change the title that is displayed.

Therefore, I don't think we can remove the text area, nor switch to a `JLabel` given the unknown length of the text.  Are there any other suggestions or do we just leave it as-is?

**Comment by DanVanAtta** [comment] 2017-08-16 05:25
API change is out of the question?

**Comment by ssoloff** [comment] 2017-08-16 05:28
@DanVanAtta Not sure what you mean by an API change in this context.  Could you please elaborate?

**Comment by DanVanAtta** [comment] 2017-08-16 05:47
Instead of calling ` UnitChooser#setTitle() `, can we update the necessary to call a new method on `UnitChooser` that would suppress the extraneous text box?

**Comment by ssoloff** [comment] 2017-08-16 06:06
@DanVanAtta If I understand you correctly, you don't want the default "Choose units" message to ever be displayed, but if `setTitle()` is called explicitly, then the message passed to that method should be displayed.  Is that correct?

Just for completeness, here's some of the other messages displayed in that text area via `setTitle()`:

* "What transports do you want to load"
* "What transports do you want to unload"
* "Select air transports to load"
* "Load air transports"
* "Attackers Fire"
* "Defenders Fire"
* "Select \<diceHits\> casualties from aa fire in \<territoryName\>"

**Comment by DanVanAtta** [comment] 2017-08-16 06:14
Sorry, I'm not thinking about this terribly deeply. It seems like we should be able to get it so at least this particular code path would not render the extra "Choose Units" text area. That's all I'm saying. I suspect an easy and really dirty solution would be to copy/paste more so this is not a shared code path anymore so we can have a version without the  extraneous UI components.

**Closed** 2017-08-17 03:09 UTC
Labels: category: game engine > UI, type: usability

**Comment by RoiEXLab** [comment] 2017-08-17 03:10
Feel free to reopen if you believe the changes in #2240 are not sufficient
