### ISSUE TITLE
TripleA 2.2 Release

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#7246] opened 2020-07-25 04:24 UTC
I'd like to cut a 2.2 release next week or early the following so that players can pick up the latest bug fixes.

**Comment by beelee1** [comment] 2020-07-25 05:09
This would not be a prerelease then ? But saves still work ? I know #7227 was gonna fix some stuff, specifically #7177 but had some compatibility issues. #7237 addressed them. Personally I think it best to bite the bullet and do trevan's pr. It's a recent update/engine change/ thingy. Better now than a year from now :) Fewer will notice now, if any, imo.

At any rate, on a side note, I'm still working on being able to test it.

**Comment by tvleavitt** [comment] 2020-07-28 15:33
I think a new release should be a priority because (a) it will hopefully lower the volume of already addtessed bug reports evading the dedup function, and make it clear what issues persist,  and (b) the improvements we've made to the big reporting itself will come into play.

I don't think the debate over breaking compatibility with a small number of save games should delay things... if we release without the PR in question being merged, the status quo persists in relation to that issue, there's no regression from 365, and we have a known issue that we can document in the release notes. All the other benefits accrue. We can issue a "hotfix" via a point release if we don't want to increment the version number when this issue is resolved.

We also establish the principle that official releases are going to come at a faster pace than in the past, and typically be more incremental in their changes.

**Comment by DanVanAtta** [comment] 2020-08-01 21:45
Has anyone had a chance to do some quick smoke testing of the latest code? I think we probably should cut 2.2 as soon as this Monday.

**Comment by panther2** [comment] 2020-08-02 13:07
If it is not too much work, it would be great if this feature
https://forums.triplea-game.org/topic/2151/feature-request-reinstate-internal-dice-roller
could be (re-)included.

**Comment by DanVanAtta** [comment] 2020-08-02 22:23
I think that'll need to wait till 2.3.

**Comment by panther2** [comment] 2020-08-11 14:24
#7350 should be corrected before.

**Comment by DanVanAtta** [comment] 2020-08-13 03:08
@panther2 I agree #7350 is important, though 2.2 is about baked. It'll perhaps take 1-3 weeks to get #7350 fixed, meanwhile 2.3 would go out in 3-5 weeks. We're not really going to see much of a timing difference. I would absolutely agree to wait on 2.2 if #7350 was going to be a new problem introduced in 2.2.

**Closed** 2020-08-13 03:08 UTC
Labels: Discussion

**Comment by Cernelius** [comment] 2020-08-13 11:05
Just letting you know that I'm not sure if you forgot to unpin the issue (is there a way to have issues automatically unpinned when closed?).

**Comment by panther2** [comment] 2020-08-13 15:14
@DanVanAtta Agreed, where do we list the issues to be fixed for 2.3?

**Comment by DanVanAtta** [comment] 2020-08-13 15:41
@panther2 as separate github issue reports for each one.

All of the 2.0 and 2.1 error report uploads will be closed pretty soon so we can clear up the list and focus on the problems coming from 2.2. If it feels like the issues would get lost we can certainly discuss a labeling strategy or to create a 2.3 project which can also be used to link issues together (the project might be the best route actually rather than a unique label).

**Comment by panther2** [comment] 2020-08-13 20:09
@DanVanAtta I just want to make sure that #7350 and especially this feature:
https://forums.triplea-game.org/topic/2151/feature-request-reinstate-internal-dice-roller
don't get lost when talkin about 2.3.
There is not even an issue for the latter, as feature requests are supposed to be noted in the forum - and the current complexity of the issue-lists invites to oversee some, too ...

**Comment by DanVanAtta** [comment] 2020-08-19 00:42
@panther2 A `2.3` project is created, #7350 is linked to it and there is a TODO card for the internal dice-roller item: https://github.com/triplea-game/triplea/projects/18#card-43902730
