### ISSUE TITLE
Dice server reported problem

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#1668] opened 2017-04-28 22:53 UTC
"I'm trying to get started with TripleA, and I'm stuck at the dice server. When I try to register my two email addresses, I put in an address, click register, and then I get a white screen. I don't receive any email from the server to confirm a registration (is that what's supposed to happen next?), and when I try to test the server from within TripleA, it tells me the addresses are unknown. It sounds like MARTI is going through a rough patch - is there another server that can be used? Any help would be much appreciated. Thanks!!"

@RoiEXLab 

Is there an issue with registration too? I'm seeing the same behaviour.

**Comment by ssoloff** [comment] 2017-04-29 04:35
Yup, server is returning `500`:

```
$ curl -i --data "email=steven.soloff%40gmail.com" https://dice.tripleawarclub.org/register.php
HTTP/1.1 500 Internal Server Error
Server: nginx/1.10.0 (Ubuntu)
Date: Sat, 29 Apr 2017 04:31:44 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive

<html>
<head>
	<title>Register your email for MARTI services</title>
</head>
<body>
```

Just in case, I also confirmed this is happening on the HTTP endpoint.

**Comment by RoiEXLab** [comment] 2017-04-29 08:24
Dice server seems to be working again...
I just needed to change `require_once("dice.class.new.php")` to `require_once("dice.class.php")` in order to fix the issue...

**Comment by panther2** [comment] 2017-04-29 11:40
@RoiEXLab 

I am afraid it does not. 
Reported on aaa.org some minutes ago:

> Well, I got a little further this time, but not much. The blank white screen now contains the message, "Email delivery failed, try again later," for both of my addresses. I'll try later...

**Comment by RoiEXLab** [comment] 2017-04-29 12:54
Finally, I got it working!
Registration should work fine again...

Whoever code this ****** PHP code, has some bad PHP-Coding habits...

**Comment by panther2** [comment] 2017-04-29 14:09
Looks good, thanks!

**Comment by RoiEXLab** [comment] 2017-05-02 02:10
@simon33-2 would you mind closing this issue?

**Closed** 2017-05-02 04:00 UTC
