### ISSUE TITLE
2.6.39 game is slow

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#8790] opened 2021-02-05 10:56 UTC
There is no error, just an overall feeling the game has slowed down from 2.5.22294, specifically.

- When selecting just one unit to move to a territory there is an unacceptable delay in the unit actually moving.
- Moving around the map is sluggish and you can see the tiles being drawn.

Everything appears slow, the above is so bad it is unplayable.

**Comment by DanVanAtta** [comment] 2021-02-05 18:01
- Which map do you observe this on? Which maps have you tried?
- Have you checked available memory when the game is running slow, is there a lot of memory allocated to TripleA?
- Can you check CPU usage when the game is running slow, do you see high or low CPU usage?
- Have you observed this in other 2.6 releases?
- Are you playing in the lobby, or single player?
- Does the slowness kick in consistently and every time you start a game? Even after a fresh computer restart?

**Comment by TheDog-GH** [comment] 2021-02-05 18:44
I have only tried it on Settlers:Age of Tribes, this is the only one, but
it has played "normal" before 2.6, it runs as expected  fast as usual on
2.5.22294
Yes I checked available memory, it had about 60% used, just over 1Gb was
allocated to TripleA
When the AI has its turns it runs at 100% CPU.
I jumped from 2.5.22294 to 2.6.39 release, so no I did not observe any
other v2.6
This is a local single play v 5 Hard AI
This slowness is all the time, even after a restart of the game, even after
a save game,  even after a reboot of the PC, it is constantly sluggish.

I had some Beta features turned on, I turned them off and observed the
above.

I dont play other games often enough, other than my own, to notice any
speed differences.

**Comment by DanVanAtta** [comment] 2021-02-06 19:24
@TheDog-GH until we isolate the cause of the slow-down, this will be next to impossible to fix. Either we need to reproduce this and/or isolate the set of changes that resulted in the slow-down.

While we work on a reproduce, would you be willing to try and find the release where you first see this problem? To do that, download the release that is half way between the latest and the last release, see if you get the problem there. If yes, then go half way between that release and the latest release. Repeat until you isolate which release causes the problem. FWIW, using this process you should be able to find the exact release after around 6-9 tries.

**Comment by TheDog-GH** [comment] 2021-02-06 23:07
Yes I will do this.

It will take me a few days I hope/guess, its something I can do to help :-)

**Comment by DanVanAtta** [comment] 2021-02-06 23:44
To help, @TheDog-GH , here is a list of release URLs:

[release-list.txt](https://github.com/triplea-game/triplea/files/5937870/release-list.txt)

**Comment by TheDog-GH** [comment] 2021-02-07 11:00
2.6.13@57528d46ee plays at its usual full speed.
2.6.33.8af5587ac3 plays SLOW as posted above.

Only 5 downloads I got lucky!

In my game, as its random start, turn 1 place units, turn 2 move, so it happens when moving units, so it is easy to spot and then the game plays but is very sluggish.

**Comment by DanVanAtta** [comment] 2021-02-07 23:05
@TheDog-GH good work.
Please give this release a try: https://github.com/triplea-game/triplea/releases/tag/2.6.57%40a614e2bb33, I think it should have the problem fixed

**Comment by TheDog-GH** [comment] 2021-02-08 09:35
Its a bit better, but it is still slow compared to 2.5.22294

As my maps have a random start, I switched to an unpublished map, that has fixed starting territories that are about 4 territories away from the enemy.  This means the AI spends most of its time just moving and buying.

With a stop watch, for 6 Hard AI mainly moving and buying, from pressing [Play] button.
2.5.22294 to complete 5 turns   43 seconds
2.6.13       to complete 5 turns   52 seconds           -  I originally thought played at full speed
2.6.33       to complete 5 turns 175 seconds
2.6.57       to complete 5 turns 102 seconds

**Comment by TheDog-GH** [comment] 2021-02-15 09:19
2.6.72       to complete 5 turns 102 seconds

**Comment by FrostionAAA** [comment] 2021-02-20 11:28
Holy moly … some of the changes made in 2021 to the engine has really slowed it down. I just tried to start up a game of Warcraft War Heroes, and it is practically impossible with engine v2.6.76. I really hope that the issue investigated here, is the same issue that now seems to bug the Warcraft map, so that we can get it fixed.

I have not tried any other trigger heavy maps, but I fear it will be the same.

It really seems like some sort of memory thing with TripleA, as during the attempted upstart of the Warcraft map, just navigating the game menus and clicking buttons had a delay of several seconds. For example I went in the engine options to speed up AI calculations, and there were waiting times while windows opened and when clicking buttons. Map never loaded but ends up frozen ... CTRL + ALT + DEL and forced shut down was the only escape. I will try to restart my PC and try other maps.

**Comment by FrostionAAA** [comment] 2021-02-20 14:32
In my efforts to get the Warcraft map working again I have tracked down the latest TripleA engine that allows the map to run, without it freezing during startup:
https://github.com/triplea-game/triplea/releases/tag/2.6.22589 … is the latest working engine.
https://github.com/triplea-game/triplea/releases/tag/2.6.7%40e2c7c416a4 … is the first following engine build after the working, and does not allow the map to run (or at least slows it down to a point where it freezes).

**Comment by DanVanAtta** [comment] 2021-02-20 23:22
@FrostionAAA is [2.6.7](https://github.com/triplea-game/triplea/releases/tag/2.6.7%40e2c7c416a4) the last good version you found, or first bad version?

**Comment by FrostionAAA** [comment] 2021-02-20 23:56
@DanVanAtta version 2.6.22589 is the last working version that allows the Warcraft map to run. At least on my PC, I have not gotten any later version to work. I cant say if later versions are able to start up the Warcraft map on other computers.

**Comment by TheDog-GH** [comment] 2021-02-21 00:45
2.6.72 & Warcraft map is running on my PC, but very slowly, as in unacceptably slow.
CPU is around 32%, and RAM just under 2.3GB used, this is just placing units.
Off to bed now, I will give an update tomorrow.

**Comment by TheDog-GH** [comment] 2021-02-21 09:12
At the point of Frostions "freeze" I think I went to bed.
The Task Manager said that CPU and RAM were changing, so I think it was working on something, but very slowly.
"Freezing", pre phase 1, during or just after Placing Units, so could be just before Human Choose Origin.

On the Forums, down at the moment of writing, so I cannot link to his Warcraft thread, Frostion mentioned that the "air ways" were working, so the AI will have lots more to calculate, could this be part of the problem?

**Comment by TheDog-GH** [comment] 2021-02-21 09:16
[](https://forums.triplea-game.org/topic/1031/warcraft-war-heroes-official-thread/302)

Frostion said this on the forums
For play against the AI, I see this version as best:
https://github.com/triplea-game/triplea/releases/tag/2.6.22444
as this version (released just after the above) is the first engine with the important AI-update that prevents AI from stacking units in Horde capitals (and other territories with land canal attachments). An issue that always made the AI lose in the long run. Sadly, this engine version is also the first to have the “NEXT” and “PREV” unmoved unit buttons removed.

**Comment by DanVanAtta** [comment] 2021-02-27 05:42
This update should help if not get back to where we were performance-wise: https://github.com/triplea-game/triplea/pull/8921

**Comment by TheDog-GH** [comment] 2021-02-27 09:52
> 2.5.22294 to complete 5 turns   43 seconds
> 2.6.13       to complete 5 turns   52 seconds           -  I originally thought played at full speed
> 2.6.33       to complete 5 turns 175 seconds
> 2.6.57       to complete 5 turns 102 seconds

**2.6.35       to complete 5 turns   55 seconds**

++Good, thanks DanVanAtta, still not as fast as v2.5.22294 but it is over 5 turns, so +2 seconds per turn.  My test map is very simple compared to Frostions Warcraft map, so I hope more complex maps dont suffer.

Does this version, 2.6.35 include Frostions land canal attachments?

**Comment by DanVanAtta** [comment] 2021-02-27 19:22
43s vs 55s is certainly much closer. What is the measurement error? If you run the same experiment multiple times, how consistent are those numbers?

**Comment by TheDog-GH** [comment] 2021-02-27 22:19
Initial values plus 6 more
```
v 2.5.22294 43 40 44 40 45 44 45 mean = 43
v 2.6.35       55 51 46 49 48 45 47 mean ~ 49
```

**Comment by DanVanAtta** [comment] 2021-02-28 19:45
Between the two diffs, are really only the first inclusion of the engine to read map and game name from 'map.yml'. To do that, the engine was scanning the downloaded-maps folder. This was done to render tooltips for every unit, even when the tooltip was not displayed. This implies that if you had 1000 units, the engine was going to scan the file system 1000 times. That is now all fixed up so that operation is constant time instead of linear.

I suspect the additional 10% is coming from other changes that have occurred more recently. Closing for now, I'm not going to be able to track it down. Thank you for the performance measurements.

**Closed by DanVanAtta** 2021-02-28 19:45 UTC
