### ISSUE TITLE
Does Anyone Have a Mac

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#84] opened 2015-08-18 22:23 UTC
So we have a few users that are having technical difficulties with the latest release on a Mac. Does anyone have a Mac and can help debug?

**Comment by gaborbernat** [comment] 2015-08-19 08:47
I've installed a Hackintosh in a VMWare image for this purpose. But my MAC knowledge is rudimentary at best :)

**Comment by veqryn** [comment] 2015-08-19 20:18
@ron-murhammer: I believe I know what the issue is.

And when you installed git, you told it to 'checkout windows style line endings', but 'check in unix style line endings', right?  (This is the default choice when installing git on windows.)

This is what caused the issue: your git added the windows style line endings as it was checking out the files.  Then when you packaged up the files into the source zip, it kept them.


Here is what you need to do:
```git config --global core.autocrlf input
git config --get core.autocrlf
git checkout master
git reset --hard origin@{0}
git pull
```

or just start over, by doing the following
```git config --global core.autocrlf input
git config --get core.autocrlf
git clone git@github.com:triplea-game/triplea.git
git pull
```

**Comment by veqryn** [comment] 2015-08-20 18:27
Ok, so that was only 1 of the 2 issues.
The other issue was bugs introduced by our gradle patch: https://github.com/triplea-game/triplea/commit/3c3e6077a6a4f461c0500dbd733585daca675c33#diff-baafe2209ef3b890ea000d7dca31772a
These have been reverted (but of course, now gradle and travis don't work).

**Comment by DanVanAtta** [comment] 2015-08-26 23:09
Looks like we can close this.

**Closed** 2015-08-27 00:17 UTC
