### ISSUE TITLE
KeyListeners making typing a pain

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#5638] opened 2019-12-01 10:50 UTC
**Describe the bug**
I tested the dice server the other day and when I tried putting my email into the form the field lost focus for every dang key I pressed.
So in order to actually type something I had to type a character and klick into the text field for each one (but not too fast, because the I would've selected all the text inside the text field and overwrite it with the next kex I press).

So yeah, this is super annoying and definitely something to fix before releasing a new stable.

**Comment by DanVanAtta** [comment] 2019-12-01 16:58
Which email form exactly @RoiEXLab was this?

**Comment by RoiEXLab** [comment] 2019-12-01 16:59
![Screenshot](https://user-images.githubusercontent.com/8350879/69917257-47140180-1464-11ea-9da1-683109cb0594.png)
This one (made the screenshot in 1.9, so it may look slightly different in 2.0)

**Comment by DanVanAtta** [comment] 2019-12-01 18:20
Keybindings are added on game launch, the email screen is before then. We have some other problem going on. I disabled some of the likely suspects like document listeners, no luck isolating the problem.  I suspect we'll need to bisect this one to find the problem.

**Comment by DanVanAtta** [comment] 2019-12-28 15:03
@asvitkine @RoiEXLab will you have any capacity to investigate this?

**Comment by RoiEXLab** [comment] 2019-12-31 16:20
Maybe, I want to et my JavaFX changes done first, but after that I can check

**Comment by asvitkine** [comment] 2020-01-01 15:55
I can try to investigate, but I need more concrete repro steps. I have no idea how to use dice server, etc.

**Comment by RoiEXLab** [comment] 2020-01-01 16:00
@asvitkine Luckily no knowledge  is required.
Basically you start the game, click on this button:
![Screenshot](https://user-images.githubusercontent.com/8350879/71643291-14a23200-2cb8-11ea-92b3-b8cd383df906.png)
And then try typing something in the "To:", "Cc:" and "Game ID:" fields

**Comment by asvitkine** [comment] 2020-01-04 14:37
Thanks, easy to repro.

I tried bisecting to see when the error was introduced. Unfortunately, it seems a different error was introduced at some point (ConcurrentModificationException) and when that was fixed, this error happened.

The last good hash: b600a5e8b36f116a02a297ae880453ac5cdeea79
Introduction of ConcurrentModificationException: 895115ce1f517c7bedb46785cb0d8eb50b760507 
Fix for ConcurrentModificationException takes us to this state: a0e9242c3c5c541be518f03f541fe9a8cc45bb22

Per the above, assigning to @DanVanAtta

**Comment by asvitkine** [comment] 2020-01-04 14:46
Checking some more - the fix for the ConcurrentModificationException was to use CopyOnWriteArrayList.

If I take 895115c which introduced ConcurrentModificationException and patch in that fix (just use CopyOnWriteArrayList), that fixes the ConcurrentModificationException but has the error we're seeing at tip of tree. So that means that the other parts of 895115c introduced this unfocusing problem.

**Comment by asvitkine** [comment] 2020-01-04 17:29
Reverting SetupPanel to use Observer fixes the issue:

```
@@ -9,7 +9,8 @@ import java.util.ArrayList;
 import java.util.Collection;
 import java.util.List;
 import java.util.Map;
-import java.util.function.Consumer;
+import java.util.Observer;
+import java.util.concurrent.CopyOnWriteArrayList;
 import javax.annotation.Nullable;
 import javax.swing.Action;
 import javax.swing.JButton;
@@ -28,14 +29,14 @@ public abstract class SetupPanel extends JPanel implements SetupModel {
   private static final long serialVersionUID = 4001323470187210773L;
   private static final String SET_ALL_DEFAULT_LABEL = "Default";
 
-  private final List<Consumer<SetupPanel>> listeners = new ArrayList<>();
+  private final List<Observer> listeners = new CopyOnWriteArrayList<>();
 
-  public void addObserver(final Consumer<SetupPanel> observer) {
+  public void addObserver(final Observer observer) {
     listeners.add(observer);
   }
 
   void notifyObservers() {
-    listeners.forEach(consumer -> consumer.accept(this));
+    listeners.forEach(consumer -> consumer.update(null, null));
   }
 
   @Nullable
```

**Comment by asvitkine** [comment] 2020-01-04 17:31
Looks like maybe MainPanel is still expecting update() to be called and not accept()?

```
  @Override
  public void update(final Observable o, final Object arg) {
    setWidgetActivation();
  }
```

**Comment by asvitkine** [comment] 2020-01-04 17:33
Hmm, that's not it, I think. Removing that observer registration does not help.

**Comment by asvitkine** [comment] 2020-01-04 17:37
Ah, so the issue is that now MainPanel.accept() is called - which seems to do different things than MainPanel.update(). So that's probably the cause.

It seems accept() is being used for two different things? Maybe we should just have anonymous Consumer<SetupPanel> classes for the two cases, e.g.:

panel.addObserver(setupPanel -> setWidgetActivation());

**Comment by asvitkine** [comment] 2020-01-04 17:39
I confirm this fixes the issue:

```
     gameSetupPanel = panel;
     gameSetupPanelHolder.removeAll();
     gameSetupPanelHolder.add(panel, BorderLayout.CENTER);
-    panel.addObserver(this);
+    panel.addObserver(setupPanel -> setWidgetActivation());
     setWidgetActivation();
     // add the cancel button if we are not choosing the type.
     if (panel.isCancelButtonVisible()) {
```

**Comment by RoiEXLab** [comment] 2020-01-04 18:00
Thanks for digging into this @asvitkine this turned out to be a completely different problem than I anticipated, good job 👍

**Closed** 2020-01-10 08:55 UTC
Labels: Impact: Incorrect UI Behavior, Pre-Release Problem, Volunteers Needed
