### ISSUE TITLE
Stable build still precludes moving on version number 

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4208] opened 2018-10-23 09:41 UTC
### Engine version

1.9.0.0.12226

### My Operating System
Ubuntu 16.04

### Map name
Any
e.g. World War II Global 2nd Edition

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Update code to have a new version. Use this new version to either start a bot or host a game. Connecting with 1.9.0.0.12226 results in a dialog window being created that cannot be interacted with.

The offending code is here: engine/framework/GameDataManager.java -> loadGame, lines 94-107

I'm not at all sure why this code doesn't work properly. Is it platform dependent?

**Comment by simon33-2** [comment] 2018-10-23 11:14
@ssoloff Let's move the discussion here.

Tried it on Windows Vista. Just locks up with no clues as to what is going on. Used builds 6664 and 9687. For some reason, I can't get build 12226 to work on this computer. Just updated my Java to 1.8-191 but AAA just flashes up and then goes away straight away. Nothing comes up at all. I even tried connecting to a 1.9 host with a 1.8 client and got a similar outcome.

**Comment by ssoloff** [comment] 2018-10-23 19:01
The root cause is that the `JOptionPane` is being created off the EDT:

```
org.pushingpixels.substance.api.UiThreadingViolationException: Component creation must be done on Event Dispatch Thread
	at org.pushingpixels.substance.internal.utils.SubstanceCoreUtilities.testComponentCreationThreadingViolation(SubstanceCoreUtilities.java:1832)
	at org.pushingpixels.substance.internal.ui.SubstanceOptionPaneUI.createUI(SubstanceOptionPaneUI.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:770)
	at javax.swing.UIManager.getUI(UIManager.java:1016)
	at javax.swing.JOptionPane.updateUI(JOptionPane.java:1882)
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1845)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:857)
	at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:795)
	at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:757)
	at javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:718)
	at games.strategy.engine.framework.GameDataManager.loadGame(GameDataManager.java:109)
	at games.strategy.io.IoUtils.readFromMemory(IoUtils.java:60)
	at games.strategy.engine.framework.startup.mc.ClientModel.startGameInNewThread(ClientModel.java:312)
	at games.strategy.engine.framework.startup.mc.ClientModel.startGame(ClientModel.java:295)
	at games.strategy.engine.framework.startup.mc.ClientModel.access$200(ClientModel.java:79)
	at games.strategy.engine.framework.startup.mc.ClientModel$2.doneSelectingPlayers(ClientModel.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:151)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:134)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:120)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$0(UnifiedMessenger.java:268)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The easiest fix would be to either use `SwingAction#invokeAndWaitResult()` or possibly `EventThreadJOptionPane`.  A better long-term fix would be to pull all UI code out of `GameDataManager#loadGame()` and have someone higher up the stack be responsible for any UI.  That probably requires a _Strategy_ to be passed in to abstract that behavior (but that would also help to pull out the headed/headless dichotomy in this method, as well).

Note also that the repro scenario, as described above, is invalid.  As I mentioned in #4208, 12226 is no longer compatible with anything forked from `master` for approximately the past month.  A more correct repro would be to use a `master` client to connect to a 1.9.0.3050 server.

**Comment by simon33-2** [comment] 2018-10-23 19:47
Hmm, I've tested as you've described and I get the same problem.

I think this problem should really be fixed but I'm not sure how to do it.

**Comment by ssoloff** [comment] 2018-10-23 20:08
Sorry for not clarifying.  Yes, the problem still exists when you use a `master` client.  I simply wanted to point out that using a 12226 client is no longer a valid use case due to our decision to break compatibility.  When verifying the fix for this issue, the PR branch should simply be tested against `master`, not stable.

**Closed** 2018-10-24 19:30 UTC
Labels: category: bug
