### ISSUE TITLE
Naval unit movement points are not reset (tutorial)

### ISSUE THREAD

**Issue by wesgarrison** [triplea-game/triplea#3281] opened 2018-03-13 21:03 UTC
Posted this issue on forums and replicating here, see Zjelcop's analysis there.
https://forums.triplea-game.org/topic/660/tutorial-don-t-understand-naval-movement/3

### Engine version
Engine version: 1.9.0.0.9687

### My Operating System
MacOS - Sierra

### Map name
Tutorial

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
I'm Germany and want to attack UK boats. I purchased and moved to combat phase, but only some of my naval units have movement points.
![image](https://user-images.githubusercontent.com/7661/37369566-77cfdc94-26d7-11e8-8d59-32c109fbd4aa.png)

When I select a sub, for instance, it shows the red x that I can't move it and there's a message "Not all units have enough movement"

![image](https://user-images.githubusercontent.com/7661/37369566-77cfdc94-26d7-11e8-8d59-32c109fbd4aa.png)

![image](https://user-images.githubusercontent.com/7661/37369572-7f20c594-26d7-11e8-97b7-ebdb5cbf9dde.png)

In this case, my destroyers and carrier and planes can move, but the other units can't.

I don't know how to see "available movement points" per unit, either, so I can't dig into what's going on.

So, I don't know if this a bug or just me mis-understanding something.
Here's a zipped version of the savegame.
https://forums.triplea-game.org/assets/uploads/files/1520971328070-tutorial-18.tsvg.zip

#### message 2
So, something is definitely broken, but I'm not sure why/what.

![image](https://user-images.githubusercontent.com/7661/37369624-a934ef54-26d7-11e8-9eb9-bbe7489eab0d.png)

![image](https://user-images.githubusercontent.com/7661/37369634-ad83b626-26d7-11e8-90ac-4a683e233668.png)

![image](https://user-images.githubusercontent.com/7661/37369639-b1a86616-26d7-11e8-87fd-8493d5e4bc2e.png)

### Do you have the exact error text? Please copy/paste if so
```
Error: Not being carried, unit:infantry owned by Germans transport:transport owned by Germans
java.lang.IllegalStateException: Not being carried, unit:infantry owned by Germans transport:transport owned by Germans
	at games.strategy.triplea.delegate.TransportTracker.unloadTransportChange(TransportTracker.java:131)
	at games.strategy.triplea.delegate.MovePerformer.markTransportsMovement(MovePerformer.java:437)
	at games.strategy.triplea.delegate.MovePerformer.access$700(MovePerformer.java:36)
	at games.strategy.triplea.delegate.MovePerformer$3.execute(MovePerformer.java:168)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:42)
	at games.strategy.triplea.delegate.MovePerformer.populateStack(MovePerformer.java:290)
	at games.strategy.triplea.delegate.MovePerformer.moveUnits(MovePerformer.java:75)
	at games.strategy.triplea.delegate.MoveDelegate.move(MoveDelegate.java:604)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.delegate.DelegateExecutionManager$1.invoke(DelegateExecutionManager.java:129)
	at com.sun.proxy.$Proxy2.move(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:157)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:126)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:105)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:52)
	at com.sun.proxy.$Proxy2.move(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.gamePlayer.DefaultPlayerBridge$GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:151)
	at com.sun.proxy.$Proxy2.move(Unknown Source)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:325)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:330)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:330)
	at games.strategy.triplea.TripleAPlayer.start(TripleAPlayer.java:124)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:515)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:404)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:254)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:58)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Thread.java:745)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:64)
	at com.sun.proxy.$Proxy2.move(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.gamePlayer.DefaultPlayerBridge$GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:151)
	at com.sun.proxy.$Proxy2.move(Unknown Source)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:325)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:330)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:330)
	at games.strategy.triplea.TripleAPlayer.start(TripleAPlayer.java:124)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:515)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:404)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:254)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:58)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Thread.java:745)
```

### Instead of this error, what should have happened?

Destroyers should have movement points.

### Any additional information that may help

https://forums.triplea-game.org/assets/uploads/files/1520971328070-tutorial-18.tsvg.zip

**Comment by ron-murhammer** [comment] 2018-03-13 23:05
I'm able to reproduce the issue. It appears the save game is corrupted. It looks like several of the naval units are no longer attached to the game data which is causing them to not reset their movement and not be able to properly load units. Why that happened is hard to say. It appears the end of round 14 is the last time the naval units get properly reset. My guess is something happened when the game was saved/loaded at the start of Italy's round 14 turn.

**Comment by ron-murhammer** [comment] 2018-05-21 00:53
Closing as unable to determine cause of corrupted save game at this time.

**Closed by ron-murhammer** 2018-05-21 00:53 UTC
