### ISSUE TITLE
Actions and Operations opens up too small (sometimes)

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#3270] opened 2018-03-12 00:23 UTC
### Engine version
1.9.0.0.9708 but most likely also many older versions

### My Operating System
Windows 10 64-bit

### Map name
Iron War and maybe other maps.

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Sometimes the Actions and Operations window is not wide and high enough to show the window content. The window pops up too small resulting in all the content of the window hidden.
If one, with the mouse, expands the window, the content gets visible again when the window is large enough. One can also manually shrink the window and then the content gets hidden again. (see the pictures posted below)

I have no idea about what is causing this and how it could be fixed, but I think if the window always popped up large enough the problem would not show? Maybe a solution would also be to not allow the window size to ever (manually or automatically) be smaller than the content in the window?
![unavngivet1](https://user-images.githubusercontent.com/15268177/37260458-acaa939a-2593-11e8-94b3-21543c420e23.png)
![unavngivet2](https://user-images.githubusercontent.com/15268177/37260466-c9fef26a-2593-11e8-9c3a-777984082ea5.png)

**Comment by ron-murhammer** [comment] 2018-03-13 23:32
@FrostionAAA Hmm. I don't think I've ever seen this happen. If you find a way to consistently reproduce it then let me know as it should be easier to fix then.

**Comment by FrostionAAA** [comment] 2018-04-30 06:52
Am I really still the only person who experiences this minor flaw? That’s strange.
![error](https://user-images.githubusercontent.com/15268177/39417319-c031a99e-4c53-11e8-98c9-e0972e08a2bb.png)

**Comment by RoiEXLab** [comment] 2018-04-30 07:36
@FrostionAAA found a way to reproduce this by accident:
Just resize the window to be smaller than the initial size and it always looks like this
#3408 has a fix

**Comment by FrostionAAA** [comment] 2018-04-30 07:58
Ok. So future verisons of the pre-release should not have this problem? I just saw the window pop up to small on engine version 1.9.0.0.10211

**Comment by RoiEXLab** [comment] 2018-04-30 09:36
@FrostionAAA Yes, once #3408 is merged this problem should no longer occur.

**Comment by RoiEXLab** [comment] 2018-04-30 12:42
@FrostionAAA Just FYI: You shouldn't close or at least you don't need to close an issue when a PR is available:
1. This PR might fix an issue, but might not fix your specific edge case
2. This issue is being closed automatically when the PR gets merged

**Closed** 2018-05-09 14:28 UTC
Labels: category: UI problem
