### ISSUE TITLE
Error (why must a player have this image in his unit image directory?)

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#6475] opened 2020-05-15 16:23 UTC
This is such a strange engine requirement that I can’t think it anything else than a flaw in the engine. Look at this situation, where a player nation kills enemies of another player:
![Unavngivet](https://user-images.githubusercontent.com/15268177/82071294-34ba1700-96d6-11ea-99cd-3f0f57dc0a08.png)

The facts in regards to this situation’s map files:
- The _Trolls_ player can in no way build the Kobold unit, so it does not have that image in its _Trolls_ unit image directory.
- The Kobold unit image is only located in the _units_ root dir.
- The Loot bag unit image is only located in the _units_ root dir.

So the unit is killed and the engine looks for the Kobolds/Lootbag images it in the Trolls dir?

```
<attachment name="unitAttachment" attachTo="Kobold-Miners" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
<option name="defense" value="2"/>
<option name="whenHitPointsDamagedChangesInto" value="1:false:Loot-Level-1"/>
</attachment>

<attachment name="unitAttachment" attachTo="Loot-Level-1" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
<option name="isInfrastructure" value="true"/>
<option name="createsResourcesList" value="10:XP"/>
<option name="createsResourcesList" value="1:Gold"/>
</attachment>
```

I guess the engine image display has a problem with this kind of unit kill -> change -> capture?

By the way, there is no other consequences of the “missing unit image”, other than no image is displayed in history-mode  when reviewing the battle.
![Unavngivet2](https://user-images.githubusercontent.com/15268177/82072266-b9596500-96d7-11ea-9d4a-eddd09c38839.png)

Can this issue be addressed?

**Comment by Johnny1900** [comment] 2020-05-15 16:53
I noticed the same error while playing Domination 1914.

**Comment by Cernelius** [comment] 2020-05-15 23:12
I don't think the "Trolls" player has anything to do with this. The error message is searching the unit for the "Kobolds" player.

**Comment by FrostionAAA** [comment] 2020-05-16 00:55
@Cernelius The history screenshot is of a Troll player flag (Green) and 3 "Kobold-Miners" units that has no unit image in Troll unit directory and therefore is missing.

The generic flag unit image of the Kobold player is the cross with cranium. This is only show as the flag image before the territory is captured.

**Comment by Cernelius** [comment] 2020-05-16 19:51
> @Cernelius The history screenshot is of a Troll player flag (Green) and 3 "Kobold-Miners" units that has no unit image in Troll unit directory and therefore is missing.
> The generic flag unit image of the Kobold player is the cross with cranium. This is only shown as the flag image before the territory is captured from Kobolds to Trolls. After this it is a green flag.

I'm really not following what you are saying here. The error screenshot you posted literally says that the missing image is Kobold-Miners owned by Kobolds, so that has nothing to do with any images in the Trolls folder. Moreover, the second screenshot you posted literally says that "Kobolds defend with", so that is referring to "Kobolds" units too (if any of those units are taken from the "Trolls", that's rather the problem, there).

What might be your problem is that you are missing an image called "Kobold-Miners_hit" inside the Kobolds folder (or main folder).

So, do you have a "Kobold-Miners_hit" image in the Kobolds folder or main folder?

At least in the action tab, when lost units are displayed, it is the "hit" version of the unit that is displayed, if the image is a single hitpoint one that turns when damaged.

@ron-murhammer Regardless wheter this is @FrostionAAA problem or not, is it intended to display the "hit" unit for lost units that change when reduced to 0 hitpoints left? I think this behaviour should be changed, if not fixed, as, in the moment in which removed units normally display the basic image (not requiring any "hit" version of the same), I think it is normal to assume the "Kobold-Miners" of this case should not need any "Kobold-Miners_hit" image in the folder. Shouldn't they?

---

This said, moving on to the second screenshot you uploaded, that looks to me being yet another two (possibly separate) issues. The first additional issue, clearly, here would be that the program is showing the "Trolls" flag in place of the "Kobolds" flag. The other issue is that the program is not showing anything for the "Kobold-Minerss". I think it's clear here that the program is mistakenly taking the units images at the condition after the territory has been conquered (but before "Kobold-Miners" are repaired, thus changed into "Loot-Level-1"), if the description, namely "Kobolds defend with...", is making any sense.

**Comment by FrostionAAA** [comment] 2020-05-17 00:30
@Cernelius I will try to add _hit images to the shared directory of all the units that have 1 hit point and turn into something else when killed. I never thought it was necessary to have _hit versions of images of 1 HP units.

And yes, it might be a separate issue when history shows wrong owners of the unit involved in the historical battles.

**Comment by FrostionAAA** [comment] 2020-05-17 10:58
I added _hit versions of the 1 HP units that turn into something else when killed, and that seems to prevent the error pop up. I will close the issue, letting it be up to devs if further action is needed.

**Comment by Cernelius** [comment] 2020-05-19 15:25
@ron-murhammer So, the fact that it is necessary having "hit" versions of 1 HP units that change upon receiving 1 damage is intended? Should it be documented?

By the way, I knew about this because I encountered the issue myself (and figured it out).

**Comment by FrostionAAA** [comment] 2020-05-24 19:19
I will just reopen this issue and let a developer close it. Maybe with an explanation on @Cernelius question ;-)

**Comment by DanVanAtta** [comment] 2020-05-25 14:34
Just want to clarify/recap the problem:  a unit that turns into another unit on damage is being required a 'hit' image that is never displayed because the unit turns into a different one?

**Comment by FrostionAAA** [comment] 2020-05-25 20:33
Yes I think that is the main problem. Maybe @Cernelius has something to add.

A secondary issue is that "history mode" draws its unit images from the current owner of the territory (shown in the right side bar when looking at old battles), even when depicting what was present in the territory from start of battle. Optimally it should be the original owners being display as with the original units present in the territory when the battle began. @Cernelius Is this not correct?

**Comment by Cernelius** [comment] 2020-05-26 11:53
> Just want to clarify/recap the problem:  a unit that turns into another unit on damage is being required a 'hit' image that is never displayed because the unit turns into a different one?

It is displayed as, if it would not be displayed, it would not be required. You can see it is the "x3" thing without the image in the second picture @FrostionAAA posted at the opening post, above the black-green flag (there is nothing because there was no image in the skin, thus the error).

But, in my opinion, here there is no need to display anything but the non-damaged image. So, I was wondering if this is just something non-wanted, and the behaviour could be changed as saving any mapmaker the trouble to have to add a damaged version of the unit, in each of such cases.

By the way, I believe this new feature (being able to spawn units out of destroyed ones) is one of the biggest advancement introduced.

I've similar ideas about cutting the number of images needed for units that change on damage, as I believe the current system is hypertrophic on the skin side, but this is not on topic, and I guess it totally depends if @ron-murhammer has any interest in the matter.

**Comment by DanVanAtta** [comment] 2020-05-26 19:52
> A secondary issue is that "history mode" draws its unit images from the current owner of the territory

I'd very much recommend creating a new issue for that. 1 problem report, 1 fix. It's notable this work flow is built into the bug tracker system here, when a code update referencing a bug report is merged the bug report is closed. If the report has multiple issues then it gets closed and has to be re-opened. We also have historic problems where issues that track 2+ issues get messy and tend to not get fixed. When in doubt, simply create a new bug report.

**Comment by DanVanAtta** [comment] 2020-05-26 19:53
Re: is the damage unit image required?

I think the latest responses have lost clarity. What is the exact problem being described? The fact that the unit image is needed, or that it's needed unnecessarily, or are there cases where it is needed but should not be?

**Comment by Cernelius** [comment] 2020-05-26 20:37
> What is the exact problem being described?

I'm thinking this is my last attempt at clarifying this matter. The original problem (beside the other problem of showing images at a wrong point in history, that I agree should be another issue, but I think only @FrostionAAA can open it, or anyone else successfully reproducing it), which has been solved, was that @FrostionAAA was missing a unit image. The same problem that I raise is that, in my opinion, there is no need to have that unit image that @FrostionAAA was missing, beside the mere fact that it is needed by the program. Therefore, in my opinion, I believe rather the program should be fixed, as not needing the needed image, instead of @FrostionAAA, or any mapmaker, having to add every instance of such images. Basically, at this point, it is an argument whether the actual fix should be at a skin or at a program level.

**Comment by Cernelius** [comment] 2020-05-26 20:43
If the program has no on-topic issues remaining, there would be still the issue that it seems this requirement is not documented anywhere (or at least I'm not aware it is and @FrostionAAA got to know about it only because I let him). However, there may be no need of any documentation if the fix would, instead, be not requiring such images.

**Comment by FrostionAAA** [comment] 2020-07-02 11:13
I have not seen this error in a while so I will just close this issue. But will re-open if I see it again :-)

**Closed** 2022-08-07 16:05 UTC
Labels: Needs Clarification
