### ISSUE TITLE
2.6+3479832: Politics popups on result of politics actions go to all players

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#10854] opened 2022-07-08 02:47 UTC
### Reproduction Steps
1. Load the following save game on "Another World" map:
[popups.zip](https://github.com/triplea-game/triplea/files/9068512/popups.zip)
2. End turn and let AI do its turns.
3. Observe popup notifications

Popups showing the result of political actions are shown, even when you're not playing the player who's performing those actions.
![Capture](https://user-images.githubusercontent.com/17648/177907165-5c94cf2a-3ecf-4f57-80ad-d4bfbb3be48a.PNG)

### Attach a Save Game

See above.

### Engine Version

Engine Version: 2.6+3479832

### Is there anything else we should know?

This was not the case on a prerelease from a week or two ago. So some recent change.

@RoiEXLab - I know you refactored some code related to notifications to players. Can you check if your changes introduced this? Thanks!

**Comment by RoiEXLab** [comment] 2022-07-08 08:02
@asvitkine I can check today or tomorrow (depending on my time) but I honestly can't remember a change touching notification code directly. Can you tell me  which change you had in mind so I can narrow it down a bit?

**Comment by RoiEXLab** [comment] 2022-07-12 22:57
Sorry for the long delay. I think you were thinking about #10709 which introduces the regression that was fixed in #10761 right? Seems to work fine in those versions. I checked if #10813 had anything to do with it and it seems to be fine as well.
Not sure at which point this was introduced. Notifications appear in all versions I checked, but only the one on master was talking to me in 2nd person. I believe that's what I had to look out for? If that assumption is correct then this regression was introduced after 19d4d3cc9234bee43323c14eac25d1a0fb712ec5
Not sure if I'm missing something though.

**Comment by asvitkine** [comment] 2022-07-13 01:30
Hmm, if it's not that, we can see what the log is since https://github.com/triplea-game/triplea/commit/19d4d3cc9234bee43323c14eac25d1a0fb712ec5:

[log.txt](https://github.com/triplea-game/triplea/files/9098092/log.txt)

**Comment by asvitkine** [comment] 2022-07-13 01:33
There's only a few changes modifying the actual engine code (as opposed to peripheral things like build infra and tests).

Nothing obvious jumps out. :\

Maybe we should test again with https://github.com/triplea-game/triplea/commit/19d4d3cc9234bee43323c14eac25d1a0fb712ec5 - in case just the game went randomly in a way that the problem wasn't hit.

**Comment by asvitkine** [comment] 2022-07-13 01:56
Ok, I went through the commits in question and identified that the error was introduced in 10235e4acf639e8c895962143359319795f22b1d. Re-assigning to Dan.

**Comment by DanVanAtta** [comment] 2022-07-13 02:13
Looks like the issue is probably in this block: 
https://github.com/triplea-game/triplea/commit/10235e4acf639e8c895962143359319795f22b1d#diff-47846210ecbc2ecd9c8de2c8ec82161e0d18e8f08dd3122870c97882971027f8L317-L322

The before and after are not equivalent. There is another instance lower on that likely has the same problem.

**Comment by DanVanAtta** [comment] 2022-07-13 03:18
Potentially fixed in: https://github.com/triplea-game/triplea/pull/10875

**Comment by DanVanAtta** [comment] 2022-07-13 03:33
PR merged.. Looks like now the notifications are now intended properly for the 'other' players.

**Closed** 2022-07-16 01:55 UTC
Labels: Problem, Regression
