### ISSUE TITLE
On the game Domiantion 1914 No man's Land, the Victory bond tech, which gives 2 dice rolls of income, during the turn complete phase, is it not working at all on multiple countries on the 2.0 lobby. The tech worked perfectly on 1.9.

### ISSUE THREAD

**Issue by samstreeter** [triplea-game/triplea#6792] opened 2020-06-24 04:23 UTC

**Comment by DanVanAtta** [comment] 2021-03-07 03:04
Likely duplicate of: https://github.com/triplea-game/triplea/issues/8609

**Comment by asvitkine** [comment] 2022-06-07 01:04
Seems to be working on 2.6 HEAD, closing.

**Closed by asvitkine** 2022-06-07 01:04 UTC
Labels: Problem, Regression
