### ISSUE TITLE
Logging GameOverException on game close

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2453] opened 2017-09-29 16:05 UTC
Repro:
- start a single player game (I used 270BC as an example)
- open error console
- leave the game via file menu

Note: game over stack trace was written 'quietly' to the console.
Expected: no stack trace

```
Loading resources from the following paths: [/home/dan/triplea/downloadedMaps/270bc-master.zip, /home/dan/work/triplea/assets]
games.strategy.engine.GameOverException: Game Over
	at games.strategy.engine.delegate.DelegateExecutionManager.assertGameNotOver(DelegateExecutionManager.java:133)
	at games.strategy.engine.delegate.DelegateExecutionManager.access$000(DelegateExecutionManager.java:32)
	at games.strategy.engine.delegate.DelegateExecutionManager$1.invoke(DelegateExecutionManager.java:153)
	at com.sun.proxy.$Proxy4.toString(Unknown Source)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.toString(EndPoint.java:191)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractMap.toString(AbstractMap.java:559)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.getImplementor(UnifiedMessenger.java:184)
	at games.strategy.engine.message.RemoteMessenger.unregisterRemote(RemoteMessenger.java:43)
	at games.strategy.engine.message.RemoteMessenger.unregisterRemote(RemoteMessenger.java:38)
	at games.strategy.engine.random.RandomStats.shutDown(RandomStats.java:20)
	at games.strategy.engine.framework.ServerGame.stopGame(ServerGame.java:318)
	at games.strategy.triplea.ui.TripleAFrame.leaveGame(TripleAFrame.java:584)
	at games.strategy.triplea.ui.menubar.FileMenu.lambda$addExitMenu$2(FileMenu.java:90)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:48)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:330)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
```

**Comment by ssoloff** [comment] 2017-10-01 03:56
I git bisected the first occurrence of this failure down to `a08ac89 (tag: 1.9.0.0.6854) Harden UnifiedMessenger.java (#2411)`.  Nothing jumps out at me as the root cause after a casual glance at the #2411 diff.

**Comment by ssoloff** [comment] 2017-10-01 04:30
Removing the `Preconditions#checkNotNull()` call added in #2411 from `UnifiedMessenger#getImplementor()` causes the exception to no longer occur:

```java
public Object getImplementor(final String name) {
  synchronized (m_endPointMutex) {
    final EndPoint endPoint = m_localEndPoints.get(name);
    Preconditions.checkNotNull(endPoint, "local endpoints: "
            + m_localEndPoints + " did not contain: " + name + ", messenger addr: " + super.toString());
    return endPoint.getFirstImplementor();
  }
}
```

I stepped through this method with the debugger and observed that an exception is being raised during the attempt to call `m_localEndPoints.toString()` (from the string concatenation).  I drilled down a bit deeper and found the exception is actually raised when calling `EndPoint#toString()`, specifically when calling `toString()` on `EndPoint#m_implementors`.

`EndPoint#m_implementors` is a collection of `Proxy`s.  Invoking `toString()` on one of those proxies results in an exception whose message is `com.sun.jdi.InvocationException occurred invoking method.`.

@DanVanAtta Assigning this to you, as you best understand the context in which you were adding the precondition failure message.  It might be sufficient to only display the keys of `UnifiedMessenger#m_localEndPoints` in the message, but I'm not sure.  IMO, I think it's sufficient to output the key that couldn't be found; I don't think it's necessary to display the entire map that was searched.  That is:

```java
Preconditions.checkNotNull(endPoint, "local endpoints did not contain: " + name
    + ", messenger addr: " + super.toString());
```

Note that the same failure will occur in `UnifiedMessenger#toString()`, as it attempts to call `toString()` on `m_localEndPoints`, as well.  Might want to address that at the same time.

**Comment by ssoloff** [comment] 2017-10-03 03:09
@DanVanAtta Bumping this before you go offline.  If you can provide your opinion on how you'd like to see this fixed, I'll be happy to submit a PR so it can get in before the next stable release.

**Comment by DanVanAtta** [comment] 2017-10-03 18:36
- IMO `toString()` should usually be 'safe'  to call, this example where we can get an exception depending on game state seems a bit broken. So ideally we would avoid that, but not the biggest priority by the same token.

- removing the toString() simply should work, it's there for extra debug, not critical to have it.

**Comment by RoiEXLab** [comment] 2017-10-05 10:44
Closing via #2465

**Closed by RoiEXLab** 2017-10-05 10:44 UTC
Labels: regression
