### ISSUE TITLE
Revised Germany locking up rnd 1

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2147] opened 2017-07-28 00:38 UTC
Current issue mentioned by a player

germany locking up rnd 1

last update 30 min ago to new (old) stable

triplea.engine.version.bin:1.9
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
java.lang.ArrayIndexOutOfBoundsException: 1
	at games.strategy.engine.message.RemoteMethodCall.classesToString(RemoteMethodCall.java:128)
	at games.strategy.engine.message.RemoteMethodCall.resolve(RemoteMethodCall.java:180)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:161)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$298(UnifiedMessenger.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I was able to duplicate it.  It seemed to occur when i moved the bomber to attack

**Comment by prastle** [comment] 2017-07-28 00:41
[bomber error.zip](https://github.com/triplea-game/triplea/files/1181651/bomber.error.zip)

File attached

**Comment by prastle** [comment] 2017-07-28 01:21
New update ... after testing in private host it appears to be a bot only related error thus why all the complaints this week from all users about the new bots.

riplea.engine.version.bin:1.9
Loading map: , from: C:\Users\john\triplea\downloadedMaps\
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\, C:\Program Files\TripleA_1.9.0.0.3635\assets]
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
java.lang.ArrayIndexOutOfBoundsException: 1
	at games.strategy.engine.message.RemoteMethodCall.classesToString(RemoteMethodCall.java:128)
	at games.strategy.engine.message.RemoteMethodCall.resolve(RemoteMethodCall.java:180)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:161)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$298(UnifiedMessenger.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


it only occurs in the bot when a bomber attacks from germany somewhere i was using caucas

**Comment by prastle** [comment] 2017-07-28 01:33
Narrowed down further  ... It only occurs in the new bots ... @DanVanAtta  warclub and private host works fine  .... maybe  the new stable is fine and its just a bots issue form your install @DanVanAtta  not trying to aggravate just trying to help.  Many people, myself included,  had np with the new stable relese. But yells were going on everywhere!  @RoiEXLab could you look at the new bots scripts and see if you see anything different from your old bots scripts or the warclub bots scripts ? Please and thank you because otherwise the new bots are useless.

**Comment by DanVanAtta** [comment] 2017-07-28 01:35
Looks like the same non-compat bug that was reported elsewhere. The bots are likely on a version that included that bug still, since the bug has been on master for a little while now. Fix would be to re-install bots  at current latest release.

**Comment by DanVanAtta** [comment] 2017-07-28 01:36
@prastle you should be able to do most of that even.
There is  a stop_all script in `/home/triplea` on each server in the meantime.

**Comment by prastle** [comment] 2017-07-28 01:47
i have stopped started etc bots but i have never installed any

and since i dont have sudo can i even install them?

**Comment by DanVanAtta** [comment] 2017-07-28 01:52
You might not be able to install them, but you can stop them. Since they have compat issues, probably better to stop them while we wait for upgrade.

 Just run: `/home/triplea/stop_all`

**Comment by prastle** [comment] 2017-07-28 01:54
well already stopped 4
the real ? is  it all new bots?
should i phone ak to ask for some and cernel?

**Comment by prastle** [comment] 2017-07-28 01:55
to be specific 50 peeps in lobby

and ur asking me to shut down all their bots

**Comment by prastle** [comment] 2017-07-28 01:56
sorry 33 alot left

**Comment by prastle** [comment] 2017-07-28 02:04
ge server has same problem
testing nj'

**Comment by prastle** [comment] 2017-07-28 02:06
nj as well

**Comment by prastle** [comment] 2017-07-28 02:22
ca as well and texas

**Comment by ssoloff** [comment] 2017-07-29 01:03
The root cause of this issue was fixed in 1.9.0.0.5947, and the bots have been downgraded to 1.9.0.0.3635 as of [1500 EDT](https://github.com/triplea-game/triplea/issues/2133#issuecomment-318734563).  @prastle, please advise if any lobby users continue to report similar lock-ups over the next 24-48 hours.

**Comment by prastle** [comment] 2017-07-30 11:34
@ssoloff It seems fine now with the downgrade

**Closed** 2017-07-30 20:29 UTC
Labels: close pending confirmation
