### ISSUE TITLE
TripleA 2.6.895 gives this error - Could not find step name

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#10647] opened 2022-06-12 23:07 UTC
This map works without error in 2.5

But 2.6.895 has the error below, by taking the defaults, it does not get past round 1.

With 2.6 it does not give me a proper error message or clue me where to look, please take a look.  The step error should work with uppercase **F**inns and **R**ussians, yes?

![image](https://user-images.githubusercontent.com/71022517/173256371-dbc3c824-1c7b-4e58-b044-2103f6f06c95.png)

Map
[WW2_Russia_Finland_1939.zip](https://github.com/triplea-game/triplea/files/8886942/WW2_Russia_Finland_1939.zip)

**Comment by asvitkine** [comment] 2022-06-13 01:37
So it's referring to steps in a battle. The list of steps the engine has in that situation is:

- Finns select casualties
- Finns notify casualties
- Finns units Elite fire
- Russians select units Elite casualties
- Russians notify units Elite casualties
- Finns units Forest fire
- Russians select units Forest casualties
- Russians notify units Forest casualties
- Remove casualties
- Russians withdraw?

So "Russians select casualties" is not one of them. I guess there's some customization of the step names somewhere and some code might not expecting for that to be the case and is looking for a normal casualties step?

**Comment by asvitkine** [comment] 2022-06-13 01:51
The step name comes from `getPossibleOldNameForNotifyingBattleDisplay()` which was added in this 2.6 PR:
https://github.com/triplea-game/triplea/commit/b804d3709224ae642c7e420d7d16cd85b372d225

It does a remapping of a step name, for example:
"Finns select air vs non subs casualties" gets mapped to "Finns select casualties"

Because the original string wasn't in the list of:
```
[Finns air vs non subs fire, Russians select air vs non subs casualties, Russians notify air vs non subs casualties, Finns fire, Russians select casualties, Russians notify casualties, Russians units Artillery fire, Finns select units Artillery casualties, Finns notify units Artillery casualties, Russians units Mountain fire, Finns select units Mountain casualties, Finns notify units Mountain casualties, Remove casualties, Finns withdraw?]
```

I'm really not familiar with this code, so maybe @trevan could chime in or @DanVanAtta who reviewed the above PR?

**Comment by TheDog-GH** [comment] 2022-06-13 09:06
This is the first time/map I have used **canNotTarget** and if I comment out its use the map runs without error.

As an aside
> Finns units Forest fire
> Russians select units Forest casualties

Forest is an **isInfrastructure** unit with no attack or defence, so should it even be in this list?

It might also be worth looking at **canNotBeTargetedBy** in the above context ?

**Comment by asvitkine** [comment] 2022-06-13 12:30
Indeed, `canNotBeTargetedBy` is relevant here.

The distinct step names above (e.g. "Russians units Mountain fire") are generated by `newTargetGroups()`, which splits on `getCanNotBeTargetedBy()` via `findTargets()`.

I agree that the result doesn't make sense given the units don't ever fire or participate in combat! But I'm not sure how exactly the logic changed here in 2.6 and what's the right fix (I mean, we can bandaid it by filtering units, but seems like there might be a more fundamental assumptions mismatch between different parts of the battle code). I'm hoping @trevan could chime in.

**Comment by trevan** [comment] 2022-06-21 02:31
That error pops up in a bunch of different locations.  It existed before my changes and, as this bug shows, still shows up.

It actually doesn't break anything.  What is happening is that when a step occurs, the UI tries to match the step from the engine with the step in the UI.  They are supposed to match but are created at two different times.  The UI steps are created at the very beginning of the battle while the engine creates each step as it is needed.  It is possible for the UI to have steps that the engine doesn't have and vice versa.  When the engine has a step that the UI doesn't have, that error will occur.  But, you can press "OK" and keep going and nothing will break.

The `getPossibleOldNameForNotifyingBattleDisplay` method was an attempt to migrate old step names to the new step names that I added.  It will only fire when you open a save game from an older engine.  If the save is from 2.5 and being opened in 2.6, then that method will be called, but if the save is from 2.6, it should never be called.  It sounds like the save is a 2.6 only save, so that method is not where you would want to look.

**Comment by asvitkine** [comment] 2023-07-06 01:35
Dupe of https://github.com/triplea-game/triplea/issues/11617

**Comment by asvitkine** [comment] 2023-07-12 19:53
So, looking at this more, one thing that changed is the actual list of steps between 2.5 and 2.6.

![2 5](https://github.com/triplea-game/triplea/assets/17648/826a4c0e-f534-4d77-b8dd-d183471c04f0)
![2 6](https://github.com/triplea-game/triplea/assets/17648/1e4a684b-6bdf-49c8-a6bb-ec9b6029ae42)

So 2.6 is splitting and including a step for forests, even though they don't participate in combat (don't show in the unit list).

So I think that would be the first thing to fix.

**Comment by asvitkine** [comment] 2023-07-12 19:54
(Repro is very simple on the above map, just play as a human and attack Finns in Ladoga.)

**Comment by asvitkine** [comment] 2023-07-12 20:39
The following PR appears to fix this: https://github.com/triplea-game/triplea/pull/11773

I need to do more testing and add a unit test.

**Closed** 2023-07-15 01:13 UTC
Labels: Problem, Regression, 2.6
