### ISSUE TITLE
alliedExclusionTerritories ?  (global 40 mod NOs)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#308] opened 2015-12-30 01:18 UTC
For attached files see: http://tripleadev.1671093.n2.nabble.com/alliedExclusionTerritories-td7590333.html

Bug report:
"On a global 40 mod there is a NO which has incorrect behaviour. It has worked fine except for this one instance and I can't figure out why. I didn't make a bug report as I was unable to reproduce it on the non modified map. 

What happens is on rd 6 the US liberates Amur. There are now US units in original Russian territory which should negate several Russian NOs. Everything is fine until during the ncm after US air has been moved from Amur the objectives activate. If I edit a unit to Amur the NO deactivates. I tried to remove the US units and replace them but it wouldn't allow due to being on a transport originally. 

The next turn I removed the transported units normally and landed new units via transport and the objective worked correctly. Anyway if anybody cares to take a look here is the mod and a saved game. "

**Comment by beelees** [comment] 2015-12-30 03:52
here's the mod again it expired on sendspace. I'll try and keep it updated.
https://www.sendspace.com/file/cqhvid
I'll see if i can figure out how to add it to the github.
 

    On Tuesday, December 29, 2015 7:18 PM, Dan Van Atta <notifications@github.com> wrote:
 

 For attached files see: http://tripleadev.1671093.n2.nabble.com/alliedExclusionTerritories-td7590333.htmlBug report:
"On a global 40 mod there is a NO which has incorrect behaviour. It has worked fine except for this one instance and I can't figure out why. I didn't make a bug report as I was unable to reproduce it on the non modified map. What happens is on rd 6 the US liberates Amur. There are now US units in original Russian territory which should negate several Russian NOs. Everything is fine until during the ncm after US air has been moved from Amur the objectives activate. If I edit a unit to Amur the NO deactivates. I tried to remove the US units and replace them but it wouldn't allow due to being on a transport originally. The next turn I removed the transported units normally and landed new units via transport and the objective worked correctly. Anyway if anybody cares to take a look here is the mod and a saved game. "—

**Comment by DanVanAtta** [comment] 2015-12-30 20:11
Github only hosts images, and it appears zenhub, a new plugin we are trying out only supports file attachments of up to 10MB. My recomendation would be google drive (or drop box if you have an account there already). It might be quite some time before someone looks at this in detail.

**Comment by beelees** [comment] 2015-12-30 21:37
Yea low prioroity that's why I didn't make a bug report just thought someone might want to take a quick look which they sometimes do.
 

    On Wednesday, December 30, 2015 2:11 PM, Dan Van Atta <notifications@github.com> wrote:
 

 Github only hosts images, and it appears zenhub, a new plugin we are trying out only supports file attachments of up to 10MB. My recomendation would be google drive (or drop box if you have an account there already). It might be quite some time before someone looks at this in detail.—

**Closed** 2016-06-06 03:53 UTC
Labels: Bug, Close Pending Confirmation

**Comment by DanVanAtta** [comment] 2016-06-07 03:20
@beelees  - pls repost the mod file so we can reproduce the problem. Github allows upload of zip files, so you should be able to zip the files up and attach them to this issue. Let's re-open and put this in the inbox once we have a repro case.
