### ISSUE TITLE
Binaries missing in pre-releases

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5794] opened 2019-12-30 21:44 UTC
![bin](https://user-images.githubusercontent.com/20812775/71601916-e99fcd00-2b55-11ea-8a95-b4ae855b35ca.PNG)

**Comment by DanVanAtta** [comment] 2019-12-31 07:37
Failed with:
```
install4j: compilation failed. Reason: java.lang.OutOfMemoryError: Java heap space
```

**Comment by panther2** [comment] 2019-12-31 11:14
Closed as latest releases have them included.

**Comment by panther2** [comment] 2020-01-03 09:31
It happened again:

**Comment by panther2** [comment] 2020-01-03 17:34
@DanVanAtta

**Comment by panther2** [comment] 2020-01-04 10:05
CC: @RoiEXLab @ron-murhammer @ssoloff

**Comment by RoiEXLab** [comment] 2020-01-04 10:21
Still the same error unfortunately :/

**Comment by DanVanAtta** [comment] 2020-01-05 23:30
Until we actually resolve the problem, this seems to be a liability.
The issue is heap space for the install4j process. We do not control that very directly.
It's less than ideal., I don't think there is a readily available fix to be had here.

**Comment by DanVanAtta** [comment] 2020-01-05 23:32
FWIW, the install4j gradle task was recently update to 8x; Assuming that is okay, perhaps that may have an impact on this issue. Will be interesting if/when how often we see this problem going forward.

**Comment by panther2** [comment] 2020-01-21 06:47
@DanVanAtta 
I am reopening this, as we see on https://github.com/triplea-game/triplea/releases
that the creation of binaries seems to be a result of a lottery, still.

**Comment by DanVanAtta** [comment] 2020-01-25 23:02
It looks like this problem is happening more often than not.

It's not a trivial fix as the problem is not really in our control 100%.

We also do not have a lot to go off of to know where this problem is coming from, secondly the iteration time for building installers is very slow, which could make this a painful fix.

The only things I can think of:
- see if we can add flags to increase heap space
- start removing likely suspects
- downgrade install4j version and/or all dependencies from when this problem started happening.

@RoiEXLab any thoughts on this one by any chance?

**Comment by DanVanAtta** [comment] 2020-01-25 23:11
@RoiEXLab  I wonder a bit about JavaFX dep's, particularly as install4j seemingly has trouble with them. Perhaps this is related to: https://github.com/triplea-game/triplea/issues/5755

**Comment by RoiEXLab** [comment] 2020-01-26 01:43
> as install4j seemingly has trouble with them.

What do you mean? Could you name an example? I doubt that it has something to do with it. After all RAM doesn't necessarily have anything to do with actual persistant storage space.

But apart from that. no clue. I remember that we had a somewhat related issue quite some time ago, where the PR builder was constantly running out of memory as well. IIRC @ssoloff created a ticket for this which resulted in the variable `_JAVA_OPTIONS` to be set by travis for the gradle daemon. Maybe something similar could help?

**Comment by DanVanAtta** [comment] 2020-01-26 03:55
Not finding JAVA_OPTS in history or code. It'd be really ideal if we could fix this with adding resources.

>  Could you name an example? 

Travis is reporting 7k warnings for pack200 issues. 

> I doubt that it has something to do with it.

I suspect that could be right, but we don't know what is causing our heap to run out of space. The timing of adding many megabytes, and perhaps if it's not being handled well and we are getting maybe something like file handles being leaked into heap, then it's conceivable we could run out of space and it be exacerbated with additional javaFx class files.

**Comment by ssoloff** [comment] 2020-01-26 07:27
> IIRC @ssoloff created a ticket for this which resulted in the variable _JAVA_OPTIONS to be set by travis for the gradle daemon.

#2365 links back to all applicable issues and PRs.

**Comment by DanVanAtta** [comment] 2020-02-01 20:59
Thanks @ssoloff for the reference, that was a help and a similar fix applied in #5897 seems to have worked.

The latest master build with a 3G heap looks to have successfully built installer artifacts. The build process still died though:

```
Triggering github release by pushing tag: 2.0.17868
+cd website
+git update-index --refresh
_maps/dragon-war.html: needs update
```

**Comment by DanVanAtta** [comment] 2020-02-01 23:10
Along a few fixes, added a setting for the gradle max heap size to be 3G (increased from 2G) when building installers. Since then have not seen an out of heap failure and the latest release has the installers attached to it.

**Closed by DanVanAtta** 2020-02-01 23:10 UTC
Labels: Pre-Release Problem, Problem
