### ISSUE TITLE
Too many problems from old Java versions

### ISSUE THREAD

**Issue by simon33-2** [triplea-game/triplea#4358] opened 2018-11-15 20:19 UTC
Me and others have been spending way too much time sorting out issues caused by mostly Windows platforms with old versions of Java causing incompatibilities.

Is there some way that the installer could at least validate that the Java is up to date? Or some other option? In 1.8 it bundled the Java which was more stable than present but I guess you don't want to go back to that.

**Comment by ssoloff** [comment] 2018-11-15 22:07
I looked through the install4j documentation to see if there was a way to force it to upgrade a previously-installed bundled JRE with a later one referenced by the current installer.  Unfortunately, I wasn't able to find any way to do this.

I'm assuming the main issue affecting users is the 1.8.0_66 JRE lacking the required CA certs that have been causing HTTPS errors with MARTI.  I suspect that issue could arise again in the future, as CA certs get renewed.

Given that we can't find a way to automatically upgrade bundled JREs, I wonder if we should just drop them and have users manually install Java, when required?  If they can download and install TripleA, it's likely they can do the same for a compatible JRE.

**Comment by ssoloff** [comment] 2018-11-15 22:13
Actually, while the install4j documentation came up empty, this [SO question](https://stackoverflow.com/questions/31681816/install4j-jre-bundle-is-not-updated) seems to indicate it may be possible to upgrade a bundled JRE.  I will investigate.

**Comment by RoiEXLab** [comment] 2018-11-15 23:42
If everything fails, we could also investigate bundling custom java 9+ runtime images with every installer.
Of course this gets more feasible the more the code is clearly separated from each other because this would reduce the filesize by a lot.
But it would definitely be interesting to know how big a custom JRE would be in the current state of the code.

**Comment by ssoloff** [comment] 2018-11-16 02:05
I found the options mentioned in the linked SO question, and they both appear to be enabled in our installer:

![install4j-update-bundled-jre](https://user-images.githubusercontent.com/4826349/48593177-a1a1f480-e919-11e8-8cb8-0b2f09ac50aa.png)

I'll have to try installing 3635 first without an existing JRE, and then look at the installation log from 12226 to see what it is (or is not) doing.

Also, re-reading the install4j docs, I found a reference that mentions the bundled JRE will be updated when it is a **static** bundle, that is embedded within the installer media file.  There is no mention of such an update for a **dynamic** bundle, that is download-on-demand, which is what we currently use.

**Comment by panther2** [comment] 2018-11-16 08:34
The problem on Windows is that the "bundled" JRE is installed in either
`c:\program files\common files\i4j_jres\` or
`C:\Users\<username>\AppData\Local`

Some Windows users don't know that these paths and folders do even exist. So the i4j_jres installation is almost "invisible" to them. It does not appear in Windows Control Panel - where they are used to find all installed software - either.

The process of identifiying the Java version that actually is used by TripleA is hard for many, too.

For years I have recommended users to install Java from java.com instead of relying on the "bundled" install. To me this appears to be a transparent solution. Every Windows user can tell which Java is installed then, just by visiting the Control Panel. This prevents from problems.

**Comment by ssoloff** [comment] 2018-11-16 16:49
> I'll have to try installing 3635 first without an existing JRE, and then look at the installation log from 12226 to see what it is (or is not) doing.

I ran the above test.  Looking at the installer log during the upgrade, I confirmed the properties discussed at the above SO question are set correctly.  Unfortunately, there is no indication install4j even attempts to update the bundled JRE.

I created a support ticket with ej-technologies to determine if bundled JRE updates apply to dynamic bundles (what we're using) or just static bundles.

**Comment by ssoloff** [comment] 2018-11-16 21:01
@simon33-2 I don't believe we have any control over the bundled JRE installation process beyond enabling it and specifying what version we want installed.  All the details of installing it appear to be buried inside the install4j runtime.  In fact, it's so low-level, it occurs while bootstrapping the installer.  The installer itself requires a JRE to run, so I believe it's some native bootstrap code that is responsible for installing the bundled JRE before the Java installer is actually launched.

I'm still waiting on a response to my support ticket.  If it turns out there's no way to upgrade a dynamic bundled JRE, then I think what myself and @panther2 suggested above should be considered: namely, removing the bundled JRE altogether.  But, as an optional extension to that idea, we could also provide parallel installers that include a statically-bundled JRE for users who truly don't want to be bothered with installing a JRE.  The benefit of the static bundle is it will be properly upgraded.  The biggest drawback is the download size will increase by several tens of MiB.  But I think that's offset by providing JRE-free installers that will be the same size as today's installers.

**Comment by ssoloff** [comment] 2018-11-17 03:07
@simon33-2 Sorry for not thinking that through a bit more.  My proposal was that users would see _both_ installers on the GitHub releases page.  For example:

```
TripleA_1.10.0.0.13067_macos.dmg
TripleA_1.10.0.0.13067_macos_nojre.dmg
TripleA_1.10.0.0.13067_unix_nojre.sh
TripleA_1.10.0.0.13067_windows-32bit.exe
TripleA_1.10.0.0.13067_windows-32bit_nojre.exe
TripleA_1.10.0.0.13067_windows-64bit.exe
TripleA_1.10.0.0.13067_windows-64bit_nojre.exe
```

Then on `triplea-game.org`, I guess we'd just pick one to point to.  I tend to agree with you that the installer with the bundled JRE would be the most appropriate.  In the secondary text that pops up once you click a download link, we could provide a short blurb and a link to the other installer (e.g. "Already have Java installed?  Click here for a smaller download.").  That way, an observant user will have access to both installers per platform (sans Unix) from the download page.  And veteran users will eventually learn how to directly download the `nojre` version if they wish to maintain their own version of Java.

**Comment by simon33-2** [comment] 2018-11-17 03:47
I don't think there was any question that users would see both installers on the github releases page, but that is not where most of them go to download the game.

Sounds like we're in agreement that the aggregated installer should be the main one. Perhaps we should have some small text only links to grab the no-jre installers?

**Comment by simon33-2** [comment] 2018-11-17 03:51
Of course, the bundled JREs wouldn't cause any problem if they weren't actually being used. Is it not possible to just ignore such pests?

**Comment by simon33-2** [comment] 2018-11-17 04:52
So if we used the custom search sequence we could kill the use of Java 8-66 once and for all and in a new release? Or is that not realistic?

**Comment by ssoloff** [comment] 2018-11-17 05:40
I don't know exactly what's possible with that feature.  It will require some investigation.

**Comment by panther2** [comment] 2018-11-17 11:55
When users on axisandallies.org are now forced to update their TripleA to at least https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.13066 I am sure that many will run into the outdated i4j_jres issue.

**Comment by ssoloff** [comment] 2018-11-20 04:16
I received a response to my install4j support ticket.  It was confirmed that, when using a dynamic bundle, any existing bundled JRE on the system **will not** be updated.

So, it sounds like we should drop the dynamic bundle given that we have no control to update older JREs that may have been previously installed by TripleA.  Therefore, based on the all the previous comments, I see three possible alternatives (please add any other I may not have thought of):

1. Use a static bundle,  This will increase Windows and Mac installer sizes by 30-40 MiB (the Unix installer does not support a bundled JRE).  (**NOTE:** Per ej-technologies support (but I haven't confirmed), if we include a newer static bundle, it will update any existing bundled JRE, even if it was originally installed via a dynamic bundle.)
1. Do not bundle a JRE at all. This will require users to always install Java themselves.
1. Provide two installers per platform: one with a static bundle and one without a bundled JRE.  This gives users the option to choose to download an installer with or without a bundled JRE.  The obvious drawback here is that the size of each GitHub release will increase by almost 100 MiB (about 2x what we use today), which will also require additional upload bandwidth from Travis.  I'm not sure if there's any limits on storage/bandwidth by GitHub/Travis that will cut us off (similar to what we encountered when using Git LFS).

Everyone please feel free to weigh in on what we should do with the bundled JREs going forward.

@DanVanAtta @RoiEXLab @ron-murhammer @simon33-2

**Comment by simon33-2** [comment] 2018-11-20 06:50
I'm voting option 3. Not sure if those issues you raise will be a problem though.

@panther2

**Comment by panther2** [comment] 2018-11-20 09:15
@ssoloff I tend to option2, as option 3 creates a lot of useless data with every commit leading to a new pre-release. But before definitely voting I have some additional questions:

1.
When using a static bundle - would that install (on Windows) again in
`c:\program files\common files\i4j_jres\` or
`C:\Users\<username>\AppData\Local\i4j_jres\` ?
Would that one leave a registry entry to appear in Windows Control Panel as Software installation?
(Different from a dynamic one that does **not** do so.)

2.
Can a bundled version instead be installed in
`c:\...\TripleA\i4jres\` ?
 (I remember "Minecraft" installations that bundled a JRE in the Minecraft directory)

That would be extremely helpful when giving support to users.

3.
Does a bundled version (actually I never installed one) install side by side next to a present Java (from java.com) installation? Or does it check whether there is already a system-wide Java present, and if yes, does not install at all?

4. 
Being aware that the difference between a pre-release and a release is just a tag - would it be somehow possible to create bundled versions according to your option 3 only for releases? Either automated or manually? Given the usually low frequency of releases - that could prevent from creating additional masses of data trash with every pre-release.


@simon33-2

**Comment by panther2** [comment] 2018-11-20 16:29
Thank you, @ssoloff .

A bundled Java inside the TripleA directory would definitely be a huge improvement.

So all in all this is my vote:

If we can somehow figure out a way to bundle only the releases I would vote for this option (installing a bundled Java inside the TripleA directory).

If the consequence of bundling is creating data masses for every pre-release I would vote for not bundling Java at all. From a user-support point of view this appears to be the easiest solution anyway.


Either way we still need to identify which Java version actually is used by TripleA once the user runs into any Java issues. I wonder if that info could be stated in the UI (maybe under "Engine Preferences"). 
Still the user might have prehistoric i4jres-installations causing trouble on his system.

**Comment by ssoloff** [comment] 2018-11-21 05:57
> Either way we still need to identify which Java version actually is used by TripleA once the user runs into any Java issues. I wonder if that info could be stated in the UI (maybe under "Engine Preferences").

@panther2 Is there a reason asking the user to bring up the console and click **Properties** is not sufficient?  If you're not aware, users can now bring up the console without actually starting a game.  They can go into **Engine Preferences > Game** and enable the **Show Console** setting.  Clicking **Save** will immediately bring up the console.  (Not as simple as it used to be in 3635 when we had a dedicated button to do this under **Engine Preferences**, but much better than having to start a local game. :smile:)

If we really want to put the JRE version front-and-center, we could easily display it on the main screen either above or below the Engine Version, if you think that would help.

**Comment by panther2** [comment] 2018-11-21 07:55
@ssoloff 

> Is there a reason asking the user to bring up the console and click Properties is not sufficient? ...

Yes, I am aware of this. To you and me it is a breeze, indeed, but to many users this is a barrier. Giving support on Java issues sometimes takes a lot of time,...

> If we really want to put the JRE version front-and-center, we could easily display it on the main screen either above or below the Engine Version, if you think that would help.

It would help the supporter and the supported :smile:

**Comment by simon33-2** [comment] 2018-11-22 02:47
And identify the frigging build everywhere we display the version. It doesn't appear in any logs at present.

**Comment by ssoloff** [comment] 2018-11-22 18:49
> Please confirm my understanding of this problem is correct:
> - The 'install-if-needed' JRE with install4j is only installed once and then not updated on future TripleA versions.
> 
> Is that about right?

Correct.

> Second question, how much of a download file size increase are we talking about exactly?

Should be between 30-40 MiB, depending on the platform (~200% increase).

**Comment by DanVanAtta** [comment] 2018-12-10 05:18
An idea:
- have game detect java version, and if the version is less than a minimum then we'll show users a prompt asking them to download a bundled version.

This might let us keep the unbundled version as the recommended download. We can determine download counts from github releases, if we see there are majority more bundled downloads then unbundled, we'll know then the default should be for a bundled download.

**Comment by ssoloff** [comment] 2019-01-05 02:30
A Mac user noted in https://github.com/triplea-game/triplea/pull/4455#issuecomment-451595132 that, on a fresh macOS system with no JRE installed, the installer correctly downloads the bundled JRE, but then fails to find it post-download.

Just noting that here, as it's tangentially related.  However, it probably requires an issue of its own.  I'll create one if we can confirm it happens with the latest stable macOS installer.

**Comment by DanVanAtta** [comment] 2019-02-16 20:57
https://resources.ej-technologies.com/install4j/help/doc/index.html#install4j.helptopics.concepts.jreBundles

>  install4j offers you a number of strategies for JRE bundling. A statically bundled JRE is always distributed along with your application. Dynamical bundling means that if the installer cannot find a suitable JRE on the target computer, it will download a JRE bundle from your web server. 

> A shared JRE bundle will not be uninstalled when the application that has installed the bundle is uninstalled itself. If you dynamically bundle a JRE for multiple installers and install it as a shared JRE, only the first time when a user installs one of your installers, a JRE will be downloaded. Subsequent installations of other installers will find that shared JRE. 

----------

It sounds like if we unshare the bundled JRE, we can continue having an on-demand download of the JRE and it would then start to be updated when we updated the bundled JRE version. I'm hoping I'm not missing anything, seems like an easy fix for this.

**Comment by DanVanAtta** [comment] 2019-02-19 22:29
@ssoloff @simon33-2 , what do you think please of this plan:

(1) Create a static bundle installer and offer it to those having problems. We've had a lot of downloads and few reported problems. Given the relative success with the DL numbers, this makes me think we should continue with dynamic bundle installer as the download of choice
(2) Decide if we will go to Java 11 in the next release. If not then add a 'min java' check to the game that will prompt the user to download the installer with the static bundle
(3) If we can show there are problems with the dynamic-bundle, then we can stop offering them as needed.

**Comment by simon33-2** [comment] 2019-02-22 05:45
Sounds like an improvement to the status quo. At least if people have problems they can be referred to the bigger download.

**Comment by DanVanAtta** [comment] 2019-06-10 22:29
The JRE is now bundled, always: https://github.com/triplea-game/triplea/pull/4876

**Closed by DanVanAtta** 2019-06-10 22:29 UTC
Labels: Impact: Operations Overhead, discussion, problem
