### ISSUE TITLE
Lobby Admin Issues

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2204] opened 2017-08-12 03:59 UTC
1. Admins unable to Reset User Passwords and users can't reset their own password for the lobby.
2. Admins unable to add/remove lobby mods.
3. Additional issues listed here: https://forums.triplea-game.org/topic/288/lobby-admin-toolbox-issues-discussion

**Comment by ssoloff** [comment] 2017-08-12 04:10
Just annotating with some history here...  It looks like this feature was purposely removed in fe55b98.  The comment states:

> Moderator password reset needs to be re-done.

**Comment by ron-murhammer** [comment] 2017-08-12 04:12
@ssoloff Yeah, I think we didn't fully consider the issue and the thought was there would be fast follow on features to address these gaps.

**Comment by ssoloff** [comment] 2017-08-12 04:18
Would simply reverting the portion of the change in the lobby client be an acceptable interim solution?  That is, when using this feature from a pre-release client, it would only work when connecting to the production (3635) lobby server, and would be a no-op when using the test lobby server.

**Comment by ron-murhammer** [comment] 2017-08-12 04:23
@ssoloff I think the problem is deeper than that. When banning by IP and MAC you need to enter that information. It used to be retrieved from the database by searching for specific users which admins no longer can do. So there is no way for them to figure out IP/MAC in order to actual ban it.

**Comment by ssoloff** [comment] 2017-08-12 04:39
@ron-murhammer Sorry, I should have clarified that my previous comment was specifically referring to password reset.  Does that require knowing more than just the user name, which presumably the user could provide to an admin via the forum or anonymous login to the lobby?

Even in that case, I think I see what you're talking about.  The previous implementation only allowed you to reset the password for a logged-in user.  A user who needs their password reset probably would not be logged in. :smile:

We could add a similar command to the **Admin > Toolbox** menu which prompts the admin for the user name, and then just run the legacy code that called `IModeratorController#setPassword()`.

I think a self-service password reset feature would have to wait until the lobby supports a different network API that would allow a user to trigger it from an URL embedded in an email or something.  That's probably related to what @DanVanAtta was experimenting with [here](https://github.com/triplea-game/triplea/issues/1505#issuecomment-318846873).

**Comment by ssoloff** [comment] 2017-08-12 04:42
> which presumably the user could provide to an admin via the forum or anonymous login to the lobby

I guess a problem with that method is verification.  If the admins can't pull the registered email from the DB, then how do they know the user requesting the reset is who they say they are?  (Presumably an admin would send a message to the registered email to confirm the user's identity.)

**Comment by ron-murhammer** [comment] 2017-08-12 04:43
@ssoloff Yeah, exactly. I think the challenge is a number of the old functions relied on mods/admins being able to look info up in the database or make changes in the database. Since they no longer have access to it, they can't do a number of functions which is causing frustration. I agree that the long-term solution is having a self-service password reset for users for at least that issue. Btw, if you wanna chat this evening we can do so on gitter.

**Comment by prastle** [comment] 2017-08-12 13:05
correct @ssoloff  
and since the database is non access really we cant fix much when a problem occurs

**Comment by Cernelius** [comment] 2017-08-12 13:22
The procedure is up to you to decide, but, just for the record, we already had this discussion and I still strongly advise you open this matter in bunker, not in an Issue here. Of course, the code is open source and the pull requests to address the problems are too, but at least I advise you don't go around openly telling everyone how people are banned in not-secreted tickets or topics.
Meaning here I suggest you delete the points 2 and 3 and all related discussions at this topic.
What I'm suggesting is to track all such matter in the secreted bunker, and just pull requests in here, without issues tracking, or, in general, whatever maximises secrecy.
For an example, I suggest reading:
https://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=2135

**Comment by prastle** [comment] 2017-08-12 13:24
Agree cer.

**Comment by prastle** [comment] 2017-08-12 13:32
Created a new topic here

https://forums.triplea-game.org/topic/288/lobby-admin-toolbox-issues-discussion

**Comment by prastle** [comment] 2017-08-12 13:44
Invited @ssoloff  and  CrazyG to mod and adjusted admin priveleges for the admin topic category

**Comment by ron-murhammer** [comment] 2017-08-12 16:44
@prastle @Cernelius Moved any sensitive items to https://forums.triplea-game.org/topic/288/lobby-admin-toolbox-issues-discussion.

**Comment by Cernelius** [comment] 2017-08-12 18:40
My suggestion was actually to edit out whatever gives sensitive info.
For example also stuff like:

> When banning by XXX and YYY you need to enter that information.

etc.

**Comment by prastle** [comment] 2017-08-12 18:59
I know @Cernelius  but, "The cat was let out of the house a few years ago!"  above matters little now sadly.

**Comment by Cernelius** [comment] 2017-08-12 19:19
No. Of course everything sensible has been removed in the WarClub.
If somebody reads here, he can perfectly know what mods can or cannot ban, exactly, while otherwise there is currently not other way to know it but delving in the code or experimenting with getting banned and trying to rejoin.

**Comment by prastle** [comment] 2017-08-12 21:41
I will clarify.  I agree above should be deleted.  Except this was already stated elsewhere in github posts earlier months and months ago.  Thus it kinda doesn't matter unless they delete all the threads that talked about this.

**Comment by DanVanAtta** [comment] 2017-08-14 20:45
Should note for context of the regression, the real regression is the runtime config of derby broke and was no longer accessible via the moderator console. Anyone is still welcome to look into that, after spending a few days trying to find that, I figured it would be more productive to move to a replacement DB. It took about a few days to do the postgres work, and a few days for the ops deployment pieces of the new DB, but now it has been taking a few weeks to get the testing done and the postgres DB launched.

**Comment by DanVanAtta** [comment] 2017-08-14 20:50
So, are we tracking this in a forum post, or here?  I sense the forum post is security theater:
- we are more likely to get random developers interested in finding a security project to contribute to by having a public issue than we are to actually give away information to the 3 or 4 trolls that already have our banning system defeated. Why would they take the time to search here, read through this, decipher what is current, when they are already trolling to their hearts content? What would even motivate them to look here, to see how they could troll further?
- the change of conversation to "we should move this to somewhere" I think at best has been distracting. I suggest we do close this and track it in the forum so we can have one place to cover this topic.

**Comment by prastle** [comment] 2017-08-14 21:03
I hate to say but i agree.  More help would be achieved here than forum.  But do we want our dirty  laundry public?  You offer tough choices bro. .... :)

**Comment by ron-murhammer** [comment] 2017-08-15 00:16
@DanVanAtta I fine tracking it here or in the forum. I'll leave it up to you since you are currently working on the DB migration. Just wanted to highlight functionality that is currently missing as I didn't see any issue or thread covering it.

**Comment by DanVanAtta** [comment] 2017-08-15 20:55
Let's do forum to keep it one place: https://forums.triplea-game.org/topic/288/lobby-admin-toolbox-issues-discussion/

**Closed by DanVanAtta** 2017-08-15 20:55 UTC
Labels: close pending confirmation, regression, type: bug
