### ISSUE TITLE
NPE when starting new PBEM game

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#3880] opened 2018-08-24 15:46 UTC
### Engine version

1.9.0.0.11547

### My Operating System

Linux localhost.localdomain 4.17.11-200.fc28.x86_64 <span>#</span>1 SMP Mon Jul 30 15:21:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Map name

Classic: Iron Blitz 3rd Edition 2.0

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

* Start PBEM game.
* Select dice server **Internal Dice Roller**.
* Select PBEM **Gmail** and enter appropriate configuration.
* Play.

Error dialog displayed after map window appears.

### Do you have the exact error text? Please copy/paste if so

```
Aug 24, 2018 11:37:04 AM games.strategy.engine.framework.GameRunner lambda$0
SEVERE: null
java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:240)
	at games.strategy.triplea.ui.CommentPanel.lambda$3(CommentPanel.java:100)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Instead of this error, what should have happened?

No error dialog should be displayed.

### Any additional information that may help

This only happened once.  I wasn't able to reproduce it after the fact.  I doubt it has anything to do with a PBEM game, per se, but that's the type of game I was starting when the exception was raised.

**Comment by RoiEXLab** [comment] 2018-08-24 17:06
This is a duplicate of #3473 I thought #3496 fixed.
This issue is really weird and not supposed to happen at all.

**Closed** 2018-10-09 02:47 UTC
Labels: category: bug
