### ISSUE TITLE
Mouse horizontal scrolling 

### ISSUE THREAD

**Issue by lensz** [triplea-game/triplea#1422] opened 2017-01-03 02:52 UTC
More of a suggestions than an issue: Add horizontal mouse wheel scrolling of the map

I am able to scroll the map vertically with my mouse wheel, but horizontally is not possible.

Would be nice to have this functionality, because it would make scrolling on my laptop (nibble mouse) much easier instead of awkwardly holding right click.

**Comment by Cernelius** [comment] 2017-01-03 09:40
I've always thought that in a strategic game like TripleA the mouse wheel should be reserved primarily to zoom in and out (thus only vertical, for this), as in strategic games normally you want to do it quite frequently.

But in TripleA the zoom is so bad looking and changing it is such a delayed and clumsy and bad working process (keep Alt pressed and move the mouse wheel to zoom a map in and out to see what I'm talking about) that I never felt suggesting having the mouse wheel set on changing the zoom as default (unless it would perform like in whatever strategic games out there, as a matter of rapidity and quality).

It would be interesting to know how many people like to use the mouse wheel for scrolling the map; myself I never do, and almost always use the right click - drag.

But this is sort of off topic; adding horizontal scrolling would be a surely good feature advancement, and if to have scrolling or zooming default would be another matter anyways (I'm not suggesting it, until the scroll zooming is so bad).

**Comment by lensz** [comment] 2017-01-05 01:41
I looked a bit into it and I noticed, that scrolling while holding the `shift` button does scroll the map horizontally.

A native support of the horizontal scroll wheel would be better though, because I guess it would also support diagonal mouse wheel action and stuff like this.

**Comment by RoiEXLab** [comment] 2017-01-06 15:06
Duplicate of #574
I requested this feature as wel...
The problem is, that the Java Swing Framework tripleA is using isn't supporting such an action \:(
This feature will be implemented when we switch to another framework like JavaFX (A lot of work)

**Comment by DanVanAtta** [comment] 2017-01-09 02:36
@RoiEXLab  do you know if we could update feasibly the map scroll listener to use JavaFX event handling? Basically use JavaFX just for this one feature/area? Any thoughts if that would be an easy or difficult task to accomplish?

**Comment by RoiEXLab** [comment] 2017-01-09 06:26
I tried replacing the game frame with a jfxpanel, so we could still keep 99% of the code.
The problem if we embed javafx inside swing is, that we still only receive swing events.
So we would have to do it the other way round, embed a swing frame inside a javafx stage and call a custom method once the event is fired

**Comment by lensz** [comment] 2017-01-09 23:45
I don't know if this help, but on stackoverflow, there is an answer to a similar [how-to-do-horizontal-scrolling-with-swing](https://stackoverflow.com/questions/2843314/how-to-use-my-trackpad-for-horizontal-mousewheel-scrolling-in-a-java-awt-scrollp?noredirect=1&lq=1) posted:

> This is supported by default in Swing although vertical scolling has priority over horizontal scrolling when both scrollbars are visible.
> [..]

To be honest I don't exactly now what he means by this, when the swing mouse event clearly only talks about scroll amount and not direction. But maybe you can get something out of it.

**Closed** 2017-06-27 22:30 UTC
Labels: category: game engine > UI, ice box - revisit later, type: feature request
