### ISSUE TITLE
Enhance Politics Notifications To Allow For Only Target Players (Feudal Japan, etc)

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3558] opened 2018-07-17 03:52 UTC
Politics notifications in Feudal Japan map go to all players.

On map Feudal Japan, when player A makes peace with player B, then every other player C gets a popup with text "We have made peace, they are afraid of our mighty army.".

This text clearly is not meant to be sent to players not involved in the deal. It should only be sent to player B.

Looking how it's set up, it seems it uses the following property:

Peace.OTHER_NOTIFICATION_SUCCESS=We have made peace, they are afraid of our mighty army.
https://github.com/triplea-maps/feudal_japan/blob/f602a7ec216c62acecf5a36448fe6a6e55f96291/map/politicstext.properties

And that property is coded to give notifications to all other players. It seems like the engine should provide another property that would only go to the deal receiver. And the map could use that.

---
**Changes:**
This is an engine change to support 2 new properties in politics text properties (TARGET_NOTIFICATION_SUCCESS & TARGET_NOTIFICATION_FAILURE). Which allow map makers to send certain messages to only the "TARGET" of the political action.

Example:

For example Feudal Japan currently:
```
War.BUTTON=Declare War!
War.DESCRIPTION=Put the heads of those cowards on our spears!
War.NOTIFICATION_SUCCESS=We are at war, may those cowards die quickly and honourless!
War.OTHER_NOTIFICATION_SUCCESS=They have declared War on us, may their blood fill the seas!
```

Should become:
```
War.BUTTON=Declare War!
War.DESCRIPTION=Put the heads of those cowards on our spears!
War.NOTIFICATION_SUCCESS=We are at war, may those cowards die quickly and honourless!
War.TARGET_NOTIFICATION_SUCCESS=They have declared War on us, may their blood fill the seas!
War.OTHER_NOTIFICATION_SUCCESS=NONE
```

**Comment by asvitkine** [comment] 2018-07-17 03:56
So perhaps we can add a boolean property that specifies whether the notification should be sent to one player or all. And have the map set that boolean property.

This way, there's still compatibility between old/new map versions and old/new engines.

**Comment by asvitkine** [comment] 2018-07-17 04:20
An "incompatible" way to do this would be to introduce a separate property - PARTICIPANTS_NOTIFICATION_SUCCESS - which only go to the players participating. But the problem with this is if an older engine reads a map with this new property, without the OTHER_NOTIFICATION_SUCCESS property, then there will be no text to responders.

**Comment by ron-murhammer** [comment] 2018-07-17 22:07
@asvitkine I'd prefer the second solution here as its much cleaner and fits with the existing properties better. As long as maps wait til this is released in the next stable (should be soon) then as long as both players use the latest stable then they wouldn't have any issues and the worse case is they miss notifications.

**Comment by asvitkine** [comment] 2018-07-17 23:53
Ok, I wasn't sure what level of compatibility we wanted. If second solution is acceptable, I'll do it that way. I agree it's cleaner.

**Comment by asvitkine** [comment] 2018-07-18 01:35
I agree it would be cleaner to not need to set it to "NONE". It's not what the code currently does, though.

I think it's a bit orthogonal - I can submit a separate PR to clean that up - basically to treat both "NONE" and the property not existing the same way.

**Comment by Cernelius** [comment] 2018-07-18 01:49
Ok, thanks for the details @asvitkine. That leaves me with only a couple of remaining doubts.

1) Can you confirm that if both a TARGET and a OTHER valid notifications are present, the OTHER notification will not be displayed to those receiving the TARGET.

2) Can you confirm that if, instead of being absent, there is a TARGET notification set to NONE, the target players receive no notifications, while everyone else but the maker receives the OTHER one.

@ron-murhammer Since this is not a perfect world, I definitely advise against ever having a behaviour of not displaying anything if absent, as that would bury game bugs and be an issue in the map development process, as you normally first code the xml, then add the text for the skin. "NONE" for not having something displayed is the way to go, tho I would personally prefer that is done by having the notification entry present, but left empty, instead of having it as "NONE" (very minor matter, as I don't think you want to display a "NONE" anyways).

On the other hand, I believe the behaviour of first searching in TARGET and, if absent, searching in OTHER is acceptable, as long as there is something, at the end of the priority list, that, if absent, gives a default message of some sort, instead of nothing.

It may be good having a way to set any kind of notifications to none, instead of having to set each one of them. In this case, Feudal Japan could be updated just adding a couple lines that set all OTHER_NOTIFICATION_SUCCESS and OTHER_NOTIFICATION_FAILURE to none, beside mass changing the existing OTHER to TARGET.

Also, are you sure you wouldn't prefer to be notified about what's happening between others, with notifications like "X has declared war on Y, may the fools drown in their own blood!". For Feudal Japan in particular, maybe better not, considering the spam of AI with AI actions, but I'm not sure.

**Comment by veqryn** [comment] 2018-07-18 03:22
Sounds like a problem with the map not the engine.
Just change the text for "OTHER" notifications.

**Comment by Cernelius** [comment] 2018-07-18 03:47
For the Feudal Japan case, you would probably want to know what the other human players are doing, with a notification like "X has made an alliance with Y, those weaklings are truly desperate.". The AI with AI actions are tons, but probably the only ones you don't really want to see are the failure ones, also since it is not a big deal spamming the OK button. Probably the most hardcore players might want to know everything in the moment they could get prompted anytime to accept something, and there is no way to put that on hold and go opening the politics tab to see what's what, but I think it would rarely make a difference on your choice.

**Comment by Cernelius** [comment] 2018-07-18 04:08
Just really don't have the notification not displayed if absent. That needs to be a NONE or an empty text (I tend to prefer not displaying if empty over not displaying if NONE). That needs keep working as it does now, in all cases, getting a default raw notification, because, in the moment you make a map, first you do the xml stuff, then you customize the text that you get, while you can still test them before doing that skin part. Plus, of course, getting a notification with a missing text is a better way to notice you are missing it or named it wrongly. Maybe the default, non customized, notification may be improved, to be fairly readable, making the politicstext.properties something optional like the tooltips.properties, but it's not really important, I think.

**Comment by veqryn** [comment] 2018-07-18 04:10
Reading through the logic and trying to remember: https://github.com/triplea-game/triplea/blob/5e2a3f3da5ced60856f3f092f81a62b79c9b41f6/game-core/src/main/java/games/strategy/triplea/delegate/UserActionDelegate.java#L215-L243

I believe the way it was implemented expected that the text would read something like:
```
War.NOTIFICATION_SUCCESS=We have declared war on Japan
War.OTHER_NOTIFICATION_SUCCESS=The USA has declared war on Japan
```

Having to separate the target out from all "others" will be difficult to do when you have multiple players and shifting alliances.
For example, if a has country A declare war on country B, and I control both countries B and C, should I get 1 notification or 2?
Ideally, you would still get only 1 notification.

**Comment by ron-murhammer** [comment] 2018-07-18 04:20
@veqryn The way it was implemented is that you only ever get 1 notification and TARGET takes precedence over OTHER. So in your example, let's say I wanted more custom messages and did this:
```
War.NOTIFICATION_SUCCESS=We have declared war on Japan
War.TARGET_NOTIFICATION_SUCCESS=The USA has declared war on us
War.OTHER_NOTIFICATION_SUCCESS=The USA has declared war on Japan
```
USA would get the first one.
Japan would get the second one.
All other players get the third one.

**Comment by veqryn** [comment] 2018-07-18 04:45
Carry on

**Comment by Cernelius** [comment] 2018-07-18 04:47
@veqryn Nothing will change for the maps that won't be changed themselves. So, yes, this is a mix of a map specific change and an additional feature disposable for new maps.

>For example, if a has country A declare war on country B, and I control both countries B and C, should I get 1 notification or 2?
Ideally, you would still get only 1 notification.

@veqryn I already touched this matter in a previous post at this issue (and I hope the developers will consider all details as well). In this case, under my suggestions, you would get the TARGET notification but not the OTHER notification. Practically, the same as you would be only in control of country B. You can expect the mapmaker to code the map in a way to make the TARGET notification meaningful, if you are supposed, by that same map, to control both B and C (the notification won't just say "You have been declared war.", assumingly, that would be a TARGET notification only pure FFA games, like Feudal Japan or the FFA mods of Napoleonic Empires, in which you must always be only 1 country, should have (and, in that case, you should just never be both B and C, as said)).

Also, the display can be improved. Currently, for example, in Feudal Japan you get OTHER (soon to be TARGET) notifications like this:

![20180718_feudal japan_001](https://user-images.githubusercontent.com/19562310/42859959-63ca860e-8a55-11e8-91ff-9a1776dd6bf2.png)

There is no point having in the title what you have in the description, so you can have in the title rather something "Political notification to Chosokabe", that would practically solve this issue, as well (albeit I agree that distinguishing between TARGET and OTHER is nice and helps adding flavour to the descriptions).

And, off topic, I would also change the name of the in game players from "player" to "country" or "power", to avoid confusion with the users playing the games (as sometimes a player controls multiple countries), but that has been discussed in forum, and nobody agreed with me.

**Comment by Cernelius** [comment] 2018-07-18 05:03
Also, I prefer if "politics" would be called "diplomacy", as that would be the correct way to call it. So, I would rather have an autodisplay as "Diplomatical notification to Chosokabe", but that would need changing a lot (only of user display, not xml coding, of course) from "Politic" to "Diplomatic", and that's just my preference. Merely a side note here; I know it will stay politic, sadly.

https://en.oxforddictionaries.com/definition/politics

> The activities associated with the governance of a country or area, especially the debate between parties having power.

(political relations between states being only a part of it)

https://en.oxforddictionaries.com/definition/diplomacy

>The profession, activity, or skill of managing international relations, typically by a country's representatives abroad.

**Closed** 2018-07-18 20:58 UTC
Labels: category: feature request, close pending confirmation

**Comment by Cernelius** [comment] 2018-07-23 14:43
Why has this been closed? Has everything been defined and documented?

Also, can we please remove that light bulb on the right, in all notifications. It just pushes the stuff to the right and it has no real value.

**Comment by Cernelius** [comment] 2018-07-23 14:47
I'm particularly interested to know what is the intended behaviour in the case @veqryn pointed out, and it making it reliably stable, by well documenting it in pos2.

>For example, if a has country A declare war on country B, and I control both countries B and C, should I get 1 notification or 2?

I'm making a game with politics with 5 alliances and 16 players. So, this is relevant to me.

**Comment by General-Dru-Zod** [comment] 2018-08-25 05:08
I have a very complex diplomatic logic in my Bad-Ass 4 Nation FFA. It is most likely the most intricate version out there. Not to mention it also uses point of agreement rather than generic end of round in the logic. This gives every player completely fair diplomacy, meaning the last in turn order does not get burned. So much was said above, that it isn't very clear on final cut. Can someone quickly post a brief description of end result.

**Comment by General-Dru-Zod** [comment] 2018-09-06 17:37
Just reposting this one incase no one noticed it.  @Cernelius and @ron-murhammer I have a very complex diplomatic logic in my Bad-Ass 4 Nation FFA. It is most likely the most intricate version out there. Not to mention it also uses point of agreement rather than generic end of round in the logic. This gives every player completely fair diplomacy, meaning the last in turn order does not get burned. So much was said above, that it isn't very clear on final cut. Can someone quickly post a brief description of end result.

**Comment by Cernelius** [comment] 2018-09-06 18:32
@General-Dru-Zod I'm in your shoes. Still have to understand why this was even closed, since nothing was clarified.

**Comment by ron-murhammer** [comment] 2018-11-08 05:43
@General-Dru-Zod @Cernelius This is an engine change to support 2 new properties in politics text properties (TARGET_NOTIFICATION_SUCCESS & TARGET_NOTIFICATION_FAILURE). Which allow map makers to send certain messages to only the "TARGET" of the political action.

The way it was implemented is that you only ever get 1 notification and TARGET takes precedence over OTHER. For example, let's say I wanted more custom messages and did this:
```
War.NOTIFICATION_SUCCESS=We have declared war on Japan
War.TARGET_NOTIFICATION_SUCCESS=The USA has declared war on us
War.OTHER_NOTIFICATION_SUCCESS=The USA has declared war on Japan
```
USA would get the first one.
Japan would get the second one.
All other players get the third one.

**Comment by asvitkine** [comment] 2019-09-16 00:34
I think I never ended up making the change to Feudal Japan for this.

I also noticed that other FFA maps are affected today. In particular, Napoleonic Wars FFA.

So I can take a look at making these follow up changes to the maps to take advantage of the new engine feature.
