### ISSUE TITLE
Invasion U.S.A. Scenario Does not Run

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#1560] opened 2017-03-03 01:18 UTC
When trying to run the scenario, it just goes back to menu. The console shows:

Loading map: Invasion_USA, from: C:\Users\Judy\triplea\downloadedMaps\invasion_usa-master.zip
Loading resources from the following paths: [C:\Users\Judy\triplea\downloadedMaps\invasion_usa-master.zip, C:\Program Files\TripleA_1.9.0.0.3266\assets]
Could not find: Invasion_USA/ doc/images/invasionusa.png
Loading map: Invasion_USA, from: C:\Users\Judy\triplea\downloadedMaps\invasion_usa-master.zip
Loading resources from the following paths: [C:\Users\Judy\triplea\downloadedMaps\invasion_usa-master.zip, C:\Program Files\TripleA_1.9.0.0.3266\assets]
Could not find: Invasion_USA/ doc/images/invasionusa.png
Loading map: Invasion_USA, from: C:\Users\Judy\triplea\downloadedMaps\invasion_usa-master.zip
Loading resources from the following paths: [C:\Users\Judy\triplea\downloadedMaps\invasion_usa-master.zip, C:\Program Files\TripleA_1.9.0.0.3266\assets]
Loading map: Invasion_USA, from: C:\Users\Judy\triplea\downloadedMaps\invasion_usa-master.zip
Loading resources from the following paths: [C:\Users\Judy\triplea\downloadedMaps\invasion_usa-master.zip, C:\Program Files\TripleA_1.9.0.0.3266\assets]
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at games.strategy.triplea.TripleA.startGame(TripleA.java:122)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:49)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$116(AbstractLauncher.java:43)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Error in resource loading. Unable to load expected resource: polygons.txt, the error is that either we did not find the correct path to load. Check the resource loader to make sure the map zip or dir was added. Failing that, the path in this error message should be available relative to the map folder, or relative to the root of the map zip
	at games.strategy.triplea.ui.mapdata.MapData.<init>(MapData.java:155)
	at games.strategy.triplea.ui.UIContext.internalSetMapDir(UIContext.java:77)
	at games.strategy.triplea.ui.AbstractUIContext.setDefaultMapDir(AbstractUIContext.java:118)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:227)
	at games.strategy.triplea.TripleA.lambda$startGame$335(TripleA.java:124)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Loading map: , from: C:\Users\Judy\triplea\downloadedMaps\
Loading resources from the following paths: [C:\Users\Judy\triplea\downloadedMaps\, C:\Program Files\TripleA_1.9.0.0.3266\assets]

I think the problem is the space in "Invasion_USA/ doc/images/invasionusa.png" but I don't where the bad code is.

**Comment by ssoloff** [comment] 2017-03-03 03:11
Just wanted to note that the space in the path is probably a red herring.  It's actually hard-coded in the log message itself (from [`games.strategy.util.LocalizeHTML`](https://github.com/triplea-game/triplea/blob/master/src/main/java/games/strategy/util/LocalizeHTML.java#L98)):

```java
System.out.println("Could not find: " + mapNameDir + "/ " + ASSET_IMAGE_FOLDER + imageFileName);
```

**Comment by ssoloff** [comment] 2017-03-03 03:51
The root cause of the problem appears to be an incorrect value for the [`mapName`](https://github.com/triplea-maps/invasion_usa/blob/master/map/games/Invasion_USA_1.5.0.xml#L1702) property:

```xml
<property name="mapName" value="Invasion_USA" editable="false"/>
```

At least on *NIX, it's apparently case sensitive.  Changing it to "invasion_usa" allowed me to start the game (and fixed the missing _doc/images/invasionusa.png_ image error on the game notes page):

```diff
diff --git a/map/games/Invasion_USA_1.5.0.xml b/map/games/Invasion_USA_1.5.0.xml
index 4cbcb34..de8563b 100644
--- a/map/games/Invasion_USA_1.5.0.xml
+++ b/map/games/Invasion_USA_1.5.0.xml
@@ -1699,7 +1699,7 @@
         </property>
 
                 <!-- Map Name: also used for map utils when asked -->
-                <property name="mapName" value="Invasion_USA" editable="false"/>
+                <property name="mapName" value="invasion_usa" editable="false"/>
 
                <property name="notes"> 
                <value>
```

It looks like the other game XML files for this map have the same issue.  Any PR should probably hit all three.

**Comment by panther2** [comment] 2017-03-03 07:35
> EDIT: The OP is on Windows but is loading the map from a zip archive. URLClassLoader appears to be case sensitive, at least for the jar/zip scheme. I suspect that if one were to clone from Git or explode the zip archive, and load the map from there, the problem would not occur on Windows due to its case-insensitive file system.

Being on Windows, too. I have experienced that 
<property name="mapName" value="any_map" editable="false"/>
is case sensitive in either scenario: zipped, unzipped, cloned.

**Comment by ssoloff** [comment] 2017-03-03 18:14
Thanks for the background information, @panther2.  With regards to the case sensitivity of `mapName`, I should have been clearer that I was talking about only those places where it is used in a file path, where it might work on Windows if it had the wrong case.  However, `mapName` appears to be used for all sorts of things within a game, so I agree with your observation that, in general, it is treated in a case-sensitive manner regardless of platform.

Just out of curiosity, I wanted to test the theory about this map working on Windows when loaded from a folder instead of a zip.  When I say "working," I only mean that I can start the game--I have no idea if I could actually play it to completion with the `mapName` as is.

I installed TripleA 1.9.0.0.3832 on a Windows box and cloned `triplea-maps/invasion_usa` into `%USERPROFILE%\triplea\downloadedMaps`.  (I had to edit each game XML file to remove the DTD due to the [bug](https://github.com/triplea-game/triplea/issues/1547) you previously reported, but I didn't touch the `mapName` property, which I verified was `Invasion_USA`.)  After starting TripleA, I was able to select the Invasion USA map and start a local game without error.

I verified that when loading a map from a cloned repo, the `URLClassLoader` is using the `file` scheme.  My guess is that, for such a scheme, the URI path is passed directly to the native file system for processing, which would explain why the path is treated in a case-insensitive manner on Windows, as observed above.

**Comment by panther2** [comment] 2017-03-03 19:27
Very interesting, thanks so much for sharing your observations, @ssoloff . 

I am glad you pointed out the removal of the DTD from the XML - that is exactly the workaround that I was asking for in #1547 - for any reason that did not come to my mind. That finally enables me to download and test the latest version.

**Comment by RogerCooper** [comment] 2017-03-04 01:10
I have already had the experience of games working in the folders, but not when they are zipped. I always test my games both ways. This scenario was in the repository, has it been fixed or should I post a fix myself.

**Comment by ssoloff** [comment] 2017-03-04 01:51
@RogerCooper, I have a fix prepared.  I will try to submit a PR in the next few hours.

**Comment by panther2** [comment] 2017-03-04 08:29
@ssoloff 
I am still a bit confused: I have downloaded the (so far unchanged) zip file from the repo, so this is the one containing the `mapName` with capitals. I am on Windows 7 (64bit).
When using starting TripleA using the map-zip, this is what happens:
![1](https://cloud.githubusercontent.com/assets/20812775/23577314/41898a28-00bc-11e7-851f-f98b855a9e34.gif)

When replacing the zip-file with the unpacked folder-structure, this is what happens:
![2](https://cloud.githubusercontent.com/assets/20812775/23577324/5fd0d27a-00bc-11e7-9295-c90b7995345b.gif)

I can only run the game without issue when changing `mapName` to lower cases, as you did in your above mentioned pull request.

So it appears, that here Windows is case sensitive in either way.

**Comment by ssoloff** [comment] 2017-03-04 15:41
@panther2 

> When replacing the zip-file with the unpacked folder-structure, this is what happens

When you unpack the zip archive, the map will be in a folder named `invasion_usa-master`.  Try renaming it to just `invasion_usa`.  I found I had to do that to get it to work (both on Windows and *NIX).  (When cloning, the folder is already named `invasion_usa`.)

I don't know if this is a true statement (and I don't have my dev environment in front of me at the moment to verify), but I think TripleA only supports `<mapName>-master` in the path when it is loading the map from a correspondingly-named `<mapName>-master.zip` file.  I remember seeing a class that handles this.  (A quick GitHub search turned up [`ResourceLocationTracker`](https://github.com/triplea-game/triplea/blob/de52f7ea14abb3d7d75b1431310a3fec27bcca62/src/main/java/games/strategy/triplea/ResourceLocationTracker.java), but I'm not sure if that class tells the whole story.)

If you are saying that you are able to get the map to load from the unpacked `invasion_usa-master` folder by just changing `mapName` to `invasion_usa` in the XML, then I'm afraid I can't explain why that works without further debugging. ☹️

**Comment by ssoloff** [comment] 2017-03-04 15:59
@panther2 

> Rethinking I am also wondering why this issue should be OS-dependent. I mean isn't it Java that searches for a directory name that matches the pattern as defined by the `mapName` ?

That would be true if the Java file system libraries were pure Java, but they ultimately delegate many operations to the native OS (asking if a file named `<something>` exists in the file system is one of those operations).  See [this SO question](http://stackoverflow.com/questions/1733770/how-to-avoid-filenotfound-exception-when-running-java-on-linux-because-of-case-s) for a classic example of "my code works on Windows but not on Linux" related to the file system.  The [accepted answer](http://stackoverflow.com/a/1733797/3900879) explains it well.

**Comment by panther2** [comment] 2017-03-04 19:54
@ssoloff 

Thank you for the Java-related link, very helpful!

Furthermore I can confirm you are right on the 'master'-extension.
I have done some more testing and found out that I accidentally thought that loading the map successfully from the unzipped folder structure was due to the correction of the 'mapName'. In fact it was due to the removal of '-master' from the folder name. On my first try (2 days ago) I did that and on my second try (that resulted in the second GIF) I simply forgot that.

So all in all I was now able to reproduce on my Windows that when
- loading the map from the -master.zip, the 'mapName' is case sensitive, so the map does not load when 'mapName' contains capitals,
- loading the map from the (unzipped) mapName-master folder fails,
- loading the map from the unzipped mapName folder (removing the -master from the folder name) works regardless of whether the 'mapName' contains capitals or not.

Again, thanks a lot, and I hope I did not waste too much of your time. :-)

**Comment by ssoloff** [comment] 2017-03-04 20:29
@panther2 No problem at all.  This is helping me, as well, learn more about how TripleA works by digging into some of the dark corners. :smile:

**Comment by RogerCooper** [comment] 2017-03-04 21:30
How do I upload the fixed file?

**Comment by ssoloff** [comment] 2017-03-04 21:48
@RogerCooper, are you talking about uploading a fixed `Invasion_USA_1.5.0.xml` file to the `triplea-maps/invasion_usa` repo?  A [fix](https://github.com/triplea-maps/invasion_usa/pull/14) has already been submitted--it is pending review before it can be merged.

**Comment by ssoloff** [comment] 2017-03-12 02:23
Bumping...

@ron-murhammer, I submitted some PRs to fix this issue about a week ago.  Those were my first map-specific PRs (triplea-maps/invasion_usa#14, triplea-maps/invasion_usa#15), so I may not have followed SOP.  Is there someone I specifically have to tag in a map repo to have them review those PRs?

**Comment by ron-murhammer** [comment] 2017-03-12 02:32
@ssoloff Merged them both. For maps, its a good idea to ping myself or Dan as we don't check the maps repos for PRs that much.

**Closed by ron-murhammer** 2017-03-12 02:32 UTC

**Comment by ssoloff** [comment] 2017-03-12 03:11
@ron-murhammer Got it.  Thanks!
