### ISSUE TITLE
Territory Name Image Loading Bug

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#899] opened 2016-06-28 23:06 UTC
On maps that use name images, some of them aren't loading properly (I'm guessing its a case issue). An example is WW2v5 where it looks like all single word names load but any names with spaces fail: 
![pre-release](https://cloud.githubusercontent.com/assets/1427689/16435354/fa8f9bfa-3d5a-11e6-95fb-a0cc498e7f93.png)

**Comment by DanVanAtta** [comment] 2016-06-28 23:17
@ron-murhammer The problem is not very clear. Could you give an example of a 'name' image that works and that does not, and give more details what is meant by "fail"?

Also, why assign this to me? Shouldn't anyone be able to pick this up? If you've identified where the problem is, paste it here, and whoever is available can then pick up from there. I really chafe at a culture that passes the buck when it comes to solving problems. Plus, I really think that issues should be opt-in. Ultimately if nobody else picks a problem, then @ron-murhammer  and I are on the hook for fixing problems. With that said though, all work on this project is voluntarily. Take into account that I could perhaps for example walk away from the project tomorrow. Hence the process we create should not track to individuals

**Comment by ron-murhammer** [comment] 2016-06-28 23:21
@DanVanAtta - Example on the above image added. Added you since it appears to be related to image loading so figured you have the most context. You can unassign if you want but figured you'd want to know the issue came up.

**Comment by DanVanAtta** [comment] 2016-06-29 00:48
I can see multiple things wrong in the image. Looking at v5, the name image: "Panama_Canal.png" loads on the map for me (using a case sensitive file system):
![canal-shows](https://cloud.githubusercontent.com/assets/12397753/16437067/66341050-3d58-11e6-9e74-dd9349a53d84.png)

@ron-murhammer  please spell out what is not working in the image, and if there is a specific image file that you know is not loading, please give it as an example if you would

**Comment by ron-murhammer** [comment] 2016-06-29 01:17
@DanVanAtta Panama Canal isn't a territory name but just a decoration I believe. The issue is territory names (both land and sea) that have spaces in them (all sea zones, baltic states, northwestern europe, etc) as mentioned above.

**Comment by DanVanAtta** [comment] 2016-06-29 05:37
Here is a before:

![__before](https://cloud.githubusercontent.com/assets/12397753/16440790/f6629c02-3d79-11e6-8337-2dace02413e9.png)

#899 is a quick fix to the problem.

**Comment by DanVanAtta** [comment] 2016-07-08 22:31
#900  Fixes

**Closed by DanVanAtta** 2016-07-08 22:31 UTC
Labels: Bug, Close Pending Confirmation, Regression
